In [5]:
%load_ext autoreload
%autoreload 2
import gym
import gym_battleship
from typing import List
import numpy as np
from agent.deterministic import deterministic_policy
from tqdm import tqdm

# Find a single size 3 ship on a 7x7 board
ship_sizes = {3: 1}
board_size = (7, 7)
episode_steps = 1000000  # way more than should ever be needed
reward_dictionary = {
    'win': 100,             # for sinking all ships
    'missed': -0.25,            # for missing a shot
    'hit': 1,               # for hitting a ship
    'repeat_missed': -1,    # for shooting at an already missed cell
    'repeat_hit': -1      # for shooting at an already hit cell
}

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload

In [6]:
def ship_dict_to_list(ship_dict: dict[int, int]) -> List[int]:
    ships = []
    for size in ship_dict:
        count = ship_dict[size]
        ships += [size] * count
    return ships

In [9]:

episodes = 1000
step_history = []
reward_history = []
env = gym.make('Battleship-v0', ship_sizes=ship_sizes, board_size=board_size, episode_steps=episode_steps, reward_dictionary=reward_dictionary)


for e in tqdm(range(0, episodes)):
    state = env.reset()
    ships = ship_dict_to_list(ship_sizes)
    done = False
    steps = 0
    rewards = 0

    while not done:
        action = deterministic_policy(state, ships)
        state, reward, done, remaining_ships = env.step(action)
        ships = ship_dict_to_list(remaining_ships)
        rewards += reward
        steps += 1

    #env.render()
    step_history.append(steps)
    reward_history.append(rewards)

print(f'Episodes: {episodes}')
print(
    f'Reward: min {np.min(reward_history)}, max {np.max(reward_history)}, mean {np.mean(reward_history)}, median: {np.median(reward_history)}')
print(
    f'Steps: min {np.min(step_history)}, max {np.max(step_history)}, mean {np.mean(step_history)}, median: {np.median(step_history)}')

  0%|          | 0/1000 [00:00<?, ?it/s]

   A  B  C  D  E  F  G
1  ⚫  ❌  ⚫  ⚫  ⬜  ⬜  ⬜
2  ⚫  ❌  ⬜  ⬜  ⚫  ⬜  ⬜
3  ⬜  ❌  ⚫  ⬜  ⬜  ⚫  ⬜
4  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜
5  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜
6  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

  0%|          | 1/1000 [00:00<04:24,  3.78it/s]

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
2  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
3  ⬜  ⬜  ❌  ⚫  ⬜  ⬜  ⬜
4  ⬜  ⬜  ❌  ⬜  ⬜  ⬜  ⬜
5  ⬜  ⬜  ❌  ⬜  ⬜  ⬜  ⬜
6  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜
2  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜
3  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜
4  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫
5  ⬜  ⚫  ⬜  ⬜  ⚫  ❌  ⬜
6  ⬜  ⬜  ⚫  ⬜  ⬜  ❌  ⚫
7  ⬜  ⬜  ⬜  ⬜  ⚫  ❌  ⬜

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⬜  ⬜  ❌  ⬜
2  ⬜  ⬜  ⬜  ⬜  ⚫  ❌  ⬜
3  ⬜  ⬜  ⚫  ⬜  ⬜  ❌  ⚫
4  ⬜  ⬜  ⬜  ⚫  ⬜  ⚫  ⬜
5  ⬜  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜
6  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜
2  ❌  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜
3  ❌  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜
4  ❌  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜
5  ⚫  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜
6  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ❌  ⚫  ⬜  ⚫  ⬜  ⬜  ⬜
2  ❌  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜
3  ❌  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜
4  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫
5  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜
6  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜
7  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜

  1%|          | 6/1000 [00:00<00:54, 18.10it/s]

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
2  ⬜  ⬜  ❌  ⬜  ⬜  ⬜  ⬜
3  ⬜  ⬜  ❌  ⚫  ⬜  ⬜  ⬜
4  ⬜  ⬜  ❌  ⬜  ⬜  ⬜  ⬜
5  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜  ⬜
6  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫
2  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜
3  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜
4  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫
5  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜
6  ⚫  ⚫  ⚫  ⬜  ⬜  ⚫  ⬜
7  ❌  ❌  ❌  ⚫  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜
2  ❌  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜
3  ❌  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜
4  ❌  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜
5  ⚫  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜
6  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⬜  ⚫  ⬜  ⚫  ⬜  ⬜  ⬜
2  ⚫  ❌  ⬜  ⬜  ⚫  ⬜  ⬜
3  ⬜  ❌  ⚫  ⬜  ⬜  ⚫  ⬜
4  ⬜  ❌  ⬜  ⚫  ⬜  ⬜  ⬜
5  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜
6  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

  1%|          | 10/1000 [00:00<00:41, 24.12it/s]

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
2  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
3  ⬜  ⬜  ❌  ❌  ❌  ⬜  ⬜
4  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜  ⬜
5  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
6  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
2  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
3  ⬜  ⬜  ⚫  ⬜  ⚫  ⬜  ⬜
4  ⬜  ⬜  ❌  ❌  ❌  ⚫  ⬜
5  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜
6  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜
2  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜
3  ⚫  ⚫  ⚫  ⬜  ⬜  ⚫  ⬜
4  ❌  ❌  ❌  ⚫  ⬜  ⬜  ⬜
5  ⚫  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜
6  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
2  ⬜  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜
3  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜
4  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜
5  ⬜  ⚫  ❌  ⬜  ⚫  ⬜  ⬜
6  ⬜  ⬜  ❌  ⚫  ⬜  ⬜  ⬜
7  ⬜  ⬜  ❌  ⚫  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜
2  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜
3  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫  ⚫
4  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜  ❌
5  ⬜  ⚫  ⬜  ⬜  ⚫  ⚫  ❌
6  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜  ❌
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

  2%|▏         | 15/1000 [00:00<00:32, 29.94it/s]

   A  B  C  D  E  F  G
1  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫
2  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜
3  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜
4  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫
5  ❌  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜
6  ❌  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜
7  ❌  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ❌  ⚫  ⬜  ⚫  ⬜  ⬜  ⬜
2  ❌  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜
3  ❌  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜
4  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫
5  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜
6  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜
7  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜
2  ⬜  ⬜  ⬜  ⚫  ❌  ❌  ❌
3  ⬜  ⬜  ⚫  ⬜  ⚫  ⬜  ⬜
4  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜
5  ⬜  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜
6  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜
2  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜
3  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫  ⚫
4  ⚫  ⬜  ⬜  ⚫  ❌  ❌  ❌
5  ⬜  ⚫  ⬜  ⬜  ⚫  ⚫  ⚫
6  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

  2%|▏         | 19/1000 [00:00<00:31, 30.74it/s]

   A  B  C  D  E  F  G
1  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫
2  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜
3  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜
4  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫
5  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜  ❌
6  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫  ❌
7  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜  ❌

   A  B  C  D  E  F  G
1  ⚫  ⬜  ⬜  ⚫  ❌  ❌  ❌
2  ⬜  ⚫  ⬜  ⬜  ⚫  ⚫  ⚫
3  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜
4  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫
5  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜
6  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜
7  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
2  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
3  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜  ⬜
4  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜
5  ⬜  ⬜  ⬜  ⬜  ❌  ❌  ❌
6  ⬜  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜
2  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜
3  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜
4  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫
5  ⬜  ⚫  ⬜  ❌  ⚫  ⬜  ⬜
6  ⬜  ⬜  ⚫  ❌  ⬜  ⚫  ⬜
7  ⬜  ⬜  ⚫  ❌  ⚫  ⬜  ⬜

  2%|▏         | 23/1000 [00:00<00:31, 31.24it/s]

   A  B  C  D  E  F  G
1  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫
2  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜
3  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜
4  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫
5  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜  ❌
6  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫  ❌
7  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜  ❌

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
2  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
3  ⬜  ⬜  ❌  ⚫  ⬜  ⬜  ⬜
4  ⬜  ⬜  ❌  ⬜  ⬜  ⬜  ⬜
5  ⬜  ⬜  ❌  ⬜  ⬜  ⬜  ⬜
6  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜
2  ⬜  ⬜  ⬜  ⚫  ❌  ❌  ❌
3  ⬜  ⬜  ⚫  ⬜  ⚫  ⬜  ⬜
4  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜
5  ⬜  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜
6  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜
2  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜
3  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫  ⚫
4  ⚫  ⬜  ⬜  ⚫  ❌  ❌  ❌
5  ⬜  ⚫  ⬜  ⬜  ⚫  ⚫  ⚫
6  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

  3%|▎         | 27/1000 [00:00<00:29, 32.93it/s]

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜
2  ⬜  ⬜  ⬜  ⚫  ❌  ⬜  ⬜
3  ⬜  ⬜  ⚫  ⬜  ❌  ⚫  ⬜
4  ⬜  ⬜  ⬜  ⚫  ❌  ⬜  ⬜
5  ⬜  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜
6  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
2  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
3  ⬜  ⬜  ⚫  ⬜  ❌  ⬜  ⬜
4  ⬜  ⬜  ⬜  ⚫  ❌  ⬜  ⬜
5  ⬜  ⬜  ⬜  ⬜  ❌  ⚫  ⬜
6  ⬜  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜
2  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜
3  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫  ⚫
4  ⚫  ⬜  ⬜  ⚫  ❌  ❌  ❌
5  ⬜  ⚫  ⬜  ⬜  ⚫  ⚫  ⚫
6  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
2  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
3  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜  ⬜
4  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜
5  ⬜  ⬜  ⬜  ⬜  ❌  ❌  ❌
6  ⬜  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

  3%|▎         | 31/1000 [00:01<00:28, 34.19it/s]

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜
2  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜  ❌
3  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫  ❌
4  ⚫  ⬜  ⬜  ⚫  ⬜  ⚫  ❌
5  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜  ⚫
6  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
2  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
3  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜  ⬜
4  ⬜  ⬜  ⬜  ❌  ⚫  ⬜  ⬜
5  ⬜  ⬜  ⬜  ❌  ⬜  ⬜  ⬜
6  ⬜  ⬜  ⬜  ❌  ⬜  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜
2  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜
3  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫  ⚫
4  ⚫  ⬜  ⬜  ⚫  ❌  ❌  ❌
5  ⬜  ⚫  ⬜  ⬜  ⚫  ⚫  ⚫
6  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜
2  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜
3  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫  ⚫
4  ⚫  ⬜  ⬜  ⚫  ❌  ❌  ❌
5  ⬜  ⚫  ⬜  ⬜  ⚫  ⚫  ⚫
6  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

  4%|▎         | 35/1000 [00:01<00:27, 34.80it/s]

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
2  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
3  ⬜  ⬜  ⚫  ⬜  ⚫  ⬜  ⬜
4  ⬜  ⬜  ⬜  ❌  ❌  ❌  ⬜
5  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜
6  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜
2  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜
3  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜
4  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫
5  ⬜  ⚫  ⬜  ❌  ⚫  ⬜  ⬜
6  ⬜  ⬜  ⚫  ❌  ⬜  ⚫  ⬜
7  ⬜  ⬜  ⚫  ❌  ⚫  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
2  ⬜  ⬜  ⬜  ⬜  ⚫  ⚫  ⬜
3  ⬜  ⬜  ⚫  ⬜  ❌  ❌  ❌
4  ⬜  ⬜  ⬜  ⚫  ⬜  ⚫  ⚫
5  ⬜  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜
6  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
2  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
3  ⬜  ⬜  ⚫  ⬜  ⚫  ⬜  ⬜
4  ⬜  ⬜  ⬜  ❌  ❌  ❌  ⬜
5  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜
6  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
2  ⬜  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜
3  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜
4  ⬜  ⬜  ❌  ⚫  ⬜  ⬜  ⬜
5  ⬜  ⚫  ❌  ⬜  ⚫  ⬜  ⬜
6  ⬜  ⬜  ❌  ⚫  ⬜  ⬜  ⬜
7  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜  ⬜

  4%|▍         | 40/1000 [00:01<00:26, 36.90it/s]

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
2  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
3  ⬜  ⬜  ❌  ⚫  ⬜  ⬜  ⬜
4  ⬜  ⬜  ❌  ⬜  ⬜  ⬜  ⬜
5  ⬜  ⬜  ❌  ⬜  ⬜  ⬜  ⬜
6  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
2  ⬜  ⬜  ⬜  ⬜  ⚫  ⚫  ⬜
3  ⬜  ⬜  ⚫  ⬜  ❌  ❌  ❌
4  ⬜  ⬜  ⬜  ⚫  ⬜  ⚫  ⚫
5  ⬜  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜
6  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
2  ⬜  ⬜  ⬜  ❌  ⬜  ⬜  ⬜
3  ⬜  ⬜  ⚫  ❌  ⬜  ⬜  ⬜
4  ⬜  ⬜  ⬜  ❌  ⚫  ⬜  ⬜
5  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜
6  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜
2  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜
3  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜
4  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫
5  ⬜  ⚫  ⬜  ⬜  ⚫  ⚫  ⬜
6  ⬜  ⬜  ⚫  ❌  ❌  ❌  ⚫
7  ⬜  ⬜  ⬜  ⬜  ⚫  ⚫  ⬜

   A  B  C  D  E  F  G
1  ❌  ⚫  ⬜  ⚫  ⬜  ⬜  ⬜
2  ❌  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜
3  ❌  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜
4  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫
5  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜
6  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜
7  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜

  4%|▍         | 45/1000 [00:01<00:24, 38.84it/s]

   A  B  C  D  E  F  G
1  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫
2  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜
3  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜
4  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫
5  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜
6  ⚫  ⚫  ⚫  ⬜  ⬜  ⚫  ⬜
7  ❌  ❌  ❌  ⚫  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ❌  ⚫  ⬜  ⚫  ⬜  ⬜  ⬜
2  ❌  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜
3  ❌  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜
4  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫
5  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜
6  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜
7  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
2  ⬜  ⬜  ⬜  ⬜  ⚫  ❌  ⬜
3  ⬜  ⬜  ⚫  ⬜  ⬜  ❌  ⚫
4  ⬜  ⬜  ⬜  ⚫  ⬜  ❌  ⚫
5  ⬜  ⬜  ⬜  ⬜  ⚫  ⚫  ⬜
6  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⬜  ⬜  ❌  ⬜
2  ⬜  ⬜  ⬜  ⬜  ⚫  ❌  ⬜
3  ⬜  ⬜  ⚫  ⬜  ⬜  ❌  ⚫
4  ⬜  ⬜  ⬜  ⚫  ⬜  ⚫  ⬜
5  ⬜  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜
6  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

  5%|▍         | 49/1000 [00:01<00:24, 38.23it/s]

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
2  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
3  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜  ⬜
4  ⬜  ⬜  ⬜  ⚫  ❌  ⬜  ⬜
5  ⬜  ⬜  ⬜  ⬜  ❌  ⚫  ⬜
6  ⬜  ⬜  ⬜  ⬜  ❌  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⚫  ⬜  ⬜  ⚫  ⬜  ⚫  ❌
2  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜  ❌
3  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫  ❌
4  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫
5  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜
6  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜
7  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⚫  ❌  ⚫  ⚫  ⬜  ⬜  ⬜
2  ⚫  ❌  ⬜  ⬜  ⚫  ⬜  ⬜
3  ⬜  ❌  ⚫  ⬜  ⬜  ⚫  ⬜
4  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜
5  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜
6  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜
2  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜
3  ⚫  ⚫  ⚫  ⬜  ⬜  ⚫  ⬜
4  ❌  ❌  ❌  ⚫  ⬜  ⬜  ⬜
5  ⚫  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜
6  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

  5%|▌         | 53/1000 [00:01<00:25, 37.83it/s]

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
2  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜  ⬜
3  ⬜  ❌  ❌  ❌  ⚫  ⬜  ⬜
4  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜  ⬜
5  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
6  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
2  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
3  ⬜  ⬜  ⚫  ⬜  ⚫  ⬜  ⬜
4  ⬜  ⬜  ❌  ❌  ❌  ⚫  ⬜
5  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜
6  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜
2  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜
3  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜
4  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫
5  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜
6  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜
7  ⬜  ⬜  ❌  ❌  ❌  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⬜  ❌  ❌  ❌  ⬜  ⬜  ⬜
2  ⬜  ⬜  ⚫  ⚫  ⚫  ⬜  ⬜
3  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜
4  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜
5  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜
6  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⬜  ⚫  ⚫  ⚫  ⬜  ⬜  ⬜
2  ⚫  ❌  ❌  ❌  ⚫  ⬜  ⬜
3  ⬜  ⚫  ⚫  ⬜  ⬜  ⚫  ⬜
4  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜
5  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜
6  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

  6%|▌         | 58/1000 [00:01<00:24, 38.83it/s]

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜
2  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜
3  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜
4  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫
5  ⬜  ⚫  ⬜  ⬜  ⚫  ⚫  ⬜
6  ⬜  ⬜  ⚫  ⬜  ❌  ❌  ❌
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⚫  ⬜

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⚫  ⚫  ⬜  ⬜
2  ⬜  ⬜  ❌  ❌  ❌  ⚫  ⬜
3  ⬜  ⬜  ⚫  ⬜  ⚫  ⬜  ⬜
4  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜
5  ⬜  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜
6  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
2  ⬜  ⬜  ⬜  ❌  ⬜  ⬜  ⬜
3  ⬜  ⬜  ⚫  ❌  ⬜  ⬜  ⬜
4  ⬜  ⬜  ⬜  ❌  ⚫  ⬜  ⬜
5  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜
6  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
2  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
3  ⬜  ⬜  ⚫  ⚫  ⬜  ⬜  ⬜
4  ⬜  ❌  ❌  ❌  ⚫  ⬜  ⬜
5  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜
6  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
2  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
3  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜  ⬜
4  ⬜  ⬜  ⬜  ⚫  ⚫  ⬜  ⬜
5  ⬜  ⬜  ❌  ❌  ❌  ⚫  ⬜
6  ⬜  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

  6%|▋         | 63/1000 [00:01<00:22, 41.15it/s]

   A  B  C  D  E  F  G
1  ⬜  ⚫  ❌  ❌  ❌  ⬜  ⬜
2  ⬜  ⬜  ⚫  ⚫  ⚫  ⬜  ⬜
3  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜
4  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜
5  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜
6  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ❌  ⚫  ⬜  ⚫  ⬜  ⬜  ⬜
2  ❌  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜
3  ❌  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜
4  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫
5  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜
6  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜
7  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜
2  ⬜  ⬜  ⬜  ⚫  ❌  ❌  ❌
3  ⬜  ⬜  ⚫  ⬜  ⚫  ⬜  ⬜
4  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜
5  ⬜  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜
6  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
2  ⬜  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜
3  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜
4  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜
5  ⬜  ⚫  ⚫  ⬜  ⚫  ⬜  ⬜
6  ❌  ❌  ❌  ⚫  ⬜  ⬜  ⬜
7  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⚫  ⚫  ⬜  ⚫  ⬜  ⬜  ⬜
2  ❌  ❌  ❌  ⬜  ⚫  ⬜  ⬜
3  ⚫  ⚫  ⚫  ⬜  ⬜  ⚫  ⬜
4  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜
5  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜
6  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

  7%|▋         | 68/1000 [00:02<00:23, 40.19it/s]

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
2  ⬜  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜
3  ⬜  ❌  ⚫  ⬜  ⬜  ⚫  ⬜
4  ⬜  ❌  ⬜  ⚫  ⬜  ⬜  ⬜
5  ⚫  ❌  ⚫  ⬜  ⚫  ⬜  ⬜
6  ⬜  ⚫  ⬜  ⬜  ⬜  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
2  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
3  ⬜  ⬜  ⚫  ❌  ⬜  ⬜  ⬜
4  ⬜  ⬜  ⬜  ❌  ⚫  ⬜  ⬜
5  ⬜  ⬜  ⚫  ❌  ⬜  ⬜  ⬜
6  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
2  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
3  ⬜  ⬜  ⚫  ⚫  ⬜  ⬜  ⬜
4  ⬜  ❌  ❌  ❌  ⚫  ⬜  ⬜
5  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜
6  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜
2  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜
3  ⚫  ⚫  ⚫  ⬜  ⬜  ⚫  ⬜
4  ❌  ❌  ❌  ⚫  ⬜  ⬜  ⬜
5  ⚫  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜
6  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫
2  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜
3  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜
4  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫
5  ❌  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜
6  ❌  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜
7  ❌  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜

  7%|▋         | 73/1000 [00:02<00:23, 39.52it/s]

   A  B  C  D  E  F  G
1  ⬜  ⬜  ❌  ⬜  ⬜  ⬜  ⬜
2  ⬜  ⬜  ❌  ⬜  ⬜  ⬜  ⬜
3  ⬜  ⬜  ❌  ⚫  ⬜  ⬜  ⬜
4  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜  ⬜
5  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
6  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
2  ⬜  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜
3  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜
4  ⬜  ❌  ⬜  ⚫  ⬜  ⬜  ⬜
5  ⚫  ❌  ⬜  ⬜  ⚫  ⬜  ⬜
6  ⬜  ❌  ⬜  ⬜  ⬜  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⚫  ❌  ❌  ❌  ⬜
2  ⬜  ⬜  ⬜  ⚫  ⚫  ⬜  ⬜
3  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜
4  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜
5  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜
6  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜
2  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜
3  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜
4  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫
5  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜
6  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜
7  ⬜  ⬜  ❌  ❌  ❌  ⬜  ⬜

  8%|▊         | 77/1000 [00:02<00:23, 39.32it/s]

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
2  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
3  ⬜  ⬜  ⚫  ⚫  ⬜  ⬜  ⬜
4  ⬜  ❌  ❌  ❌  ⚫  ⬜  ⬜
5  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜
6  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
2  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
3  ⬜  ⬜  ⚫  ⬜  ❌  ⬜  ⬜
4  ⬜  ⬜  ⬜  ⚫  ❌  ⬜  ⬜
5  ⬜  ⬜  ⬜  ⬜  ❌  ⚫  ⬜
6  ⬜  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
2  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜  ⬜
3  ⬜  ❌  ❌  ❌  ⚫  ⬜  ⬜
4  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜  ⬜
5  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
6  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
2  ⬜  ⬜  ⬜  ⬜  ⚫  ⚫  ⬜
3  ⬜  ⬜  ⚫  ❌  ❌  ❌  ⚫
4  ⬜  ⬜  ⬜  ⚫  ⬜  ⚫  ⬜
5  ⬜  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜
6  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜
2  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜
3  ⚫  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜
4  ❌  ⚫  ⬜  ⚫  ⬜  ⬜  ⬜
5  ❌  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜
6  ❌  ⬜  ⚫  ⬜  ⬜  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

  8%|▊         | 82/1000 [00:02<00:22, 41.44it/s]

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
2  ⬜  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜
3  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜
4  ⬜  ⚫  ⬜  ⚫  ⬜  ⬜  ⬜
5  ⚫  ❌  ⬜  ⬜  ⚫  ⬜  ⬜
6  ⬜  ❌  ⚫  ⬜  ⬜  ⬜  ⬜
7  ⬜  ❌  ⬜  ⬜  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⬜  ⬜  ❌  ⬜  ⬜  ⬜  ⬜
2  ⬜  ⬜  ❌  ⬜  ⬜  ⬜  ⬜
3  ⬜  ⬜  ❌  ⚫  ⬜  ⬜  ⬜
4  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜  ⬜
5  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
6  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
2  ⬜  ⬜  ⬜  ⬜  ⚫  ❌  ⬜
3  ⬜  ⬜  ⚫  ⬜  ⬜  ❌  ⚫
4  ⬜  ⬜  ⬜  ⚫  ⬜  ❌  ⚫
5  ⬜  ⬜  ⬜  ⬜  ⚫  ⚫  ⬜
6  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜
2  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜
3  ⚫  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜
4  ❌  ⚫  ⬜  ⚫  ⬜  ⬜  ⬜
5  ❌  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜
6  ❌  ⬜  ⚫  ⬜  ⬜  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
2  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
3  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜  ⬜
4  ⬜  ⬜  ⬜  ⚫  ⚫  ⬜  ⬜
5  ⬜  ⬜  ⬜  ❌  ❌  ❌  ⚫
6  ⬜  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

  9%|▊         | 87/1000 [00:02<00:21, 42.30it/s]

   A  B  C  D  E  F  G
1  ⬜  ⚫  ⚫  ⚫  ⬜  ⬜  ⬜
2  ⚫  ❌  ❌  ❌  ⚫  ⬜  ⬜
3  ⬜  ⚫  ⚫  ⬜  ⬜  ⚫  ⬜
4  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜
5  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜
6  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
2  ⬜  ⬜  ⬜  ⬜  ⚫  ⚫  ⬜
3  ⬜  ⬜  ⚫  ⬜  ❌  ❌  ❌
4  ⬜  ⬜  ⬜  ⚫  ⬜  ⚫  ⚫
5  ⬜  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜
6  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⚫  ⚫  ⬜  ⚫  ⬜  ⬜  ⬜
2  ❌  ❌  ❌  ⬜  ⚫  ⬜  ⬜
3  ⚫  ⚫  ⚫  ⬜  ⬜  ⚫  ⬜
4  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜
5  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜
6  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜
2  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜
3  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫  ⚫
4  ⚫  ⬜  ⬜  ⚫  ❌  ❌  ❌
5  ⬜  ⚫  ⬜  ⬜  ⚫  ⚫  ⚫
6  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
2  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
3  ⬜  ⬜  ⚫  ❌  ⬜  ⬜  ⬜
4  ⬜  ⬜  ⬜  ❌  ⚫  ⬜  ⬜
5  ⬜  ⬜  ⚫  ❌  ⬜  ⬜  ⬜
6  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

  9%|▉         | 92/1000 [00:02<00:22, 40.76it/s]

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
2  ⬜  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜
3  ⬜  ⬜  ⚫  ⬜  ⬜  ❌  ⚫
4  ⬜  ⬜  ⬜  ⚫  ⬜  ❌  ⬜
5  ⬜  ⬜  ⬜  ⬜  ⚫  ❌  ⬜
6  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜
2  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜
3  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜
4  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫
5  ⬜  ⚫  ⬜  ⬜  ⚫  ⚫  ⬜
6  ⬜  ⬜  ⚫  ⬜  ❌  ❌  ❌
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⚫  ⬜

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
2  ⬜  ⬜  ❌  ⬜  ⬜  ⬜  ⬜
3  ⬜  ⬜  ❌  ⚫  ⬜  ⬜  ⬜
4  ⬜  ⬜  ❌  ⬜  ⬜  ⬜  ⬜
5  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜  ⬜
6  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
2  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜  ⬜
3  ❌  ❌  ❌  ⚫  ⬜  ⬜  ⬜
4  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜  ⬜
5  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
6  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
2  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
3  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜  ⬜
4  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜
5  ⬜  ⬜  ⬜  ⬜  ❌  ⚫  ⬜
6  ⬜  ⬜  ⬜  ⬜  ❌  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ❌  ⬜  ⬜

 10%|▉         | 97/1000 [00:02<00:21, 42.65it/s]

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
2  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
3  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜  ⬜
4  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜
5  ⬜  ⬜  ⬜  ⬜  ❌  ⚫  ⬜
6  ⬜  ⬜  ⬜  ⬜  ❌  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ❌  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
2  ⬜  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜
3  ⬜  ⬜  ⚫  ⬜  ⬜  ❌  ⚫
4  ⬜  ⬜  ⬜  ⚫  ⬜  ❌  ⬜
5  ⬜  ⬜  ⬜  ⬜  ⚫  ❌  ⬜
6  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫
2  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜
3  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜
4  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫
5  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜
6  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫  ⚫
7  ⚫  ⬜  ⬜  ⚫  ❌  ❌  ❌

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⚫  ❌  ⬜  ⬜
2  ⬜  ⬜  ⬜  ⬜  ❌  ⬜  ⬜
3  ⬜  ⬜  ⚫  ⬜  ❌  ⬜  ⬜
4  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜
5  ⬜  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜
6  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ❌  ❌  ❌  ⚫  ⬜  ⬜  ⬜
2  ⚫  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜
3  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜
4  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫
5  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜
6  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜
7  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜

 10%|█         | 102/1000 [00:02<00:24, 37.23it/s]

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜
2  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜
3  ⚫  ⚫  ⚫  ⬜  ⬜  ⚫  ⬜
4  ❌  ❌  ❌  ⚫  ⬜  ⬜  ⬜
5  ⚫  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜
6  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⚫  ❌  ⚫  ⬜  ⬜
2  ⬜  ⬜  ⚫  ❌  ⚫  ⬜  ⬜
3  ⬜  ⬜  ⚫  ❌  ⬜  ⚫  ⬜
4  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜
5  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜
6  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
2  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
3  ⬜  ⬜  ⚫  ⚫  ⬜  ⬜  ⬜
4  ⬜  ❌  ❌  ❌  ⚫  ⬜  ⬜
5  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜
6  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
2  ⬜  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜
3  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜
4  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜
5  ❌  ❌  ❌  ⬜  ⚫  ⬜  ⬜
6  ⬜  ⚫  ⬜  ⬜  ⬜  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

 11%|█         | 106/1000 [00:02<00:23, 37.77it/s]

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
2  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
3  ⬜  ⬜  ⚫  ⬜  ⚫  ⬜  ⬜
4  ⬜  ⬜  ❌  ❌  ❌  ⚫  ⬜
5  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜
6  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
2  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
3  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜  ⬜
4  ⬜  ⬜  ⬜  ⚫  ❌  ⬜  ⬜
5  ⬜  ⬜  ⬜  ⬜  ❌  ⚫  ⬜
6  ⬜  ⬜  ⬜  ⬜  ❌  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
2  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
3  ⬜  ⬜  ❌  ❌  ❌  ⬜  ⬜
4  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜  ⬜
5  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
6  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜
2  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜  ❌
3  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫  ❌
4  ⚫  ⬜  ⬜  ⚫  ⬜  ⚫  ❌
5  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜  ⚫
6  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜
2  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜
3  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜
4  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫
5  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜
6  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜
7  ⬜  ❌  ❌  ❌  ⚫  ⬜  ⬜

 11%|█         | 111/1000 [00:03<00:22, 39.26it/s]

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜
2  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜
3  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜
4  ⚫  ⬜  ⬜  ⚫  ⬜  ❌  ⚫
5  ⬜  ⚫  ⬜  ⬜  ⚫  ❌  ⬜
6  ⬜  ⬜  ⚫  ⬜  ⬜  ❌  ⚫
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⚫  ⬜

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
2  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
3  ⬜  ⬜  ⚫  ⬜  ⚫  ⬜  ⬜
4  ⬜  ⬜  ⬜  ❌  ❌  ❌  ⬜
5  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜
6  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⬜  ⚫  ⬜  ⚫  ⬜  ⬜  ⬜
2  ⚫  ❌  ⬜  ⬜  ⚫  ⬜  ⬜
3  ⬜  ❌  ⚫  ⬜  ⬜  ⚫  ⬜
4  ⬜  ❌  ⬜  ⚫  ⬜  ⬜  ⬜
5  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜
6  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜
2  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜
3  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜
4  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫
5  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜
6  ⬜  ⬜  ⚫  ⚫  ⚫  ⚫  ⬜
7  ⬜  ⬜  ⚫  ❌  ❌  ❌  ⬜

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜
2  ❌  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜
3  ❌  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜
4  ❌  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜
5  ⚫  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜
6  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

 12%|█▏        | 116/1000 [00:03<00:23, 38.36it/s]

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜
2  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜
3  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫  ❌
4  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜  ❌
5  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜  ❌
6  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⚫  ❌  ⚫  ⚫  ⬜  ⬜  ⬜
2  ⚫  ❌  ⬜  ⬜  ⚫  ⬜  ⬜
3  ⬜  ❌  ⚫  ⬜  ⬜  ⚫  ⬜
4  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜
5  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜
6  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
2  ⬜  ⬜  ⬜  ⬜  ⚫  ⚫  ⬜
3  ⬜  ⬜  ⚫  ⬜  ❌  ❌  ❌
4  ⬜  ⬜  ⬜  ⚫  ⬜  ⚫  ⚫
5  ⬜  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜
6  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⬜  ❌  ❌  ❌  ⬜  ⬜  ⬜
2  ⬜  ⬜  ⚫  ⚫  ⚫  ⬜  ⬜
3  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜
4  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜
5  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜
6  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

 12%|█▏        | 120/1000 [00:03<00:22, 38.26it/s]

   A  B  C  D  E  F  G
1  ⚫  ⬜  ⬜  ⚫  ⬜  ⚫  ❌
2  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜  ❌
3  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫  ❌
4  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫
5  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜
6  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜
7  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
2  ⬜  ⬜  ❌  ⬜  ⬜  ⬜  ⬜
3  ⬜  ⬜  ❌  ⚫  ⬜  ⬜  ⬜
4  ⬜  ⬜  ❌  ⬜  ⬜  ⬜  ⬜
5  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜  ⬜
6  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⬜  ⚫  ❌  ❌  ❌  ⬜  ⬜
2  ⬜  ⬜  ⚫  ⚫  ⚫  ⬜  ⬜
3  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜
4  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜
5  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜
6  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
2  ⬜  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜
3  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜
4  ⬜  ❌  ⬜  ⚫  ⬜  ⬜  ⬜
5  ⚫  ❌  ⬜  ⬜  ⚫  ⬜  ⬜
6  ⬜  ❌  ⬜  ⬜  ⬜  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⬜  ⬜  ❌  ⬜  ⬜  ⬜  ⬜
2  ⬜  ⬜  ❌  ⬜  ⬜  ⬜  ⬜
3  ⬜  ⬜  ❌  ⚫  ⬜  ⬜  ⬜
4  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜  ⬜
5  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
6  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

 12%|█▎        | 125/1000 [00:03<00:21, 40.12it/s]

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
2  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
3  ⬜  ⬜  ⚫  ❌  ⬜  ⬜  ⬜
4  ⬜  ⬜  ⬜  ❌  ⚫  ⬜  ⬜
5  ⬜  ⬜  ⚫  ❌  ⬜  ⬜  ⬜
6  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫
2  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜
3  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜
4  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫
5  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜  ❌
6  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫  ❌
7  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜  ❌

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
2  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
3  ⬜  ⬜  ⚫  ❌  ⬜  ⬜  ⬜
4  ⬜  ⬜  ⬜  ❌  ⚫  ⬜  ⬜
5  ⬜  ⬜  ⚫  ❌  ⬜  ⬜  ⬜
6  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
2  ⬜  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜
3  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜
4  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜
5  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜
6  ⬜  ⬜  ❌  ❌  ❌  ⬜  ⬜
7  ⬜  ⬜  ⚫  ⚫  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⚫  ❌  ⬜  ⬜
2  ⬜  ⬜  ⬜  ⬜  ❌  ⬜  ⬜
3  ⬜  ⬜  ⚫  ⬜  ❌  ⬜  ⬜
4  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜
5  ⬜  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜
6  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

 13%|█▎        | 130/1000 [00:03<00:21, 41.23it/s]

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
2  ⬜  ⬜  ⬜  ❌  ⬜  ⬜  ⬜
3  ⬜  ⬜  ⚫  ❌  ⬜  ⬜  ⬜
4  ⬜  ⬜  ⬜  ❌  ⚫  ⬜  ⬜
5  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜
6  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜
2  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜
3  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫  ⚫
4  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜  ❌
5  ⬜  ⚫  ⬜  ⬜  ⚫  ⚫  ❌
6  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜  ❌
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
2  ⬜  ⬜  ⬜  ⬜  ⚫  ⚫  ⬜
3  ⬜  ⬜  ⚫  ⬜  ❌  ❌  ❌
4  ⬜  ⬜  ⬜  ⚫  ⬜  ⚫  ⚫
5  ⬜  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜
6  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
2  ⬜  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜
3  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜
4  ⬜  ⚫  ⬜  ⚫  ⬜  ⬜  ⬜
5  ⚫  ❌  ⬜  ⬜  ⚫  ⬜  ⬜
6  ⬜  ❌  ⚫  ⬜  ⬜  ⬜  ⬜
7  ⬜  ❌  ⬜  ⬜  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⚫  ⬜  ⬜  ⚫  ⬜  ⚫  ❌
2  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜  ❌
3  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫  ❌
4  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫
5  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜
6  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜
7  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜

 14%|█▎        | 135/1000 [00:03<00:21, 40.81it/s]

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜
2  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜
3  ⚫  ⚫  ⚫  ⬜  ⬜  ⚫  ⬜
4  ❌  ❌  ❌  ⚫  ⬜  ⬜  ⬜
5  ⚫  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜
6  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⬜  ⚫  ⬜  ⚫  ⬜  ⬜  ⬜
2  ⚫  ❌  ⬜  ⬜  ⚫  ⬜  ⬜
3  ⬜  ❌  ⚫  ⬜  ⬜  ⚫  ⬜
4  ⬜  ❌  ⬜  ⚫  ⬜  ⬜  ⬜
5  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜
6  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫
2  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜
3  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜
4  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫
5  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜
6  ⚫  ⚫  ⚫  ⬜  ⬜  ⚫  ⬜
7  ❌  ❌  ❌  ⚫  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
2  ⬜  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜
3  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜
4  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜
5  ❌  ❌  ❌  ⬜  ⚫  ⬜  ⬜
6  ⬜  ⚫  ⬜  ⬜  ⬜  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜
2  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜
3  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜
4  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫
5  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜
6  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜
7  ⬜  ❌  ❌  ❌  ⚫  ⬜  ⬜

 14%|█▍        | 140/1000 [00:03<00:22, 37.40it/s]

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
2  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
3  ⬜  ⬜  ❌  ❌  ❌  ⬜  ⬜
4  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜  ⬜
5  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
6  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜
2  ⬜  ⬜  ⬜  ⚫  ❌  ⬜  ⬜
3  ⬜  ⬜  ⚫  ⬜  ❌  ⚫  ⬜
4  ⬜  ⬜  ⬜  ⚫  ❌  ⬜  ⬜
5  ⬜  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜
6  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⚫  ❌  ❌  ❌  ⬜
2  ⬜  ⬜  ⬜  ⚫  ⚫  ⬜  ⬜
3  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜
4  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜
5  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜
6  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜
2  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜
3  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫  ❌
4  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜  ❌
5  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜  ❌
6  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
2  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
3  ⬜  ⬜  ⚫  ⚫  ⬜  ⬜  ⬜
4  ⬜  ❌  ❌  ❌  ⚫  ⬜  ⬜
5  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜
6  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

 14%|█▍        | 145/1000 [00:03<00:21, 40.03it/s]

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜
2  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜  ❌
3  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫  ❌
4  ⚫  ⬜  ⬜  ⚫  ⬜  ⚫  ❌
5  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜  ⚫
6  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
2  ⬜  ⬜  ⬜  ⬜  ⚫  ⚫  ⬜
3  ⬜  ⬜  ⚫  ⬜  ❌  ❌  ❌
4  ⬜  ⬜  ⬜  ⚫  ⬜  ⚫  ⚫
5  ⬜  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜
6  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫
2  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜
3  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜
4  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫
5  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜
6  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫  ⚫
7  ⚫  ⬜  ⬜  ⚫  ❌  ❌  ❌

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
2  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
3  ⬜  ⬜  ⚫  ⬜  ⚫  ⬜  ⬜
4  ⬜  ⬜  ⬜  ❌  ❌  ❌  ⬜
5  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜
6  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⬜  ⬜  ❌  ⬜  ⬜  ⬜  ⬜
2  ⬜  ⬜  ❌  ⬜  ⬜  ⬜  ⬜
3  ⬜  ⬜  ❌  ⚫  ⬜  ⬜  ⬜
4  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜  ⬜
5  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
6  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

 15%|█▌        | 150/1000 [00:04<00:21, 40.01it/s]

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜
2  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜
3  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫  ⚫
4  ⚫  ⬜  ⬜  ⚫  ❌  ❌  ❌
5  ⬜  ⚫  ⬜  ⬜  ⚫  ⚫  ⚫
6  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫
2  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜
3  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜
4  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫
5  ❌  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜
6  ❌  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜
7  ❌  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
2  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
3  ⬜  ⬜  ⚫  ⬜  ⚫  ⬜  ⬜
4  ⬜  ⬜  ⬜  ❌  ❌  ❌  ⬜
5  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜
6  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
2  ⬜  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜
3  ⬜  ⬜  ⚫  ⬜  ⬜  ❌  ⚫
4  ⬜  ⬜  ⬜  ⚫  ⬜  ❌  ⬜
5  ⬜  ⬜  ⬜  ⬜  ⚫  ❌  ⬜
6  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⚫  ⚫  ⬜  ⬜
2  ⬜  ⬜  ❌  ❌  ❌  ⚫  ⬜
3  ⬜  ⬜  ⚫  ⬜  ⚫  ⬜  ⬜
4  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜
5  ⬜  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜
6  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

 16%|█▌        | 155/1000 [00:04<00:20, 40.27it/s]

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
2  ⬜  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜
3  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜
4  ⬜  ⬜  ❌  ⚫  ⬜  ⬜  ⬜
5  ⬜  ⚫  ❌  ⬜  ⚫  ⬜  ⬜
6  ⬜  ⬜  ❌  ⚫  ⬜  ⬜  ⬜
7  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
2  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
3  ⬜  ⬜  ❌  ⚫  ⬜  ⬜  ⬜
4  ⬜  ⬜  ❌  ⬜  ⬜  ⬜  ⬜
5  ⬜  ⬜  ❌  ⬜  ⬜  ⬜  ⬜
6  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜
2  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜
3  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫  ⚫
4  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜  ❌
5  ⬜  ⚫  ⬜  ⬜  ⚫  ⚫  ❌
6  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜  ❌
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
2  ⬜  ⬜  ⬜  ⬜  ⚫  ❌  ⬜
3  ⬜  ⬜  ⚫  ⬜  ⬜  ❌  ⚫
4  ⬜  ⬜  ⬜  ⚫  ⬜  ❌  ⚫
5  ⬜  ⬜  ⬜  ⬜  ⚫  ⚫  ⬜
6  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
2  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
3  ⬜  ⬜  ⚫  ⚫  ⬜  ⬜  ⬜
4  ⬜  ❌  ❌  ❌  ⚫  ⬜  ⬜
5  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜
6  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

 16%|█▌        | 160/1000 [00:04<00:19, 42.52it/s]

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
2  ⬜  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜
3  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜
4  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜
5  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜
6  ⬜  ⬜  ❌  ❌  ❌  ⬜  ⬜
7  ⬜  ⬜  ⚫  ⚫  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
2  ⬜  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜
3  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜
4  ⬜  ❌  ⬜  ⚫  ⬜  ⬜  ⬜
5  ⚫  ❌  ⬜  ⬜  ⚫  ⬜  ⬜
6  ⬜  ❌  ⬜  ⬜  ⬜  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜
2  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜
3  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫  ⚫
4  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜  ❌
5  ⬜  ⚫  ⬜  ⬜  ⚫  ⚫  ❌
6  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜  ❌
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
2  ⬜  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜
3  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜
4  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜
5  ⬜  ⚫  ⚫  ⬜  ⚫  ⬜  ⬜
6  ⬜  ❌  ❌  ❌  ⚫  ⬜  ⬜
7  ⬜  ⬜  ⚫  ⚫  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⚫  ⬜  ⬜  ⚫  ⬜  ⚫  ❌
2  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜  ❌
3  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫  ❌
4  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫
5  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜
6  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜
7  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜

 16%|█▋        | 165/1000 [00:04<00:20, 41.55it/s]

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
2  ⬜  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜
3  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜
4  ⬜  ⚫  ⬜  ⚫  ⬜  ⬜  ⬜
5  ⚫  ❌  ⬜  ⬜  ⚫  ⬜  ⬜
6  ⬜  ❌  ⚫  ⬜  ⬜  ⬜  ⬜
7  ⬜  ❌  ⬜  ⬜  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⚫  ⬜  ⬜  ⚫  ❌  ❌  ❌
2  ⬜  ⚫  ⬜  ⬜  ⚫  ⚫  ⚫
3  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜
4  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫
5  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜
6  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜
7  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
2  ⬜  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜
3  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜
4  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜
5  ❌  ❌  ❌  ⬜  ⚫  ⬜  ⬜
6  ⬜  ⚫  ⬜  ⬜  ⬜  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
2  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
3  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜  ⬜
4  ⬜  ⬜  ⬜  ⚫  ❌  ⬜  ⬜
5  ⬜  ⬜  ⬜  ⬜  ❌  ⚫  ⬜
6  ⬜  ⬜  ⬜  ⬜  ❌  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⬜  ⬜  ❌  ⬜
2  ⬜  ⬜  ⬜  ⬜  ⚫  ❌  ⬜
3  ⬜  ⬜  ⚫  ⬜  ⬜  ❌  ⚫
4  ⬜  ⬜  ⬜  ⚫  ⬜  ⚫  ⬜
5  ⬜  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜
6  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

 17%|█▋        | 170/1000 [00:04<00:19, 41.72it/s]

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜
2  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜
3  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜
4  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫
5  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜
6  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜
7  ⬜  ❌  ❌  ❌  ⚫  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫
2  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜
3  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜
4  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫
5  ❌  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜
6  ❌  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜
7  ❌  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
2  ⬜  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜
3  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜
4  ⬜  ⚫  ⬜  ⚫  ⬜  ⬜  ⬜
5  ⚫  ❌  ⬜  ⬜  ⚫  ⬜  ⬜
6  ⬜  ❌  ⚫  ⬜  ⬜  ⬜  ⬜
7  ⬜  ❌  ⬜  ⬜  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
2  ⬜  ⬜  ❌  ⬜  ⬜  ⬜  ⬜
3  ⬜  ⬜  ❌  ⚫  ⬜  ⬜  ⬜
4  ⬜  ⬜  ❌  ⬜  ⬜  ⬜  ⬜
5  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜  ⬜
6  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
2  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
3  ⬜  ⬜  ⚫  ❌  ⬜  ⬜  ⬜
4  ⬜  ⬜  ⬜  ❌  ⚫  ⬜  ⬜
5  ⬜  ⬜  ⚫  ❌  ⬜  ⬜  ⬜
6  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

 18%|█▊        | 175/1000 [00:04<00:19, 41.46it/s]

   A  B  C  D  E  F  G
1  ⬜  ⚫  ⚫  ⚫  ⬜  ⬜  ⬜
2  ⚫  ❌  ❌  ❌  ⚫  ⬜  ⬜
3  ⬜  ⚫  ⚫  ⬜  ⬜  ⚫  ⬜
4  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜
5  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜
6  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜
2  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜
3  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫  ⚫
4  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜  ❌
5  ⬜  ⚫  ⬜  ⬜  ⚫  ⚫  ❌
6  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜  ❌
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
2  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
3  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜  ⬜
4  ⬜  ⬜  ⬜  ⚫  ⚫  ⬜  ⬜
5  ⬜  ⬜  ⬜  ❌  ❌  ❌  ⚫
6  ⬜  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜
2  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜
3  ⚫  ⚫  ⚫  ⬜  ⬜  ⚫  ⬜
4  ❌  ❌  ❌  ⚫  ⬜  ⬜  ⬜
5  ⚫  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜
6  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
2  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜  ⬜
3  ❌  ❌  ❌  ⚫  ⬜  ⬜  ⬜
4  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜  ⬜
5  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
6  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

 18%|█▊        | 180/1000 [00:04<00:19, 41.11it/s]

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
2  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
3  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜  ⬜
4  ⬜  ⬜  ⬜  ⚫  ❌  ⬜  ⬜
5  ⬜  ⬜  ⬜  ⬜  ❌  ⚫  ⬜
6  ⬜  ⬜  ⬜  ⬜  ❌  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
2  ⬜  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜
3  ⬜  ❌  ⚫  ⬜  ⬜  ⚫  ⬜
4  ⬜  ❌  ⬜  ⚫  ⬜  ⬜  ⬜
5  ⚫  ❌  ⚫  ⬜  ⚫  ⬜  ⬜
6  ⬜  ⚫  ⬜  ⬜  ⬜  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
2  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
3  ⬜  ⬜  ⚫  ❌  ⬜  ⬜  ⬜
4  ⬜  ⬜  ⬜  ❌  ⚫  ⬜  ⬜
5  ⬜  ⬜  ⚫  ❌  ⬜  ⬜  ⬜
6  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⚫  ⚫  ⬜  ⚫  ⬜  ⬜  ⬜
2  ❌  ❌  ❌  ⬜  ⚫  ⬜  ⬜
3  ⚫  ⚫  ⚫  ⬜  ⬜  ⚫  ⬜
4  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜
5  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜
6  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⬜  ⚫  ⬜  ⚫  ⬜  ⬜  ⬜
2  ⚫  ❌  ⬜  ⬜  ⚫  ⬜  ⬜
3  ⬜  ❌  ⚫  ⬜  ⬜  ⚫  ⬜
4  ⬜  ❌  ⬜  ⚫  ⬜  ⬜  ⬜
5  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜
6  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

 18%|█▊        | 185/1000 [00:04<00:19, 42.05it/s]

   A  B  C  D  E  F  G
1  ❌  ❌  ❌  ⚫  ⬜  ⬜  ⬜
2  ⚫  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜
3  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜
4  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫
5  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜
6  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜
7  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫
2  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜
3  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜
4  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫
5  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜
6  ⚫  ⚫  ⚫  ⬜  ⬜  ⚫  ⬜
7  ❌  ❌  ❌  ⚫  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
2  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
3  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜  ⬜
4  ⬜  ⬜  ⬜  ❌  ⚫  ⬜  ⬜
5  ⬜  ⬜  ⬜  ❌  ⬜  ⬜  ⬜
6  ⬜  ⬜  ⬜  ❌  ⬜  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜
2  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜  ❌
3  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫  ❌
4  ⚫  ⬜  ⬜  ⚫  ⬜  ⚫  ❌
5  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜  ⚫
6  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
2  ⬜  ⬜  ⬜  ❌  ⬜  ⬜  ⬜
3  ⬜  ⬜  ⚫  ❌  ⬜  ⬜  ⬜
4  ⬜  ⬜  ⬜  ❌  ⚫  ⬜  ⬜
5  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜
6  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

 19%|█▉        | 190/1000 [00:05<00:19, 41.16it/s]

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
2  ⬜  ⬜  ⬜  ⬜  ⚫  ❌  ⬜
3  ⬜  ⬜  ⚫  ⬜  ⬜  ❌  ⚫
4  ⬜  ⬜  ⬜  ⚫  ⬜  ❌  ⚫
5  ⬜  ⬜  ⬜  ⬜  ⚫  ⚫  ⬜
6  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⚫  ❌  ⚫  ⚫  ⬜  ⬜  ⬜
2  ⚫  ❌  ⬜  ⬜  ⚫  ⬜  ⬜
3  ⬜  ❌  ⚫  ⬜  ⬜  ⚫  ⬜
4  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜
5  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜
6  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
2  ⬜  ⬜  ⬜  ⬜  ⚫  ⚫  ⬜
3  ⬜  ⬜  ⚫  ⬜  ❌  ❌  ❌
4  ⬜  ⬜  ⬜  ⚫  ⬜  ⚫  ⚫
5  ⬜  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜
6  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
2  ⬜  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜
3  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜
4  ⬜  ⬜  ❌  ⚫  ⬜  ⬜  ⬜
5  ⬜  ⚫  ❌  ⬜  ⚫  ⬜  ⬜
6  ⬜  ⬜  ❌  ⚫  ⬜  ⬜  ⬜
7  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
2  ⬜  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜
3  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜
4  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜
5  ⬜  ⚫  ❌  ⬜  ⚫  ⬜  ⬜
6  ⬜  ⬜  ❌  ⚫  ⬜  ⬜  ⬜
7  ⬜  ⬜  ❌  ⚫  ⬜  ⬜  ⬜

 20%|█▉        | 195/1000 [00:05<00:19, 41.24it/s]

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
2  ⬜  ⬜  ⬜  ⬜  ⚫  ⚫  ⬜
3  ⬜  ⬜  ⚫  ⬜  ❌  ❌  ❌
4  ⬜  ⬜  ⬜  ⚫  ⬜  ⚫  ⚫
5  ⬜  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜
6  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
2  ⬜  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜
3  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜
4  ⬜  ❌  ⬜  ⚫  ⬜  ⬜  ⬜
5  ⚫  ❌  ⬜  ⬜  ⚫  ⬜  ⬜
6  ⬜  ❌  ⬜  ⬜  ⬜  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⚫  ⬜  ⬜  ⚫  ⬜  ⚫  ❌
2  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜  ❌
3  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫  ❌
4  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫
5  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜
6  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜
7  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
2  ⬜  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜
3  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜
4  ⬜  ❌  ⬜  ⚫  ⬜  ⬜  ⬜
5  ⚫  ❌  ⬜  ⬜  ⚫  ⬜  ⬜
6  ⬜  ❌  ⬜  ⬜  ⬜  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
2  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
3  ⬜  ⬜  ⚫  ❌  ⬜  ⬜  ⬜
4  ⬜  ⬜  ⬜  ❌  ⚫  ⬜  ⬜
5  ⬜  ⬜  ⚫  ❌  ⬜  ⬜  ⬜
6  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

 20%|██        | 200/1000 [00:05<00:19, 40.46it/s]

   A  B  C  D  E  F  G
1  ⬜  ⬜  ❌  ⬜  ⬜  ⬜  ⬜
2  ⬜  ⬜  ❌  ⬜  ⬜  ⬜  ⬜
3  ⬜  ⬜  ❌  ⚫  ⬜  ⬜  ⬜
4  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜  ⬜
5  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
6  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⬜  ⬜  ❌  ⬜
2  ⬜  ⬜  ⬜  ⬜  ⚫  ❌  ⬜
3  ⬜  ⬜  ⚫  ⬜  ⬜  ❌  ⚫
4  ⬜  ⬜  ⬜  ⚫  ⬜  ⚫  ⬜
5  ⬜  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜
6  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
2  ⬜  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜
3  ⬜  ⬜  ⚫  ⬜  ⬜  ❌  ⚫
4  ⬜  ⬜  ⬜  ⚫  ⬜  ❌  ⬜
5  ⬜  ⬜  ⬜  ⬜  ⚫  ❌  ⬜
6  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
2  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
3  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜  ⬜
4  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜
5  ⬜  ⬜  ⬜  ⬜  ❌  ⚫  ⬜
6  ⬜  ⬜  ⬜  ⬜  ❌  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ❌  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
2  ⬜  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜
3  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜
4  ⬜  ⬜  ❌  ⚫  ⬜  ⬜  ⬜
5  ⬜  ⚫  ❌  ⬜  ⚫  ⬜  ⬜
6  ⬜  ⬜  ❌  ⚫  ⬜  ⬜  ⬜
7  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
2  ⬜  ⬜  ⬜  ⬜  ⚫  ⚫  ⬜
3  ⬜  ⬜  ⚫  ❌  ❌  ❌  ⚫
4  ⬜  ⬜  ⬜  ⚫  ⬜  ⚫  ⬜
5  ⬜  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜
6  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

 21%|██        | 206/1000 [00:05<00:18, 43.44it/s]

   A  B  C  D  E  F  G
1  ⬜  ⚫  ❌  ❌  ❌  ⬜  ⬜
2  ⬜  ⬜  ⚫  ⚫  ⚫  ⬜  ⬜
3  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜
4  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜
5  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜
6  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜
2  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜
3  ⚫  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜
4  ❌  ⚫  ⬜  ⚫  ⬜  ⬜  ⬜
5  ❌  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜
6  ❌  ⬜  ⚫  ⬜  ⬜  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⬜  ⚫  ⚫  ⚫  ⬜  ⬜  ⬜
2  ⚫  ❌  ❌  ❌  ⚫  ⬜  ⬜
3  ⬜  ⚫  ⚫  ⬜  ⬜  ⚫  ⬜
4  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜
5  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜
6  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
2  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
3  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜  ⬜
4  ⬜  ⬜  ⬜  ⚫  ⚫  ⬜  ⬜
5  ⬜  ⬜  ❌  ❌  ❌  ⚫  ⬜
6  ⬜  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜
2  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜
3  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜
4  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫
5  ⬜  ⚫  ⬜  ⬜  ⚫  ⚫  ⬜
6  ⬜  ⬜  ⚫  ❌  ❌  ❌  ⚫
7  ⬜  ⬜  ⬜  ⬜  ⚫  ⚫  ⬜

 21%|██        | 211/1000 [00:05<00:18, 41.58it/s]

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
2  ⬜  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜
3  ⬜  ⬜  ⚫  ⬜  ⬜  ❌  ⚫
4  ⬜  ⬜  ⬜  ⚫  ⬜  ❌  ⬜
5  ⬜  ⬜  ⬜  ⬜  ⚫  ❌  ⬜
6  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
2  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
3  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜  ⬜
4  ⬜  ⬜  ⬜  ❌  ⚫  ⬜  ⬜
5  ⬜  ⬜  ⬜  ❌  ⬜  ⬜  ⬜
6  ⬜  ⬜  ⬜  ❌  ⬜  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜
2  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜
3  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫  ⚫
4  ⚫  ⬜  ⬜  ⚫  ❌  ❌  ❌
5  ⬜  ⚫  ⬜  ⬜  ⚫  ⚫  ⚫
6  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
2  ⬜  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜
3  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜
4  ⬜  ⬜  ❌  ⚫  ⬜  ⬜  ⬜
5  ⬜  ⚫  ❌  ⬜  ⚫  ⬜  ⬜
6  ⬜  ⬜  ❌  ⚫  ⬜  ⬜  ⬜
7  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⬜  ⬜  ❌  ⬜
2  ⬜  ⬜  ⬜  ⬜  ⚫  ❌  ⬜
3  ⬜  ⬜  ⚫  ⬜  ⬜  ❌  ⚫
4  ⬜  ⬜  ⬜  ⚫  ⬜  ⚫  ⬜
5  ⬜  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜
6  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

 22%|██▏       | 216/1000 [00:05<00:18, 42.01it/s]

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜
2  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜
3  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜
4  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫
5  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜
6  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜
7  ⬜  ⬜  ❌  ❌  ❌  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⚫  ❌  ❌  ❌  ⬜
2  ⬜  ⬜  ⬜  ⚫  ⚫  ⬜  ⬜
3  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜
4  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜
5  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜
6  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜
2  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜
3  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜
4  ⚫  ⬜  ⬜  ⚫  ⬜  ❌  ⚫
5  ⬜  ⚫  ⬜  ⬜  ⚫  ❌  ⬜
6  ⬜  ⬜  ⚫  ⬜  ⬜  ❌  ⚫
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⚫  ⬜

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
2  ⬜  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜
3  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜
4  ⬜  ⬜  ❌  ⚫  ⬜  ⬜  ⬜
5  ⬜  ⚫  ❌  ⬜  ⚫  ⬜  ⬜
6  ⬜  ⬜  ❌  ⚫  ⬜  ⬜  ⬜
7  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⚫  ❌  ⚫  ⚫  ⬜  ⬜  ⬜
2  ⚫  ❌  ⬜  ⬜  ⚫  ⬜  ⬜
3  ⬜  ❌  ⚫  ⬜  ⬜  ⚫  ⬜
4  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜
5  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜
6  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

 22%|██▏       | 221/1000 [00:05<00:20, 38.72it/s]

   A  B  C  D  E  F  G
1  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫
2  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜
3  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜
4  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫
5  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜
6  ⚫  ⚫  ⚫  ⬜  ⬜  ⚫  ⬜
7  ❌  ❌  ❌  ⚫  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫
2  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜
3  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜
4  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫
5  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜
6  ⚫  ⚫  ⚫  ⬜  ⬜  ⚫  ⬜
7  ❌  ❌  ❌  ⚫  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
2  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
3  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜  ⬜
4  ⬜  ⬜  ⬜  ❌  ⚫  ⬜  ⬜
5  ⬜  ⬜  ⬜  ❌  ⬜  ⬜  ⬜
6  ⬜  ⬜  ⬜  ❌  ⬜  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
2  ⬜  ⬜  ⬜  ⬜  ⚫  ⚫  ⬜
3  ⬜  ⬜  ⚫  ⬜  ❌  ❌  ❌
4  ⬜  ⬜  ⬜  ⚫  ⬜  ⚫  ⚫
5  ⬜  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜
6  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

 22%|██▎       | 225/1000 [00:05<00:20, 37.09it/s]

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
2  ⬜  ⬜  ⬜  ❌  ⬜  ⬜  ⬜
3  ⬜  ⬜  ⚫  ❌  ⬜  ⬜  ⬜
4  ⬜  ⬜  ⬜  ❌  ⚫  ⬜  ⬜
5  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜
6  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
2  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
3  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜  ⬜
4  ⬜  ⬜  ⬜  ⚫  ⚫  ⬜  ⬜
5  ⬜  ⬜  ❌  ❌  ❌  ⚫  ⬜
6  ⬜  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜
2  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜
3  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜
4  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫
5  ⬜  ⚫  ⬜  ⬜  ⚫  ⚫  ⬜
6  ⬜  ⬜  ⚫  ⬜  ❌  ❌  ❌
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⚫  ⬜

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
2  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
3  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜  ⬜
4  ⬜  ⬜  ⬜  ⚫  ⚫  ⬜  ⬜
5  ⬜  ⬜  ❌  ❌  ❌  ⚫  ⬜
6  ⬜  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

 23%|██▎       | 229/1000 [00:06<00:21, 35.94it/s]

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜
2  ❌  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜
3  ❌  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜
4  ❌  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜
5  ⚫  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜
6  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
2  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
3  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜  ⬜
4  ⬜  ⬜  ⬜  ⚫  ❌  ⬜  ⬜
5  ⬜  ⬜  ⬜  ⬜  ❌  ⚫  ⬜
6  ⬜  ⬜  ⬜  ⬜  ❌  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
2  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
3  ⬜  ⬜  ⚫  ⬜  ❌  ⬜  ⬜
4  ⬜  ⬜  ⬜  ⚫  ❌  ⬜  ⬜
5  ⬜  ⬜  ⬜  ⬜  ❌  ⚫  ⬜
6  ⬜  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
2  ⬜  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜
3  ⬜  ❌  ⚫  ⬜  ⬜  ⚫  ⬜
4  ⬜  ❌  ⬜  ⚫  ⬜  ⬜  ⬜
5  ⚫  ❌  ⚫  ⬜  ⚫  ⬜  ⬜
6  ⬜  ⚫  ⬜  ⬜  ⬜  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
2  ⬜  ⬜  ⬜  ❌  ⬜  ⬜  ⬜
3  ⬜  ⬜  ⚫  ❌  ⬜  ⬜  ⬜
4  ⬜  ⬜  ⬜  ❌  ⚫  ⬜  ⬜
5  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜
6  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

 23%|██▎       | 234/1000 [00:06<00:19, 39.28it/s]

   A  B  C  D  E  F  G
1  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫
2  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜
3  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜
4  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫
5  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜
6  ⚫  ⚫  ⚫  ⬜  ⬜  ⚫  ⬜
7  ❌  ❌  ❌  ⚫  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⬜  ⬜  ❌  ⬜
2  ⬜  ⬜  ⬜  ⬜  ⚫  ❌  ⬜
3  ⬜  ⬜  ⚫  ⬜  ⬜  ❌  ⚫
4  ⬜  ⬜  ⬜  ⚫  ⬜  ⚫  ⬜
5  ⬜  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜
6  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⚫  ⚫  ⬜  ⚫  ⬜  ⬜  ⬜
2  ❌  ❌  ❌  ⬜  ⚫  ⬜  ⬜
3  ⚫  ⚫  ⚫  ⬜  ⬜  ⚫  ⬜
4  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜
5  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜
6  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫
2  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜
3  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜
4  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫
5  ❌  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜
6  ❌  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜
7  ❌  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜

 24%|██▍       | 238/1000 [00:06<00:20, 37.56it/s]

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
2  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
3  ⬜  ⬜  ⚫  ⚫  ⬜  ⬜  ⬜
4  ⬜  ❌  ❌  ❌  ⚫  ⬜  ⬜
5  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜
6  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
2  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜  ⬜
3  ⬜  ❌  ❌  ❌  ⚫  ⬜  ⬜
4  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜  ⬜
5  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
6  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⬜  ⚫  ⬜  ⚫  ⬜  ⬜  ⬜
2  ⚫  ❌  ⬜  ⬜  ⚫  ⬜  ⬜
3  ⬜  ❌  ⚫  ⬜  ⬜  ⚫  ⬜
4  ⬜  ❌  ⬜  ⚫  ⬜  ⬜  ⬜
5  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜
6  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
2  ⬜  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜
3  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜
4  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜
5  ⬜  ⚫  ⚫  ⬜  ⚫  ⬜  ⬜
6  ❌  ❌  ❌  ⚫  ⬜  ⬜  ⬜
7  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
2  ⬜  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜
3  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜
4  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜
5  ⬜  ⚫  ⚫  ⬜  ⚫  ⬜  ⬜
6  ⬜  ❌  ❌  ❌  ⚫  ⬜  ⬜
7  ⬜  ⬜  ⚫  ⚫  ⬜  ⬜  ⬜

 24%|██▍       | 243/1000 [00:06<00:19, 38.90it/s]

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜
2  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜
3  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜
4  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫
5  ⬜  ⚫  ⬜  ⬜  ⚫  ⚫  ⬜
6  ⬜  ⬜  ⚫  ⬜  ❌  ❌  ❌
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⚫  ⬜

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜
2  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜
3  ❌  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜
4  ❌  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜
5  ❌  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜
6  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜
2  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜
3  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫  ❌
4  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜  ❌
5  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜  ❌
6  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
2  ⬜  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜
3  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜
4  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜
5  ⬜  ⚫  ⚫  ⬜  ⚫  ⬜  ⬜
6  ⬜  ❌  ❌  ❌  ⚫  ⬜  ⬜
7  ⬜  ⬜  ⚫  ⚫  ⬜  ⬜  ⬜

 25%|██▍       | 247/1000 [00:06<00:19, 38.11it/s]

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜
2  ❌  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜
3  ❌  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜
4  ❌  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜
5  ⚫  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜
6  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
2  ⬜  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜
3  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜
4  ⬜  ⚫  ⬜  ⚫  ⬜  ⬜  ⬜
5  ⚫  ❌  ⬜  ⬜  ⚫  ⬜  ⬜
6  ⬜  ❌  ⚫  ⬜  ⬜  ⬜  ⬜
7  ⬜  ❌  ⬜  ⬜  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
2  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
3  ⬜  ⬜  ⚫  ⬜  ❌  ⬜  ⬜
4  ⬜  ⬜  ⬜  ⚫  ❌  ⬜  ⬜
5  ⬜  ⬜  ⬜  ⬜  ❌  ⚫  ⬜
6  ⬜  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
2  ⬜  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜
3  ⬜  ⬜  ⚫  ⬜  ⬜  ❌  ⚫
4  ⬜  ⬜  ⬜  ⚫  ⬜  ❌  ⬜
5  ⬜  ⬜  ⬜  ⬜  ⚫  ❌  ⬜
6  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
2  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
3  ⬜  ⬜  ⚫  ⬜  ⚫  ⬜  ⬜
4  ⬜  ⬜  ⬜  ❌  ❌  ❌  ⬜
5  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜
6  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

 25%|██▌       | 252/1000 [00:06<00:18, 40.42it/s]

   A  B  C  D  E  F  G
1  ⬜  ⚫  ⚫  ⚫  ⬜  ⬜  ⬜
2  ⚫  ❌  ❌  ❌  ⚫  ⬜  ⬜
3  ⬜  ⚫  ⚫  ⬜  ⬜  ⚫  ⬜
4  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜
5  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜
6  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜
2  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜
3  ⚫  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜
4  ❌  ⚫  ⬜  ⚫  ⬜  ⬜  ⬜
5  ❌  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜
6  ❌  ⬜  ⚫  ⬜  ⬜  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫
2  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜
3  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜
4  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫
5  ❌  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜
6  ❌  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜
7  ❌  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
2  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
3  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜  ⬜
4  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜
5  ⬜  ⬜  ⬜  ⬜  ❌  ❌  ❌
6  ⬜  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫
2  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜
3  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜
4  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫
5  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜
6  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫  ⚫
7  ⚫  ⬜  ⬜  ⚫  ❌  ❌  ❌

 26%|██▌       | 257/1000 [00:06<00:19, 38.28it/s]

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⚫  ❌  ❌  ❌  ⬜
2  ⬜  ⬜  ⬜  ⚫  ⚫  ⬜  ⬜
3  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜
4  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜
5  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜
6  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
2  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
3  ⬜  ⬜  ⚫  ⬜  ❌  ⬜  ⬜
4  ⬜  ⬜  ⬜  ⚫  ❌  ⬜  ⬜
5  ⬜  ⬜  ⬜  ⬜  ❌  ⚫  ⬜
6  ⬜  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⚫  ⬜  ⬜  ⚫  ❌  ❌  ❌
2  ⬜  ⚫  ⬜  ⬜  ⚫  ⚫  ⚫
3  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜
4  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫
5  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜
6  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜
7  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜
2  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜
3  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜
4  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫
5  ⬜  ⚫  ⬜  ❌  ⚫  ⬜  ⬜
6  ⬜  ⬜  ⚫  ❌  ⬜  ⚫  ⬜
7  ⬜  ⬜  ⚫  ❌  ⚫  ⬜  ⬜

 26%|██▌       | 261/1000 [00:06<00:19, 37.92it/s]

   A  B  C  D  E  F  G
1  ⬜  ⚫  ⬜  ⚫  ⬜  ⬜  ⬜
2  ⚫  ❌  ⬜  ⬜  ⚫  ⬜  ⬜
3  ⬜  ❌  ⚫  ⬜  ⬜  ⚫  ⬜
4  ⬜  ❌  ⬜  ⚫  ⬜  ⬜  ⬜
5  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜
6  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜
2  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜
3  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜
4  ⚫  ⬜  ⬜  ⚫  ⬜  ❌  ⚫
5  ⬜  ⚫  ⬜  ⬜  ⚫  ❌  ⬜
6  ⬜  ⬜  ⚫  ⬜  ⬜  ❌  ⚫
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⚫  ⬜

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
2  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜  ⬜
3  ❌  ❌  ❌  ⚫  ⬜  ⬜  ⬜
4  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜  ⬜
5  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
6  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜
2  ⬜  ⬜  ⬜  ⚫  ❌  ⬜  ⬜
3  ⬜  ⬜  ⚫  ⬜  ❌  ⚫  ⬜
4  ⬜  ⬜  ⬜  ⚫  ❌  ⬜  ⬜
5  ⬜  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜
6  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⚫  ⬜  ⬜  ⚫  ❌  ❌  ❌
2  ⬜  ⚫  ⬜  ⬜  ⚫  ⚫  ⚫
3  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜
4  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫
5  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜
6  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜
7  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜

 27%|██▋       | 266/1000 [00:06<00:19, 37.93it/s]

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⬜  ⬜  ❌  ⬜
2  ⬜  ⬜  ⬜  ⬜  ⚫  ❌  ⬜
3  ⬜  ⬜  ⚫  ⬜  ⬜  ❌  ⚫
4  ⬜  ⬜  ⬜  ⚫  ⬜  ⚫  ⬜
5  ⬜  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜
6  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
2  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
3  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜  ⬜
4  ⬜  ⬜  ⬜  ⚫  ⚫  ⬜  ⬜
5  ⬜  ⬜  ❌  ❌  ❌  ⚫  ⬜
6  ⬜  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
2  ⬜  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜
3  ⬜  ❌  ⚫  ⬜  ⬜  ⚫  ⬜
4  ⬜  ❌  ⬜  ⚫  ⬜  ⬜  ⬜
5  ⚫  ❌  ⚫  ⬜  ⚫  ⬜  ⬜
6  ⬜  ⚫  ⬜  ⬜  ⬜  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
2  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
3  ⬜  ⬜  ⚫  ⬜  ⚫  ⬜  ⬜
4  ⬜  ⬜  ❌  ❌  ❌  ⚫  ⬜
5  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜
6  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
2  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜  ⬜
3  ⬜  ❌  ❌  ❌  ⚫  ⬜  ⬜
4  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜  ⬜
5  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
6  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

 27%|██▋       | 271/1000 [00:07<00:18, 40.32it/s]

   A  B  C  D  E  F  G
1  ⬜  ⚫  ⚫  ⚫  ⬜  ⬜  ⬜
2  ⚫  ❌  ❌  ❌  ⚫  ⬜  ⬜
3  ⬜  ⚫  ⚫  ⬜  ⬜  ⚫  ⬜
4  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜
5  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜
6  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜
2  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜
3  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜
4  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫
5  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜
6  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜
7  ⬜  ❌  ❌  ❌  ⚫  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⬜  ⚫  ⚫  ⚫  ⬜  ⬜  ⬜
2  ⚫  ❌  ❌  ❌  ⚫  ⬜  ⬜
3  ⬜  ⚫  ⚫  ⬜  ⬜  ⚫  ⬜
4  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜
5  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜
6  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⚫  ⚫  ⬜  ⚫  ⬜  ⬜  ⬜
2  ❌  ❌  ❌  ⬜  ⚫  ⬜  ⬜
3  ⚫  ⚫  ⚫  ⬜  ⬜  ⚫  ⬜
4  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜
5  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜
6  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜
2  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜
3  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫  ❌
4  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜  ❌
5  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜  ❌
6  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

 28%|██▊       | 276/1000 [00:07<00:19, 37.98it/s]

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
2  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
3  ⬜  ⬜  ⚫  ⬜  ⚫  ⬜  ⬜
4  ⬜  ⬜  ❌  ❌  ❌  ⚫  ⬜
5  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜
6  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜
2  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜
3  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜
4  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫
5  ⬜  ⚫  ⬜  ⬜  ⚫  ⚫  ⬜
6  ⬜  ⬜  ⚫  ⬜  ❌  ❌  ❌
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⚫  ⬜

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
2  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
3  ⬜  ⬜  ⚫  ⬜  ⚫  ⬜  ⬜
4  ⬜  ⬜  ❌  ❌  ❌  ⚫  ⬜
5  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜
6  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜
2  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜  ❌
3  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫  ❌
4  ⚫  ⬜  ⬜  ⚫  ⬜  ⚫  ❌
5  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜  ⚫
6  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

 28%|██▊       | 280/1000 [00:07<00:19, 37.26it/s]

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜
2  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜
3  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜
4  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫
5  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜
6  ⬜  ⬜  ⚫  ⚫  ⚫  ⚫  ⬜
7  ⬜  ⬜  ⚫  ❌  ❌  ❌  ⬜

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
2  ⬜  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜
3  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜
4  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜
5  ⬜  ⚫  ⚫  ⬜  ⚫  ⬜  ⬜
6  ❌  ❌  ❌  ⚫  ⬜  ⬜  ⬜
7  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
2  ⬜  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜
3  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜
4  ⬜  ⚫  ⬜  ⚫  ⬜  ⬜  ⬜
5  ⚫  ❌  ⬜  ⬜  ⚫  ⬜  ⬜
6  ⬜  ❌  ⚫  ⬜  ⬜  ⬜  ⬜
7  ⬜  ❌  ⬜  ⬜  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜
2  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜
3  ❌  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜
4  ❌  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜
5  ❌  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜
6  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

 28%|██▊       | 284/1000 [00:07<00:19, 36.43it/s]

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
2  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
3  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜  ⬜
4  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜
5  ⬜  ⬜  ⬜  ⬜  ❌  ❌  ❌
6  ⬜  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⚫  ❌  ❌  ❌  ⬜
2  ⬜  ⬜  ⬜  ⚫  ⚫  ⬜  ⬜
3  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜
4  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜
5  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜
6  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜
2  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜
3  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫  ⚫
4  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜  ❌
5  ⬜  ⚫  ⬜  ⬜  ⚫  ⚫  ❌
6  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜  ❌
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
2  ⬜  ⬜  ⬜  ⬜  ⚫  ⚫  ⬜
3  ⬜  ⬜  ⚫  ❌  ❌  ❌  ⚫
4  ⬜  ⬜  ⬜  ⚫  ⬜  ⚫  ⬜
5  ⬜  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜
6  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⚫  ⬜  ⬜  ⚫  ❌  ❌  ❌
2  ⬜  ⚫  ⬜  ⬜  ⚫  ⚫  ⚫
3  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜
4  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫
5  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜
6  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜
7  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜

 29%|██▉       | 289/1000 [00:07<00:19, 37.14it/s]

   A  B  C  D  E  F  G
1  ⬜  ⚫  ❌  ❌  ❌  ⬜  ⬜
2  ⬜  ⬜  ⚫  ⚫  ⚫  ⬜  ⬜
3  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜
4  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜
5  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜
6  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
2  ⬜  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜
3  ⬜  ⬜  ⚫  ⬜  ⬜  ❌  ⚫
4  ⬜  ⬜  ⬜  ⚫  ⬜  ❌  ⬜
5  ⬜  ⬜  ⬜  ⬜  ⚫  ❌  ⬜
6  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
2  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
3  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜  ⬜
4  ⬜  ⬜  ⬜  ❌  ⚫  ⬜  ⬜
5  ⬜  ⬜  ⬜  ❌  ⬜  ⬜  ⬜
6  ⬜  ⬜  ⬜  ❌  ⬜  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⚫  ❌  ❌  ❌  ⬜
2  ⬜  ⬜  ⬜  ⚫  ⚫  ⬜  ⬜
3  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜
4  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜
5  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜
6  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ❌  ❌  ❌  ⚫  ⬜  ⬜  ⬜
2  ⚫  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜
3  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜
4  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫
5  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜
6  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜
7  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜

 29%|██▉       | 294/1000 [00:07<00:18, 38.64it/s]

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
2  ⬜  ⬜  ❌  ⬜  ⬜  ⬜  ⬜
3  ⬜  ⬜  ❌  ⚫  ⬜  ⬜  ⬜
4  ⬜  ⬜  ❌  ⬜  ⬜  ⬜  ⬜
5  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜  ⬜
6  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⚫  ⚫  ⬜  ⬜
2  ⬜  ⬜  ❌  ❌  ❌  ⚫  ⬜
3  ⬜  ⬜  ⚫  ⬜  ⚫  ⬜  ⬜
4  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜
5  ⬜  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜
6  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
2  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
3  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜  ⬜
4  ⬜  ⬜  ⬜  ❌  ⚫  ⬜  ⬜
5  ⬜  ⬜  ⬜  ❌  ⬜  ⬜  ⬜
6  ⬜  ⬜  ⬜  ❌  ⬜  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
2  ⬜  ⬜  ❌  ⬜  ⬜  ⬜  ⬜
3  ⬜  ⬜  ❌  ⚫  ⬜  ⬜  ⬜
4  ⬜  ⬜  ❌  ⬜  ⬜  ⬜  ⬜
5  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜  ⬜
6  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
2  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
3  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜  ⬜
4  ⬜  ⬜  ⬜  ⚫  ⚫  ⬜  ⬜
5  ⬜  ⬜  ⬜  ❌  ❌  ❌  ⚫
6  ⬜  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⬜  ⬜  ❌  ⬜  ⬜  ⬜  ⬜
2  ⬜  ⬜  ❌  ⬜  ⬜  ⬜  ⬜
3  ⬜  ⬜  ❌  ⚫  ⬜  ⬜  ⬜
4  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜  ⬜
5  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
6  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

 30%|███       | 300/1000 [00:07<00:16, 43.02it/s]

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
2  ⬜  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜
3  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜
4  ⬜  ⚫  ⬜  ⚫  ⬜  ⬜  ⬜
5  ⚫  ❌  ❌  ❌  ⚫  ⬜  ⬜
6  ⬜  ⚫  ⚫  ⬜  ⬜  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜
2  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜
3  ❌  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜
4  ❌  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜
5  ❌  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜
6  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
2  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
3  ⬜  ⬜  ❌  ❌  ❌  ⬜  ⬜
4  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜  ⬜
5  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
6  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜
2  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜
3  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫  ❌
4  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜  ❌
5  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜  ❌
6  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜
2  ⬜  ⬜  ⬜  ⚫  ❌  ⬜  ⬜
3  ⬜  ⬜  ⚫  ⬜  ❌  ⚫  ⬜
4  ⬜  ⬜  ⬜  ⚫  ❌  ⬜  ⬜
5  ⬜  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜
6  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

 30%|███       | 305/1000 [00:07<00:16, 43.16it/s]

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
2  ⬜  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜
3  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜
4  ⬜  ⚫  ⬜  ⚫  ⬜  ⬜  ⬜
5  ⚫  ❌  ❌  ❌  ⚫  ⬜  ⬜
6  ⬜  ⚫  ⚫  ⬜  ⬜  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⚫  ❌  ⬜  ⬜
2  ⬜  ⬜  ⬜  ⬜  ❌  ⬜  ⬜
3  ⬜  ⬜  ⚫  ⬜  ❌  ⬜  ⬜
4  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜
5  ⬜  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜
6  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜
2  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜
3  ⚫  ⚫  ⚫  ⬜  ⬜  ⚫  ⬜
4  ❌  ❌  ❌  ⚫  ⬜  ⬜  ⬜
5  ⚫  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜
6  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⬜  ⚫  ⚫  ⚫  ⬜  ⬜  ⬜
2  ⚫  ❌  ❌  ❌  ⚫  ⬜  ⬜
3  ⬜  ⚫  ⚫  ⬜  ⬜  ⚫  ⬜
4  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜
5  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜
6  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜
2  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜
3  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜
4  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫
5  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜
6  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜
7  ⬜  ⬜  ❌  ❌  ❌  ⬜  ⬜

 31%|███       | 310/1000 [00:08<00:16, 40.76it/s]

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
2  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
3  ⬜  ⬜  ⚫  ⬜  ⚫  ⬜  ⬜
4  ⬜  ⬜  ⬜  ❌  ❌  ❌  ⬜
5  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜
6  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⚫  ⬜  ⬜  ⚫  ⬜  ⚫  ❌
2  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜  ❌
3  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫  ❌
4  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫
5  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜
6  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜
7  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
2  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
3  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜  ⬜
4  ⬜  ⬜  ⬜  ❌  ⚫  ⬜  ⬜
5  ⬜  ⬜  ⬜  ❌  ⬜  ⬜  ⬜
6  ⬜  ⬜  ⬜  ❌  ⬜  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⬜  ⚫  ❌  ❌  ❌  ⬜  ⬜
2  ⬜  ⬜  ⚫  ⚫  ⚫  ⬜  ⬜
3  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜
4  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜
5  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜
6  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
2  ⬜  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜
3  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜
4  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜
5  ⬜  ⚫  ❌  ⬜  ⚫  ⬜  ⬜
6  ⬜  ⬜  ❌  ⚫  ⬜  ⬜  ⬜
7  ⬜  ⬜  ❌  ⚫  ⬜  ⬜  ⬜

 32%|███▏      | 315/1000 [00:08<00:16, 41.18it/s]

   A  B  C  D  E  F  G
1  ⚫  ❌  ⚫  ⚫  ⬜  ⬜  ⬜
2  ⚫  ❌  ⬜  ⬜  ⚫  ⬜  ⬜
3  ⬜  ❌  ⚫  ⬜  ⬜  ⚫  ⬜
4  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜
5  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜
6  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜
2  ⬜  ⬜  ⬜  ❌  ❌  ❌  ⬜
3  ⬜  ⬜  ⚫  ⬜  ⚫  ⬜  ⬜
4  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜
5  ⬜  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜
6  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫
2  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜
3  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜
4  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫
5  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜
6  ⚫  ⚫  ⚫  ⬜  ⬜  ⚫  ⬜
7  ❌  ❌  ❌  ⚫  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
2  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜  ⬜
3  ❌  ❌  ❌  ⚫  ⬜  ⬜  ⬜
4  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜  ⬜
5  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
6  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
2  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
3  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜  ⬜
4  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜
5  ⬜  ⬜  ⬜  ⬜  ❌  ❌  ❌
6  ⬜  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

 32%|███▏      | 320/1000 [00:08<00:16, 40.90it/s]

   A  B  C  D  E  F  G
1  ⬜  ⚫  ⬜  ⚫  ⬜  ⬜  ⬜
2  ⚫  ❌  ⬜  ⬜  ⚫  ⬜  ⬜
3  ⬜  ❌  ⚫  ⬜  ⬜  ⚫  ⬜
4  ⬜  ❌  ⬜  ⚫  ⬜  ⬜  ⬜
5  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜
6  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
2  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
3  ⬜  ⬜  ⚫  ⬜  ⚫  ⬜  ⬜
4  ⬜  ⬜  ⬜  ❌  ❌  ❌  ⬜
5  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜
6  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫
2  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜
3  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜
4  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫
5  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜  ❌
6  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫  ❌
7  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜  ❌

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
2  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
3  ⬜  ⬜  ⚫  ⬜  ⚫  ⬜  ⬜
4  ⬜  ⬜  ⬜  ❌  ❌  ❌  ⬜
5  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜
6  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⬜  ⚫  ⬜  ⚫  ⬜  ⬜  ⬜
2  ⚫  ❌  ⬜  ⬜  ⚫  ⬜  ⬜
3  ⬜  ❌  ⚫  ⬜  ⬜  ⚫  ⬜
4  ⬜  ❌  ⬜  ⚫  ⬜  ⬜  ⬜
5  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜
6  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

 32%|███▎      | 325/1000 [00:08<00:16, 40.07it/s]

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
2  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
3  ⬜  ⬜  ⚫  ⚫  ⬜  ⬜  ⬜
4  ⬜  ❌  ❌  ❌  ⚫  ⬜  ⬜
5  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜
6  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
2  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
3  ⬜  ⬜  ❌  ❌  ❌  ⬜  ⬜
4  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜  ⬜
5  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
6  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
2  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
3  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜  ⬜
4  ⬜  ⬜  ⬜  ⚫  ❌  ⬜  ⬜
5  ⬜  ⬜  ⬜  ⬜  ❌  ⚫  ⬜
6  ⬜  ⬜  ⬜  ⬜  ❌  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜
2  ⬜  ⬜  ⬜  ⚫  ❌  ⬜  ⬜
3  ⬜  ⬜  ⚫  ⬜  ❌  ⚫  ⬜
4  ⬜  ⬜  ⬜  ⚫  ❌  ⬜  ⬜
5  ⬜  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜
6  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
2  ⬜  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜
3  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜
4  ⬜  ⚫  ⬜  ⚫  ⬜  ⬜  ⬜
5  ⚫  ❌  ⬜  ⬜  ⚫  ⬜  ⬜
6  ⬜  ❌  ⚫  ⬜  ⬜  ⬜  ⬜
7  ⬜  ❌  ⬜  ⬜  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜
2  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜
3  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫  ⚫
4  ⚫  ⬜  ⬜  ⚫  ❌  ❌  ❌
5  ⬜  ⚫  ⬜  ⬜  ⚫  ⚫  ⚫
6  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

 33%|███▎      | 331/1000 [00:08<00:15, 42.31it/s]

   A  B  C  D  E  F  G
1  ❌  ⚫  ⬜  ⚫  ⬜  ⬜  ⬜
2  ❌  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜
3  ❌  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜
4  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫
5  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜
6  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜
7  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
2  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
3  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜  ⬜
4  ⬜  ⬜  ⬜  ⚫  ⚫  ⬜  ⬜
5  ⬜  ⬜  ⬜  ❌  ❌  ❌  ⚫
6  ⬜  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
2  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
3  ⬜  ⬜  ❌  ⚫  ⬜  ⬜  ⬜
4  ⬜  ⬜  ❌  ⬜  ⬜  ⬜  ⬜
5  ⬜  ⬜  ❌  ⬜  ⬜  ⬜  ⬜
6  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
2  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜  ⬜
3  ❌  ❌  ❌  ⚫  ⬜  ⬜  ⬜
4  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜  ⬜
5  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
6  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜
2  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜
3  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜
4  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫
5  ⬜  ⚫  ⬜  ⬜  ⚫  ⚫  ⬜
6  ⬜  ⬜  ⚫  ⬜  ❌  ❌  ❌
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⚫  ⬜

 34%|███▎      | 336/1000 [00:08<00:15, 42.33it/s]

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
2  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
3  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜  ⬜
4  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜
5  ⬜  ⬜  ⬜  ⬜  ❌  ❌  ❌
6  ⬜  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⬜  ⚫  ❌  ❌  ❌  ⬜  ⬜
2  ⬜  ⬜  ⚫  ⚫  ⚫  ⬜  ⬜
3  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜
4  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜
5  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜
6  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜
2  ❌  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜
3  ❌  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜
4  ❌  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜
5  ⚫  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜
6  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
2  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
3  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜  ⬜
4  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜
5  ⬜  ⬜  ⬜  ⬜  ❌  ❌  ❌
6  ⬜  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜
2  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜
3  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫  ⚫
4  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜  ❌
5  ⬜  ⚫  ⬜  ⬜  ⚫  ⚫  ❌
6  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜  ❌
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

 34%|███▍      | 341/1000 [00:08<00:15, 42.91it/s]

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
2  ⬜  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜
3  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜
4  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜
5  ⬜  ⚫  ⚫  ⬜  ⚫  ⬜  ⬜
6  ⬜  ❌  ❌  ❌  ⚫  ⬜  ⬜
7  ⬜  ⬜  ⚫  ⚫  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜
2  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜
3  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜
4  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫
5  ⬜  ⚫  ⬜  ❌  ⚫  ⬜  ⬜
6  ⬜  ⬜  ⚫  ❌  ⬜  ⚫  ⬜
7  ⬜  ⬜  ⚫  ❌  ⚫  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
2  ⬜  ⬜  ⬜  ⬜  ⚫  ❌  ⬜
3  ⬜  ⬜  ⚫  ⬜  ⬜  ❌  ⚫
4  ⬜  ⬜  ⬜  ⚫  ⬜  ❌  ⚫
5  ⬜  ⬜  ⬜  ⬜  ⚫  ⚫  ⬜
6  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫
2  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜
3  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜
4  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫
5  ❌  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜
6  ❌  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜
7  ❌  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⬜  ❌  ❌  ❌  ⬜  ⬜  ⬜
2  ⬜  ⬜  ⚫  ⚫  ⚫  ⬜  ⬜
3  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜
4  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜
5  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜
6  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

 35%|███▍      | 346/1000 [00:08<00:15, 40.95it/s]

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
2  ⬜  ⬜  ❌  ⬜  ⬜  ⬜  ⬜
3  ⬜  ⬜  ❌  ⚫  ⬜  ⬜  ⬜
4  ⬜  ⬜  ❌  ⬜  ⬜  ⬜  ⬜
5  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜  ⬜
6  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⚫  ❌  ⚫  ⚫  ⬜  ⬜  ⬜
2  ⚫  ❌  ⬜  ⬜  ⚫  ⬜  ⬜
3  ⬜  ❌  ⚫  ⬜  ⬜  ⚫  ⬜
4  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜
5  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜
6  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⚫  ⚫  ⬜  ⚫  ⬜  ⬜  ⬜
2  ❌  ❌  ❌  ⬜  ⚫  ⬜  ⬜
3  ⚫  ⚫  ⚫  ⬜  ⬜  ⚫  ⬜
4  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜
5  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜
6  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
2  ⬜  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜
3  ⬜  ❌  ⚫  ⬜  ⬜  ⚫  ⬜
4  ⬜  ❌  ⬜  ⚫  ⬜  ⬜  ⬜
5  ⚫  ❌  ⚫  ⬜  ⚫  ⬜  ⬜
6  ⬜  ⚫  ⬜  ⬜  ⬜  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
2  ⬜  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜
3  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜
4  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜
5  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜
6  ⬜  ⬜  ❌  ❌  ❌  ⬜  ⬜
7  ⬜  ⬜  ⚫  ⚫  ⬜  ⬜  ⬜

 35%|███▌      | 351/1000 [00:09<00:15, 41.56it/s]

   A  B  C  D  E  F  G
1  ⬜  ⚫  ⚫  ⚫  ⬜  ⬜  ⬜
2  ⚫  ❌  ❌  ❌  ⚫  ⬜  ⬜
3  ⬜  ⚫  ⚫  ⬜  ⬜  ⚫  ⬜
4  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜
5  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜
6  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⚫  ❌  ⬜  ⬜
2  ⬜  ⬜  ⬜  ⬜  ❌  ⬜  ⬜
3  ⬜  ⬜  ⚫  ⬜  ❌  ⬜  ⬜
4  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜
5  ⬜  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜
6  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
2  ⬜  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜
3  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜
4  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜
5  ❌  ❌  ❌  ⬜  ⚫  ⬜  ⬜
6  ⬜  ⚫  ⬜  ⬜  ⬜  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜
2  ⬜  ⬜  ⬜  ⚫  ❌  ❌  ❌
3  ⬜  ⬜  ⚫  ⬜  ⚫  ⬜  ⬜
4  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜
5  ⬜  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜
6  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜
2  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜
3  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜
4  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫
5  ⬜  ⚫  ⬜  ⬜  ⚫  ❌  ⬜
6  ⬜  ⬜  ⚫  ⬜  ⬜  ❌  ⚫
7  ⬜  ⬜  ⬜  ⬜  ⚫  ❌  ⬜

 36%|███▌      | 356/1000 [00:09<00:15, 41.78it/s]

   A  B  C  D  E  F  G
1  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫
2  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜
3  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜
4  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫
5  ❌  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜
6  ❌  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜
7  ❌  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⚫  ❌  ⚫  ⚫  ⬜  ⬜  ⬜
2  ⚫  ❌  ⬜  ⬜  ⚫  ⬜  ⬜
3  ⬜  ❌  ⚫  ⬜  ⬜  ⚫  ⬜
4  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜
5  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜
6  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫
2  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜
3  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜
4  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫
5  ❌  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜
6  ❌  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜
7  ❌  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
2  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
3  ⬜  ⬜  ⚫  ⚫  ⬜  ⬜  ⬜
4  ⬜  ❌  ❌  ❌  ⚫  ⬜  ⬜
5  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜
6  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜
2  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜
3  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜
4  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫
5  ⬜  ⚫  ⬜  ⬜  ⚫  ❌  ⬜
6  ⬜  ⬜  ⚫  ⬜  ⬜  ❌  ⚫
7  ⬜  ⬜  ⬜  ⬜  ⚫  ❌  ⬜

 36%|███▌      | 361/1000 [00:09<00:15, 40.09it/s]

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
2  ⬜  ⬜  ⬜  ❌  ⬜  ⬜  ⬜
3  ⬜  ⬜  ⚫  ❌  ⬜  ⬜  ⬜
4  ⬜  ⬜  ⬜  ❌  ⚫  ⬜  ⬜
5  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜
6  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜
2  ⬜  ⬜  ⬜  ⚫  ❌  ⬜  ⬜
3  ⬜  ⬜  ⚫  ⬜  ❌  ⚫  ⬜
4  ⬜  ⬜  ⬜  ⚫  ❌  ⬜  ⬜
5  ⬜  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜
6  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜
2  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜
3  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫  ⚫
4  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜  ❌
5  ⬜  ⚫  ⬜  ⬜  ⚫  ⚫  ❌
6  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜  ❌
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
2  ⬜  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜
3  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜
4  ⬜  ⚫  ⬜  ⚫  ⬜  ⬜  ⬜
5  ⚫  ❌  ❌  ❌  ⚫  ⬜  ⬜
6  ⬜  ⚫  ⚫  ⬜  ⬜  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜
2  ❌  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜
3  ❌  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜
4  ❌  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜
5  ⚫  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜
6  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

 37%|███▋      | 366/1000 [00:09<00:15, 40.69it/s]

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
2  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
3  ⬜  ⬜  ⚫  ⚫  ⬜  ⬜  ⬜
4  ⬜  ❌  ❌  ❌  ⚫  ⬜  ⬜
5  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜
6  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
2  ⬜  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜
3  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜
4  ⬜  ⬜  ❌  ⚫  ⬜  ⬜  ⬜
5  ⬜  ⚫  ❌  ⬜  ⚫  ⬜  ⬜
6  ⬜  ⬜  ❌  ⚫  ⬜  ⬜  ⬜
7  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⬜  ❌  ❌  ❌  ⬜  ⬜  ⬜
2  ⬜  ⬜  ⚫  ⚫  ⚫  ⬜  ⬜
3  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜
4  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜
5  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜
6  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜
2  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜
3  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜
4  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫
5  ⬜  ⚫  ⬜  ⬜  ⚫  ⚫  ⬜
6  ⬜  ⬜  ⚫  ❌  ❌  ❌  ⚫
7  ⬜  ⬜  ⬜  ⬜  ⚫  ⚫  ⬜

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
2  ⬜  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜
3  ⬜  ❌  ⚫  ⬜  ⬜  ⚫  ⬜
4  ⬜  ❌  ⬜  ⚫  ⬜  ⬜  ⬜
5  ⚫  ❌  ⚫  ⬜  ⚫  ⬜  ⬜
6  ⬜  ⚫  ⬜  ⬜  ⬜  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

 37%|███▋      | 371/1000 [00:09<00:15, 40.59it/s]

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
2  ⬜  ⬜  ❌  ⬜  ⬜  ⬜  ⬜
3  ⬜  ⬜  ❌  ⚫  ⬜  ⬜  ⬜
4  ⬜  ⬜  ❌  ⬜  ⬜  ⬜  ⬜
5  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜  ⬜
6  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
2  ⬜  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜
3  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜
4  ⬜  ❌  ⬜  ⚫  ⬜  ⬜  ⬜
5  ⚫  ❌  ⬜  ⬜  ⚫  ⬜  ⬜
6  ⬜  ❌  ⬜  ⬜  ⬜  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
2  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
3  ⬜  ⬜  ⚫  ⚫  ⬜  ⬜  ⬜
4  ⬜  ❌  ❌  ❌  ⚫  ⬜  ⬜
5  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜
6  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⚫  ⬜  ⬜  ⚫  ❌  ❌  ❌
2  ⬜  ⚫  ⬜  ⬜  ⚫  ⚫  ⚫
3  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜
4  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫
5  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜
6  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜
7  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⚫  ❌  ⚫  ⚫  ⬜  ⬜  ⬜
2  ⚫  ❌  ⬜  ⬜  ⚫  ⬜  ⬜
3  ⬜  ❌  ⚫  ⬜  ⬜  ⚫  ⬜
4  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜
5  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜
6  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

 38%|███▊      | 376/1000 [00:09<00:15, 40.03it/s]

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
2  ⬜  ⬜  ⬜  ❌  ⬜  ⬜  ⬜
3  ⬜  ⬜  ⚫  ❌  ⬜  ⬜  ⬜
4  ⬜  ⬜  ⬜  ❌  ⚫  ⬜  ⬜
5  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜
6  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜
2  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜
3  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫  ⚫
4  ⚫  ⬜  ⬜  ⚫  ❌  ❌  ❌
5  ⬜  ⚫  ⬜  ⬜  ⚫  ⚫  ⚫
6  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
2  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
3  ⬜  ⬜  ⚫  ⬜  ⚫  ⬜  ⬜
4  ⬜  ⬜  ⬜  ❌  ❌  ❌  ⬜
5  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜
6  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
2  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜  ⬜
3  ❌  ❌  ❌  ⚫  ⬜  ⬜  ⬜
4  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜  ⬜
5  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
6  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜
2  ❌  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜
3  ❌  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜
4  ❌  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜
5  ⚫  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜
6  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

 38%|███▊      | 381/1000 [00:09<00:14, 41.70it/s]

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⚫  ❌  ⚫  ⬜  ⬜
2  ⬜  ⬜  ⚫  ❌  ⚫  ⬜  ⬜
3  ⬜  ⬜  ⚫  ❌  ⬜  ⚫  ⬜
4  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜
5  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜
6  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜
2  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜
3  ⚫  ⚫  ⚫  ⬜  ⬜  ⚫  ⬜
4  ❌  ❌  ❌  ⚫  ⬜  ⬜  ⬜
5  ⚫  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜
6  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
2  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
3  ⬜  ⬜  ⚫  ⬜  ❌  ⬜  ⬜
4  ⬜  ⬜  ⬜  ⚫  ❌  ⬜  ⬜
5  ⬜  ⬜  ⬜  ⬜  ❌  ⚫  ⬜
6  ⬜  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
2  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
3  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜  ⬜
4  ⬜  ⬜  ⬜  ❌  ⚫  ⬜  ⬜
5  ⬜  ⬜  ⬜  ❌  ⬜  ⬜  ⬜
6  ⬜  ⬜  ⬜  ❌  ⬜  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
2  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
3  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜  ⬜
4  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜
5  ⬜  ⬜  ⬜  ⬜  ❌  ❌  ❌
6  ⬜  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

 39%|███▊      | 386/1000 [00:09<00:14, 43.53it/s]

   A  B  C  D  E  F  G
1  ⚫  ⬜  ⬜  ⚫  ❌  ❌  ❌
2  ⬜  ⚫  ⬜  ⬜  ⚫  ⚫  ⚫
3  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜
4  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫
5  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜
6  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜
7  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⬜  ⚫  ⚫  ⚫  ⬜  ⬜  ⬜
2  ⚫  ❌  ❌  ❌  ⚫  ⬜  ⬜
3  ⬜  ⚫  ⚫  ⬜  ⬜  ⚫  ⬜
4  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜
5  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜
6  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜
2  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜
3  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜
4  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫
5  ⬜  ⚫  ⬜  ⬜  ⚫  ❌  ⬜
6  ⬜  ⬜  ⚫  ⬜  ⬜  ❌  ⚫
7  ⬜  ⬜  ⬜  ⬜  ⚫  ❌  ⬜

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
2  ⬜  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜
3  ⬜  ⬜  ⚫  ⬜  ⬜  ❌  ⚫
4  ⬜  ⬜  ⬜  ⚫  ⬜  ❌  ⬜
5  ⬜  ⬜  ⬜  ⬜  ⚫  ❌  ⬜
6  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜
2  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜
3  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜
4  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫
5  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜
6  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜
7  ⬜  ❌  ❌  ❌  ⚫  ⬜  ⬜

 39%|███▉      | 391/1000 [00:10<00:14, 41.37it/s]

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⬜  ⬜  ❌  ⬜
2  ⬜  ⬜  ⬜  ⬜  ⚫  ❌  ⬜
3  ⬜  ⬜  ⚫  ⬜  ⬜  ❌  ⚫
4  ⬜  ⬜  ⬜  ⚫  ⬜  ⚫  ⬜
5  ⬜  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜
6  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜
2  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜
3  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜
4  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫
5  ⬜  ⚫  ⬜  ❌  ⚫  ⬜  ⬜
6  ⬜  ⬜  ⚫  ❌  ⬜  ⚫  ⬜
7  ⬜  ⬜  ⚫  ❌  ⚫  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫
2  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜
3  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜
4  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫
5  ❌  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜
6  ❌  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜
7  ❌  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜
2  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜
3  ⚫  ⚫  ⚫  ⬜  ⬜  ⚫  ⬜
4  ❌  ❌  ❌  ⚫  ⬜  ⬜  ⬜
5  ⚫  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜
6  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
2  ⬜  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜
3  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜
4  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜
5  ⬜  ⚫  ⚫  ⬜  ⚫  ⬜  ⬜
6  ❌  ❌  ❌  ⚫  ⬜  ⬜  ⬜
7  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜  ⬜

 40%|███▉      | 396/1000 [00:10<00:15, 38.92it/s]

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜
2  ⬜  ⬜  ⬜  ⚫  ❌  ⬜  ⬜
3  ⬜  ⬜  ⚫  ⬜  ❌  ⚫  ⬜
4  ⬜  ⬜  ⬜  ⚫  ❌  ⬜  ⬜
5  ⬜  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜
6  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
2  ⬜  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜
3  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜
4  ⬜  ⚫  ⬜  ⚫  ⬜  ⬜  ⬜
5  ⚫  ❌  ❌  ❌  ⚫  ⬜  ⬜
6  ⬜  ⚫  ⚫  ⬜  ⬜  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⬜  ⬜  ❌  ⬜  ⬜  ⬜  ⬜
2  ⬜  ⬜  ❌  ⬜  ⬜  ⬜  ⬜
3  ⬜  ⬜  ❌  ⚫  ⬜  ⬜  ⬜
4  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜  ⬜
5  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
6  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⚫  ❌  ⬜  ⬜
2  ⬜  ⬜  ⬜  ⬜  ❌  ⬜  ⬜
3  ⬜  ⬜  ⚫  ⬜  ❌  ⬜  ⬜
4  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜
5  ⬜  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜
6  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
2  ⬜  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜
3  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜
4  ⬜  ⚫  ⬜  ⚫  ⬜  ⬜  ⬜
5  ⚫  ❌  ❌  ❌  ⚫  ⬜  ⬜
6  ⬜  ⚫  ⚫  ⬜  ⬜  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

 40%|████      | 401/1000 [00:10<00:14, 40.16it/s]

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
2  ⬜  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜
3  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜
4  ⬜  ⚫  ⬜  ⚫  ⬜  ⬜  ⬜
5  ⚫  ❌  ⬜  ⬜  ⚫  ⬜  ⬜
6  ⬜  ❌  ⚫  ⬜  ⬜  ⬜  ⬜
7  ⬜  ❌  ⬜  ⬜  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜
2  ⬜  ⬜  ⬜  ⚫  ❌  ⬜  ⬜
3  ⬜  ⬜  ⚫  ⬜  ❌  ⚫  ⬜
4  ⬜  ⬜  ⬜  ⚫  ❌  ⬜  ⬜
5  ⬜  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜
6  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜
2  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜
3  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜
4  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫
5  ⬜  ⚫  ⬜  ⬜  ⚫  ⚫  ⬜
6  ⬜  ⬜  ⚫  ❌  ❌  ❌  ⚫
7  ⬜  ⬜  ⬜  ⬜  ⚫  ⚫  ⬜

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
2  ⬜  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜
3  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜
4  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜
5  ❌  ❌  ❌  ⬜  ⚫  ⬜  ⬜
6  ⬜  ⚫  ⬜  ⬜  ⬜  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
2  ⬜  ⬜  ⬜  ⬜  ⚫  ⚫  ⬜
3  ⬜  ⬜  ⚫  ⬜  ❌  ❌  ❌
4  ⬜  ⬜  ⬜  ⚫  ⬜  ⚫  ⚫
5  ⬜  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜
6  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

 41%|████      | 406/1000 [00:10<00:14, 39.74it/s]

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜
2  ⬜  ⬜  ⬜  ⚫  ❌  ⬜  ⬜
3  ⬜  ⬜  ⚫  ⬜  ❌  ⚫  ⬜
4  ⬜  ⬜  ⬜  ⚫  ❌  ⬜  ⬜
5  ⬜  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜
6  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜
2  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜
3  ⚫  ⚫  ⚫  ⬜  ⬜  ⚫  ⬜
4  ❌  ❌  ❌  ⚫  ⬜  ⬜  ⬜
5  ⚫  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜
6  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⬜  ⬜  ❌  ⬜
2  ⬜  ⬜  ⬜  ⬜  ⚫  ❌  ⬜
3  ⬜  ⬜  ⚫  ⬜  ⬜  ❌  ⚫
4  ⬜  ⬜  ⬜  ⚫  ⬜  ⚫  ⬜
5  ⬜  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜
6  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
2  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
3  ⬜  ⬜  ⚫  ⬜  ❌  ⬜  ⬜
4  ⬜  ⬜  ⬜  ⚫  ❌  ⬜  ⬜
5  ⬜  ⬜  ⬜  ⬜  ❌  ⚫  ⬜
6  ⬜  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
2  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
3  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜  ⬜
4  ⬜  ⬜  ⬜  ❌  ⚫  ⬜  ⬜
5  ⬜  ⬜  ⬜  ❌  ⬜  ⬜  ⬜
6  ⬜  ⬜  ⬜  ❌  ⬜  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

 41%|████      | 411/1000 [00:10<00:14, 41.54it/s]

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜
2  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜
3  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜
4  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫
5  ⬜  ⚫  ⬜  ⬜  ⚫  ❌  ⬜
6  ⬜  ⬜  ⚫  ⬜  ⬜  ❌  ⚫
7  ⬜  ⬜  ⬜  ⬜  ⚫  ❌  ⬜

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
2  ⬜  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜
3  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜
4  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜
5  ⬜  ⚫  ❌  ⬜  ⚫  ⬜  ⬜
6  ⬜  ⬜  ❌  ⚫  ⬜  ⬜  ⬜
7  ⬜  ⬜  ❌  ⚫  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
2  ⬜  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜
3  ⬜  ❌  ⚫  ⬜  ⬜  ⚫  ⬜
4  ⬜  ❌  ⬜  ⚫  ⬜  ⬜  ⬜
5  ⚫  ❌  ⚫  ⬜  ⚫  ⬜  ⬜
6  ⬜  ⚫  ⬜  ⬜  ⬜  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⚫  ❌  ⚫  ⚫  ⬜  ⬜  ⬜
2  ⚫  ❌  ⬜  ⬜  ⚫  ⬜  ⬜
3  ⬜  ❌  ⚫  ⬜  ⬜  ⚫  ⬜
4  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜
5  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜
6  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜
2  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜
3  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫  ⚫
4  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜  ❌
5  ⬜  ⚫  ⬜  ⬜  ⚫  ⚫  ❌
6  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜  ❌
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

 42%|████▏     | 416/1000 [00:10<00:14, 38.98it/s]

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
2  ⬜  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜
3  ⬜  ⬜  ⚫  ⬜  ⬜  ❌  ⚫
4  ⬜  ⬜  ⬜  ⚫  ⬜  ❌  ⬜
5  ⬜  ⬜  ⬜  ⬜  ⚫  ❌  ⬜
6  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⚫  ❌  ⚫  ⬜  ⬜
2  ⬜  ⬜  ⚫  ❌  ⚫  ⬜  ⬜
3  ⬜  ⬜  ⚫  ❌  ⬜  ⚫  ⬜
4  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜
5  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜
6  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
2  ⬜  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜
3  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜
4  ⬜  ⚫  ⬜  ⚫  ⬜  ⬜  ⬜
5  ⚫  ❌  ⬜  ⬜  ⚫  ⬜  ⬜
6  ⬜  ❌  ⚫  ⬜  ⬜  ⬜  ⬜
7  ⬜  ❌  ⬜  ⬜  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜
2  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜
3  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜
4  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫
5  ⬜  ⚫  ⬜  ⬜  ⚫  ❌  ⬜
6  ⬜  ⬜  ⚫  ⬜  ⬜  ❌  ⚫
7  ⬜  ⬜  ⬜  ⬜  ⚫  ❌  ⬜

 42%|████▏     | 420/1000 [00:10<00:14, 38.95it/s]

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
2  ⬜  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜
3  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜
4  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜
5  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜
6  ⬜  ⬜  ❌  ❌  ❌  ⬜  ⬜
7  ⬜  ⬜  ⚫  ⚫  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫
2  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜
3  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜
4  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫
5  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜
6  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫  ⚫
7  ⚫  ⬜  ⬜  ⚫  ❌  ❌  ❌

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
2  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜  ⬜
3  ⬜  ❌  ❌  ❌  ⚫  ⬜  ⬜
4  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜  ⬜
5  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
6  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
2  ⬜  ⬜  ⬜  ⬜  ⚫  ❌  ⬜
3  ⬜  ⬜  ⚫  ⬜  ⬜  ❌  ⚫
4  ⬜  ⬜  ⬜  ⚫  ⬜  ❌  ⚫
5  ⬜  ⬜  ⬜  ⬜  ⚫  ⚫  ⬜
6  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫
2  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜
3  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜
4  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫
5  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜
6  ⚫  ⚫  ⚫  ⬜  ⬜  ⚫  ⬜
7  ❌  ❌  ❌  ⚫  ⬜  ⬜  ⬜

 42%|████▎     | 425/1000 [00:10<00:14, 38.53it/s]

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜
2  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜
3  ⚫  ⚫  ⚫  ⬜  ⬜  ⚫  ⬜
4  ❌  ❌  ❌  ⚫  ⬜  ⬜  ⬜
5  ⚫  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜
6  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
2  ⬜  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜
3  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜
4  ⬜  ❌  ⬜  ⚫  ⬜  ⬜  ⬜
5  ⚫  ❌  ⬜  ⬜  ⚫  ⬜  ⬜
6  ⬜  ❌  ⬜  ⬜  ⬜  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⚫  ❌  ⬜  ⬜
2  ⬜  ⬜  ⬜  ⬜  ❌  ⬜  ⬜
3  ⬜  ⬜  ⚫  ⬜  ❌  ⬜  ⬜
4  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜
5  ⬜  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜
6  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
2  ⬜  ⬜  ⬜  ⬜  ⚫  ⚫  ⬜
3  ⬜  ⬜  ⚫  ❌  ❌  ❌  ⚫
4  ⬜  ⬜  ⬜  ⚫  ⬜  ⚫  ⬜
5  ⬜  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜
6  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ❌  ❌  ❌  ⚫  ⬜  ⬜  ⬜
2  ⚫  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜
3  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜
4  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫
5  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜
6  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜
7  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜

 43%|████▎     | 430/1000 [00:11<00:14, 39.43it/s]

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
2  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
3  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜  ⬜
4  ⬜  ⬜  ⬜  ⚫  ⚫  ⬜  ⬜
5  ⬜  ⬜  ⬜  ❌  ❌  ❌  ⚫
6  ⬜  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⬜  ⚫  ⚫  ⚫  ⬜  ⬜  ⬜
2  ⚫  ❌  ❌  ❌  ⚫  ⬜  ⬜
3  ⬜  ⚫  ⚫  ⬜  ⬜  ⚫  ⬜
4  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜
5  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜
6  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
2  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
3  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜  ⬜
4  ⬜  ⬜  ⬜  ⚫  ⚫  ⬜  ⬜
5  ⬜  ⬜  ❌  ❌  ❌  ⚫  ⬜
6  ⬜  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜
2  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜
3  ⚫  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜
4  ❌  ⚫  ⬜  ⚫  ⬜  ⬜  ⬜
5  ❌  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜
6  ❌  ⬜  ⚫  ⬜  ⬜  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜
2  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜
3  ⚫  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜
4  ❌  ⚫  ⬜  ⚫  ⬜  ⬜  ⬜
5  ❌  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜
6  ❌  ⬜  ⚫  ⬜  ⬜  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

 44%|████▎     | 435/1000 [00:11<00:14, 39.57it/s]

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
2  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
3  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜  ⬜
4  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜
5  ⬜  ⬜  ⬜  ⬜  ❌  ⚫  ⬜
6  ⬜  ⬜  ⬜  ⬜  ❌  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ❌  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜
2  ⬜  ⬜  ⬜  ⚫  ❌  ❌  ❌
3  ⬜  ⬜  ⚫  ⬜  ⚫  ⬜  ⬜
4  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜
5  ⬜  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜
6  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
2  ⬜  ⬜  ⬜  ⬜  ⚫  ⚫  ⬜
3  ⬜  ⬜  ⚫  ❌  ❌  ❌  ⚫
4  ⬜  ⬜  ⬜  ⚫  ⬜  ⚫  ⬜
5  ⬜  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜
6  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
2  ⬜  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜
3  ⬜  ❌  ⚫  ⬜  ⬜  ⚫  ⬜
4  ⬜  ❌  ⬜  ⚫  ⬜  ⬜  ⬜
5  ⚫  ❌  ⚫  ⬜  ⚫  ⬜  ⬜
6  ⬜  ⚫  ⬜  ⬜  ⬜  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
2  ⬜  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜
3  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜
4  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜
5  ❌  ❌  ❌  ⬜  ⚫  ⬜  ⬜
6  ⬜  ⚫  ⬜  ⬜  ⬜  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

 44%|████▍     | 440/1000 [00:11<00:13, 41.64it/s]

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜
2  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜
3  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜
4  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫
5  ⬜  ⚫  ⬜  ❌  ⚫  ⬜  ⬜
6  ⬜  ⬜  ⚫  ❌  ⬜  ⚫  ⬜
7  ⬜  ⬜  ⚫  ❌  ⚫  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
2  ⬜  ⬜  ⬜  ⬜  ⚫  ⚫  ⬜
3  ⬜  ⬜  ⚫  ⬜  ❌  ❌  ❌
4  ⬜  ⬜  ⬜  ⚫  ⬜  ⚫  ⚫
5  ⬜  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜
6  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜
2  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜
3  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜
4  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫
5  ⬜  ⚫  ⬜  ⬜  ⚫  ⚫  ⬜
6  ⬜  ⬜  ⚫  ⬜  ❌  ❌  ❌
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⚫  ⬜

   A  B  C  D  E  F  G
1  ⚫  ⬜  ⬜  ⚫  ⬜  ⚫  ❌
2  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜  ❌
3  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫  ❌
4  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫
5  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜
6  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜
7  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
2  ⬜  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜
3  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜
4  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜
5  ⬜  ⚫  ⚫  ⬜  ⚫  ⬜  ⬜
6  ⬜  ❌  ❌  ❌  ⚫  ⬜  ⬜
7  ⬜  ⬜  ⚫  ⚫  ⬜  ⬜  ⬜

 44%|████▍     | 445/1000 [00:11<00:14, 39.52it/s]

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
2  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
3  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜  ⬜
4  ⬜  ⬜  ⬜  ❌  ⚫  ⬜  ⬜
5  ⬜  ⬜  ⬜  ❌  ⬜  ⬜  ⬜
6  ⬜  ⬜  ⬜  ❌  ⬜  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
2  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
3  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜  ⬜
4  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜
5  ⬜  ⬜  ⬜  ⬜  ❌  ⚫  ⬜
6  ⬜  ⬜  ⬜  ⬜  ❌  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ❌  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
2  ⬜  ⬜  ⬜  ⬜  ⚫  ⚫  ⬜
3  ⬜  ⬜  ⚫  ❌  ❌  ❌  ⚫
4  ⬜  ⬜  ⬜  ⚫  ⬜  ⚫  ⬜
5  ⬜  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜
6  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⚫  ⚫  ⬜  ⬜
2  ⬜  ⬜  ❌  ❌  ❌  ⚫  ⬜
3  ⬜  ⬜  ⚫  ⬜  ⚫  ⬜  ⬜
4  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜
5  ⬜  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜
6  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⬜  ⚫  ⚫  ⚫  ⬜  ⬜  ⬜
2  ⚫  ❌  ❌  ❌  ⚫  ⬜  ⬜
3  ⬜  ⚫  ⚫  ⬜  ⬜  ⚫  ⬜
4  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜
5  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜
6  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

 45%|████▌     | 450/1000 [00:11<00:13, 41.24it/s]

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
2  ⬜  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜
3  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜
4  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜
5  ⬜  ⚫  ⚫  ⬜  ⚫  ⬜  ⬜
6  ⬜  ❌  ❌  ❌  ⚫  ⬜  ⬜
7  ⬜  ⬜  ⚫  ⚫  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⚫  ⚫  ⬜  ⚫  ⬜  ⬜  ⬜
2  ❌  ❌  ❌  ⬜  ⚫  ⬜  ⬜
3  ⚫  ⚫  ⚫  ⬜  ⬜  ⚫  ⬜
4  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜
5  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜
6  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜
2  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜
3  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫  ❌
4  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜  ❌
5  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜  ❌
6  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
2  ⬜  ⬜  ⬜  ⬜  ⚫  ⚫  ⬜
3  ⬜  ⬜  ⚫  ❌  ❌  ❌  ⚫
4  ⬜  ⬜  ⬜  ⚫  ⬜  ⚫  ⬜
5  ⬜  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜
6  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜
2  ❌  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜
3  ❌  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜
4  ❌  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜
5  ⚫  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜
6  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

 46%|████▌     | 455/1000 [00:11<00:13, 40.24it/s]

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
2  ⬜  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜
3  ⬜  ❌  ⚫  ⬜  ⬜  ⚫  ⬜
4  ⬜  ❌  ⬜  ⚫  ⬜  ⬜  ⬜
5  ⚫  ❌  ⚫  ⬜  ⚫  ⬜  ⬜
6  ⬜  ⚫  ⬜  ⬜  ⬜  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
2  ⬜  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜
3  ⬜  ⬜  ⚫  ⬜  ⬜  ❌  ⚫
4  ⬜  ⬜  ⬜  ⚫  ⬜  ❌  ⬜
5  ⬜  ⬜  ⬜  ⬜  ⚫  ❌  ⬜
6  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜
2  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜
3  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜
4  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫
5  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜
6  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜
7  ⬜  ⬜  ❌  ❌  ❌  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
2  ⬜  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜
3  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜
4  ⬜  ❌  ⬜  ⚫  ⬜  ⬜  ⬜
5  ⚫  ❌  ⬜  ⬜  ⚫  ⬜  ⬜
6  ⬜  ❌  ⬜  ⬜  ⬜  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
2  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜  ⬜
3  ⬜  ❌  ❌  ❌  ⚫  ⬜  ⬜
4  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜  ⬜
5  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
6  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

 46%|████▌     | 460/1000 [00:11<00:13, 41.32it/s]

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
2  ⬜  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜
3  ⬜  ❌  ⚫  ⬜  ⬜  ⚫  ⬜
4  ⬜  ❌  ⬜  ⚫  ⬜  ⬜  ⬜
5  ⚫  ❌  ⚫  ⬜  ⚫  ⬜  ⬜
6  ⬜  ⚫  ⬜  ⬜  ⬜  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
2  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
3  ⬜  ⬜  ⚫  ⚫  ⬜  ⬜  ⬜
4  ⬜  ❌  ❌  ❌  ⚫  ⬜  ⬜
5  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜
6  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⬜  ⬜  ❌  ⬜
2  ⬜  ⬜  ⬜  ⬜  ⚫  ❌  ⬜
3  ⬜  ⬜  ⚫  ⬜  ⬜  ❌  ⚫
4  ⬜  ⬜  ⬜  ⚫  ⬜  ⚫  ⬜
5  ⬜  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜
6  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜
2  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜
3  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜
4  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫
5  ⬜  ⚫  ⬜  ⬜  ⚫  ⚫  ⬜
6  ⬜  ⬜  ⚫  ⬜  ❌  ❌  ❌
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⚫  ⬜

   A  B  C  D  E  F  G
1  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫
2  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜
3  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜
4  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫
5  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜
6  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫  ⚫
7  ⚫  ⬜  ⬜  ⚫  ❌  ❌  ❌

 46%|████▋     | 465/1000 [00:11<00:13, 40.55it/s]

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜
2  ⬜  ⬜  ⬜  ❌  ❌  ❌  ⬜
3  ⬜  ⬜  ⚫  ⬜  ⚫  ⬜  ⬜
4  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜
5  ⬜  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜
6  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
2  ⬜  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜
3  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜
4  ⬜  ❌  ⬜  ⚫  ⬜  ⬜  ⬜
5  ⚫  ❌  ⬜  ⬜  ⚫  ⬜  ⬜
6  ⬜  ❌  ⬜  ⬜  ⬜  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
2  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
3  ⬜  ⬜  ⚫  ⬜  ⚫  ⬜  ⬜
4  ⬜  ⬜  ⬜  ❌  ❌  ❌  ⬜
5  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜
6  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
2  ⬜  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜
3  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜
4  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜
5  ⬜  ⚫  ❌  ⬜  ⚫  ⬜  ⬜
6  ⬜  ⬜  ❌  ⚫  ⬜  ⬜  ⬜
7  ⬜  ⬜  ❌  ⚫  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
2  ⬜  ⬜  ⬜  ⬜  ⚫  ❌  ⬜
3  ⬜  ⬜  ⚫  ⬜  ⬜  ❌  ⚫
4  ⬜  ⬜  ⬜  ⚫  ⬜  ❌  ⚫
5  ⬜  ⬜  ⬜  ⬜  ⚫  ⚫  ⬜
6  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

 47%|████▋     | 470/1000 [00:12<00:12, 41.16it/s]

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜
2  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜
3  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫  ❌
4  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜  ❌
5  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜  ❌
6  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜
2  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜
3  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜
4  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫
5  ⬜  ⚫  ⬜  ⬜  ⚫  ⚫  ⬜
6  ⬜  ⬜  ⚫  ⬜  ❌  ❌  ❌
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⚫  ⬜

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜
2  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜
3  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜
4  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫
5  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜
6  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜
7  ⬜  ⬜  ❌  ❌  ❌  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜
2  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜
3  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜
4  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫
5  ⬜  ⚫  ⬜  ❌  ⚫  ⬜  ⬜
6  ⬜  ⬜  ⚫  ❌  ⬜  ⚫  ⬜
7  ⬜  ⬜  ⚫  ❌  ⚫  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
2  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
3  ⬜  ⬜  ❌  ⚫  ⬜  ⬜  ⬜
4  ⬜  ⬜  ❌  ⬜  ⬜  ⬜  ⬜
5  ⬜  ⬜  ❌  ⬜  ⬜  ⬜  ⬜
6  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

 48%|████▊     | 475/1000 [00:12<00:13, 39.91it/s]

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜
2  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜
3  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫  ⚫
4  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜  ❌
5  ⬜  ⚫  ⬜  ⬜  ⚫  ⚫  ❌
6  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜  ❌
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
2  ⬜  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜
3  ⬜  ⬜  ⚫  ⬜  ⬜  ❌  ⚫
4  ⬜  ⬜  ⬜  ⚫  ⬜  ❌  ⬜
5  ⬜  ⬜  ⬜  ⬜  ⚫  ❌  ⬜
6  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜
2  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜
3  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜
4  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫
5  ⬜  ⚫  ⬜  ⬜  ⚫  ❌  ⬜
6  ⬜  ⬜  ⚫  ⬜  ⬜  ❌  ⚫
7  ⬜  ⬜  ⬜  ⬜  ⚫  ❌  ⬜

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜
2  ⬜  ⬜  ⬜  ⚫  ❌  ❌  ❌
3  ⬜  ⬜  ⚫  ⬜  ⚫  ⬜  ⬜
4  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜
5  ⬜  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜
6  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
2  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
3  ⬜  ⬜  ⚫  ⬜  ❌  ⬜  ⬜
4  ⬜  ⬜  ⬜  ⚫  ❌  ⬜  ⬜
5  ⬜  ⬜  ⬜  ⬜  ❌  ⚫  ⬜
6  ⬜  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

 48%|████▊     | 480/1000 [00:12<00:12, 40.81it/s]

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜
2  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜  ❌
3  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫  ❌
4  ⚫  ⬜  ⬜  ⚫  ⬜  ⚫  ❌
5  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜  ⚫
6  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
2  ⬜  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜
3  ⬜  ❌  ⚫  ⬜  ⬜  ⚫  ⬜
4  ⬜  ❌  ⬜  ⚫  ⬜  ⬜  ⬜
5  ⚫  ❌  ⚫  ⬜  ⚫  ⬜  ⬜
6  ⬜  ⚫  ⬜  ⬜  ⬜  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⚫  ❌  ⬜  ⬜
2  ⬜  ⬜  ⬜  ⬜  ❌  ⬜  ⬜
3  ⬜  ⬜  ⚫  ⬜  ❌  ⬜  ⬜
4  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜
5  ⬜  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜
6  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜
2  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜
3  ⚫  ⚫  ⚫  ⬜  ⬜  ⚫  ⬜
4  ❌  ❌  ❌  ⚫  ⬜  ⬜  ⬜
5  ⚫  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜
6  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
2  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
3  ⬜  ⬜  ⚫  ⬜  ⚫  ⬜  ⬜
4  ⬜  ⬜  ❌  ❌  ❌  ⚫  ⬜
5  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜
6  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

 48%|████▊     | 485/1000 [00:12<00:12, 41.51it/s]

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜
2  ⬜  ⬜  ⬜  ⚫  ❌  ❌  ❌
3  ⬜  ⬜  ⚫  ⬜  ⚫  ⬜  ⬜
4  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜
5  ⬜  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜
6  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
2  ⬜  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜
3  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜
4  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜
5  ⬜  ⚫  ⚫  ⬜  ⚫  ⬜  ⬜
6  ⬜  ❌  ❌  ❌  ⚫  ⬜  ⬜
7  ⬜  ⬜  ⚫  ⚫  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⚫  ⬜  ⬜  ⚫  ⬜  ⚫  ❌
2  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜  ❌
3  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫  ❌
4  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫
5  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜
6  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜
7  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⬜  ⚫  ⚫  ⚫  ⬜  ⬜  ⬜
2  ⚫  ❌  ❌  ❌  ⚫  ⬜  ⬜
3  ⬜  ⚫  ⚫  ⬜  ⬜  ⚫  ⬜
4  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜
5  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜
6  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
2  ⬜  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜
3  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜
4  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜
5  ⬜  ⚫  ⚫  ⬜  ⚫  ⬜  ⬜
6  ⬜  ❌  ❌  ❌  ⚫  ⬜  ⬜
7  ⬜  ⬜  ⚫  ⚫  ⬜  ⬜  ⬜

 49%|████▉     | 490/1000 [00:12<00:12, 40.47it/s]

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
2  ⬜  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜
3  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜
4  ⬜  ❌  ⬜  ⚫  ⬜  ⬜  ⬜
5  ⚫  ❌  ⬜  ⬜  ⚫  ⬜  ⬜
6  ⬜  ❌  ⬜  ⬜  ⬜  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
2  ⬜  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜
3  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜
4  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜
5  ⬜  ⚫  ⚫  ⬜  ⚫  ⬜  ⬜
6  ❌  ❌  ❌  ⚫  ⬜  ⬜  ⬜
7  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫
2  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜
3  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜
4  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫
5  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜
6  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫  ⚫
7  ⚫  ⬜  ⬜  ⚫  ❌  ❌  ❌

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜
2  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜  ❌
3  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫  ❌
4  ⚫  ⬜  ⬜  ⚫  ⬜  ⚫  ❌
5  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜  ⚫
6  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
2  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
3  ⬜  ⬜  ⚫  ❌  ⬜  ⬜  ⬜
4  ⬜  ⬜  ⬜  ❌  ⚫  ⬜  ⬜
5  ⬜  ⬜  ⚫  ❌  ⬜  ⬜  ⬜
6  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

 50%|████▉     | 495/1000 [00:12<00:12, 39.49it/s]

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
2  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
3  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜  ⬜
4  ⬜  ⬜  ⬜  ⚫  ⚫  ⬜  ⬜
5  ⬜  ⬜  ❌  ❌  ❌  ⚫  ⬜
6  ⬜  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ❌  ❌  ❌  ⚫  ⬜  ⬜  ⬜
2  ⚫  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜
3  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜
4  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫
5  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜
6  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜
7  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
2  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
3  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜  ⬜
4  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜
5  ⬜  ⬜  ⬜  ⬜  ❌  ❌  ❌
6  ⬜  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
2  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
3  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜  ⬜
4  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜
5  ⬜  ⬜  ⬜  ⬜  ❌  ⚫  ⬜
6  ⬜  ⬜  ⬜  ⬜  ❌  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ❌  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⬜  ⚫  ⚫  ⚫  ⬜  ⬜  ⬜
2  ⚫  ❌  ❌  ❌  ⚫  ⬜  ⬜
3  ⬜  ⚫  ⚫  ⬜  ⬜  ⚫  ⬜
4  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜
5  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜
6  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

 50%|█████     | 500/1000 [00:12<00:12, 40.75it/s]

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜
2  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜
3  ⚫  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜
4  ❌  ⚫  ⬜  ⚫  ⬜  ⬜  ⬜
5  ❌  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜
6  ❌  ⬜  ⚫  ⬜  ⬜  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
2  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
3  ⬜  ⬜  ❌  ❌  ❌  ⬜  ⬜
4  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜  ⬜
5  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
6  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
2  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜  ⬜
3  ❌  ❌  ❌  ⚫  ⬜  ⬜  ⬜
4  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜  ⬜
5  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
6  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
2  ⬜  ⬜  ⬜  ⬜  ⚫  ⚫  ⬜
3  ⬜  ⬜  ⚫  ❌  ❌  ❌  ⚫
4  ⬜  ⬜  ⬜  ⚫  ⬜  ⚫  ⬜
5  ⬜  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜
6  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
2  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
3  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜  ⬜
4  ⬜  ⬜  ⬜  ❌  ⚫  ⬜  ⬜
5  ⬜  ⬜  ⬜  ❌  ⬜  ⬜  ⬜
6  ⬜  ⬜  ⬜  ❌  ⬜  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

 50%|█████     | 505/1000 [00:12<00:11, 43.07it/s]

   A  B  C  D  E  F  G
1  ⚫  ⬜  ⬜  ⚫  ❌  ❌  ❌
2  ⬜  ⚫  ⬜  ⬜  ⚫  ⚫  ⚫
3  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜
4  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫
5  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜
6  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜
7  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⚫  ❌  ⬜  ⬜
2  ⬜  ⬜  ⬜  ⬜  ❌  ⬜  ⬜
3  ⬜  ⬜  ⚫  ⬜  ❌  ⬜  ⬜
4  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜
5  ⬜  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜
6  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫
2  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜
3  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜
4  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫
5  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜
6  ⚫  ⚫  ⚫  ⬜  ⬜  ⚫  ⬜
7  ❌  ❌  ❌  ⚫  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⚫  ⚫  ⬜  ⚫  ⬜  ⬜  ⬜
2  ❌  ❌  ❌  ⬜  ⚫  ⬜  ⬜
3  ⚫  ⚫  ⚫  ⬜  ⬜  ⚫  ⬜
4  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜
5  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜
6  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜
2  ⬜  ⬜  ⬜  ⚫  ❌  ⬜  ⬜
3  ⬜  ⬜  ⚫  ⬜  ❌  ⚫  ⬜
4  ⬜  ⬜  ⬜  ⚫  ❌  ⬜  ⬜
5  ⬜  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜
6  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

 51%|█████     | 510/1000 [00:13<00:12, 40.36it/s]

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
2  ⬜  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜
3  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜
4  ⬜  ⚫  ⬜  ⚫  ⬜  ⬜  ⬜
5  ⚫  ❌  ⬜  ⬜  ⚫  ⬜  ⬜
6  ⬜  ❌  ⚫  ⬜  ⬜  ⬜  ⬜
7  ⬜  ❌  ⬜  ⬜  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜
2  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜
3  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜
4  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫
5  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜
6  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜
7  ⬜  ❌  ❌  ❌  ⚫  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⬜  ⬜  ❌  ⬜  ⬜  ⬜  ⬜
2  ⬜  ⬜  ❌  ⬜  ⬜  ⬜  ⬜
3  ⬜  ⬜  ❌  ⚫  ⬜  ⬜  ⬜
4  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜  ⬜
5  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
6  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜
2  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜
3  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜
4  ⚫  ⬜  ⬜  ⚫  ⬜  ❌  ⚫
5  ⬜  ⚫  ⬜  ⬜  ⚫  ❌  ⬜
6  ⬜  ⬜  ⚫  ⬜  ⬜  ❌  ⚫
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⚫  ⬜

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
2  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
3  ⬜  ⬜  ⚫  ⬜  ⚫  ⬜  ⬜
4  ⬜  ⬜  ⬜  ❌  ❌  ❌  ⬜
5  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜
6  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

 52%|█████▏    | 515/1000 [00:13<00:11, 41.39it/s]

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
2  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
3  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜  ⬜
4  ⬜  ⬜  ⬜  ❌  ⚫  ⬜  ⬜
5  ⬜  ⬜  ⬜  ❌  ⬜  ⬜  ⬜
6  ⬜  ⬜  ⬜  ❌  ⬜  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
2  ⬜  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜
3  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜
4  ⬜  ⚫  ⬜  ⚫  ⬜  ⬜  ⬜
5  ⚫  ❌  ❌  ❌  ⚫  ⬜  ⬜
6  ⬜  ⚫  ⚫  ⬜  ⬜  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜
2  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜
3  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜
4  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫
5  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜
6  ⬜  ⬜  ⚫  ⚫  ⚫  ⚫  ⬜
7  ⬜  ⬜  ⚫  ❌  ❌  ❌  ⬜

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
2  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
3  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜  ⬜
4  ⬜  ⬜  ⬜  ❌  ⚫  ⬜  ⬜
5  ⬜  ⬜  ⬜  ❌  ⬜  ⬜  ⬜
6  ⬜  ⬜  ⬜  ❌  ⬜  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
2  ⬜  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜
3  ⬜  ⬜  ⚫  ⬜  ⬜  ❌  ⚫
4  ⬜  ⬜  ⬜  ⚫  ⬜  ❌  ⬜
5  ⬜  ⬜  ⬜  ⬜  ⚫  ❌  ⬜
6  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

 52%|█████▏    | 520/1000 [00:13<00:11, 42.67it/s]

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
2  ⬜  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜
3  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜
4  ⬜  ❌  ⬜  ⚫  ⬜  ⬜  ⬜
5  ⚫  ❌  ⬜  ⬜  ⚫  ⬜  ⬜
6  ⬜  ❌  ⬜  ⬜  ⬜  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜
2  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜
3  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫  ❌
4  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜  ❌
5  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜  ❌
6  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
2  ⬜  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜
3  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜
4  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜
5  ⬜  ⚫  ⚫  ⬜  ⚫  ⬜  ⬜
6  ❌  ❌  ❌  ⚫  ⬜  ⬜  ⬜
7  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
2  ⬜  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜
3  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜
4  ⬜  ❌  ⬜  ⚫  ⬜  ⬜  ⬜
5  ⚫  ❌  ⬜  ⬜  ⚫  ⬜  ⬜
6  ⬜  ❌  ⬜  ⬜  ⬜  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜
2  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜  ❌
3  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫  ❌
4  ⚫  ⬜  ⬜  ⚫  ⬜  ⚫  ❌
5  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜  ⚫
6  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

 52%|█████▎    | 525/1000 [00:13<00:11, 42.65it/s]

   A  B  C  D  E  F  G
1  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫
2  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜
3  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜
4  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫
5  ❌  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜
6  ❌  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜
7  ❌  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⚫  ⚫  ⬜  ⬜
2  ⬜  ⬜  ❌  ❌  ❌  ⚫  ⬜
3  ⬜  ⬜  ⚫  ⬜  ⚫  ⬜  ⬜
4  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜
5  ⬜  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜
6  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫
2  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜
3  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜
4  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫
5  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜
6  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫  ⚫
7  ⚫  ⬜  ⬜  ⚫  ❌  ❌  ❌

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜
2  ⬜  ⬜  ⬜  ⚫  ❌  ❌  ❌
3  ⬜  ⬜  ⚫  ⬜  ⚫  ⬜  ⬜
4  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜
5  ⬜  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜
6  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
2  ⬜  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜
3  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜
4  ⬜  ❌  ⬜  ⚫  ⬜  ⬜  ⬜
5  ⚫  ❌  ⬜  ⬜  ⚫  ⬜  ⬜
6  ⬜  ❌  ⬜  ⬜  ⬜  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

 53%|█████▎    | 530/1000 [00:13<00:11, 40.30it/s]

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
2  ⬜  ⬜  ⬜  ⬜  ⚫  ⚫  ⬜
3  ⬜  ⬜  ⚫  ❌  ❌  ❌  ⚫
4  ⬜  ⬜  ⬜  ⚫  ⬜  ⚫  ⬜
5  ⬜  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜
6  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜
2  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜
3  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜
4  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫
5  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜
6  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜
7  ⬜  ❌  ❌  ❌  ⚫  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜
2  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜
3  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜
4  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫
5  ⬜  ⚫  ⬜  ⬜  ⚫  ⚫  ⬜
6  ⬜  ⬜  ⚫  ⬜  ❌  ❌  ❌
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⚫  ⬜

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
2  ⬜  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜
3  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜
4  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜
5  ⬜  ⚫  ⚫  ⬜  ⚫  ⬜  ⬜
6  ❌  ❌  ❌  ⚫  ⬜  ⬜  ⬜
7  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
2  ⬜  ⬜  ❌  ⬜  ⬜  ⬜  ⬜
3  ⬜  ⬜  ❌  ⚫  ⬜  ⬜  ⬜
4  ⬜  ⬜  ❌  ⬜  ⬜  ⬜  ⬜
5  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜  ⬜
6  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

 54%|█████▎    | 535/1000 [00:13<00:11, 40.49it/s]

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
2  ⬜  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜
3  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜
4  ⬜  ❌  ⬜  ⚫  ⬜  ⬜  ⬜
5  ⚫  ❌  ⬜  ⬜  ⚫  ⬜  ⬜
6  ⬜  ❌  ⬜  ⬜  ⬜  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⬜  ⚫  ⚫  ⚫  ⬜  ⬜  ⬜
2  ⚫  ❌  ❌  ❌  ⚫  ⬜  ⬜
3  ⬜  ⚫  ⚫  ⬜  ⬜  ⚫  ⬜
4  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜
5  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜
6  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜
2  ❌  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜
3  ❌  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜
4  ❌  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜
5  ⚫  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜
6  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
2  ⬜  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜
3  ⬜  ⬜  ⚫  ⬜  ⬜  ❌  ⚫
4  ⬜  ⬜  ⬜  ⚫  ⬜  ❌  ⬜
5  ⬜  ⬜  ⬜  ⬜  ⚫  ❌  ⬜
6  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜
2  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜  ❌
3  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫  ❌
4  ⚫  ⬜  ⬜  ⚫  ⬜  ⚫  ❌
5  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜  ⚫
6  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

 54%|█████▍    | 540/1000 [00:13<00:11, 39.77it/s]

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜
2  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜  ❌
3  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫  ❌
4  ⚫  ⬜  ⬜  ⚫  ⬜  ⚫  ❌
5  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜  ⚫
6  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
2  ⬜  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜
3  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜
4  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜
5  ❌  ❌  ❌  ⬜  ⚫  ⬜  ⬜
6  ⬜  ⚫  ⬜  ⬜  ⬜  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
2  ⬜  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜
3  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜
4  ⬜  ❌  ⬜  ⚫  ⬜  ⬜  ⬜
5  ⚫  ❌  ⬜  ⬜  ⚫  ⬜  ⬜
6  ⬜  ❌  ⬜  ⬜  ⬜  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫
2  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜
3  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜
4  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫
5  ❌  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜
6  ❌  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜
7  ❌  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜
2  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜
3  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜
4  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫
5  ⬜  ⚫  ⬜  ⬜  ⚫  ⚫  ⬜
6  ⬜  ⬜  ⚫  ❌  ❌  ❌  ⚫
7  ⬜  ⬜  ⬜  ⬜  ⚫  ⚫  ⬜

 55%|█████▍    | 545/1000 [00:13<00:11, 39.24it/s]

   A  B  C  D  E  F  G
1  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫
2  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜
3  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜
4  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫
5  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜
6  ⚫  ⚫  ⚫  ⬜  ⬜  ⚫  ⬜
7  ❌  ❌  ❌  ⚫  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜
2  ⬜  ⬜  ⬜  ❌  ❌  ❌  ⬜
3  ⬜  ⬜  ⚫  ⬜  ⚫  ⬜  ⬜
4  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜
5  ⬜  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜
6  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜
2  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜
3  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜
4  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫
5  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜
6  ⬜  ⬜  ⚫  ⚫  ⚫  ⚫  ⬜
7  ⬜  ⬜  ⚫  ❌  ❌  ❌  ⬜

   A  B  C  D  E  F  G
1  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫
2  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜
3  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜
4  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫
5  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜
6  ⚫  ⚫  ⚫  ⬜  ⬜  ⚫  ⬜
7  ❌  ❌  ❌  ⚫  ⬜  ⬜  ⬜

 55%|█████▍    | 549/1000 [00:13<00:11, 37.82it/s]

   A  B  C  D  E  F  G
1  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫
2  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜
3  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜
4  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫
5  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜  ❌
6  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫  ❌
7  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜  ❌

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
2  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
3  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜  ⬜
4  ⬜  ⬜  ⬜  ⚫  ⚫  ⬜  ⬜
5  ⬜  ⬜  ❌  ❌  ❌  ⚫  ⬜
6  ⬜  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⚫  ⬜  ⬜  ⚫  ❌  ❌  ❌
2  ⬜  ⚫  ⬜  ⬜  ⚫  ⚫  ⚫
3  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜
4  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫
5  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜
6  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜
7  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⚫  ❌  ⚫  ⚫  ⬜  ⬜  ⬜
2  ⚫  ❌  ⬜  ⬜  ⚫  ⬜  ⬜
3  ⬜  ❌  ⚫  ⬜  ⬜  ⚫  ⬜
4  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜
5  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜
6  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

 55%|█████▌    | 553/1000 [00:14<00:12, 36.97it/s]

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
2  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
3  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜  ⬜
4  ⬜  ⬜  ⬜  ⚫  ❌  ⬜  ⬜
5  ⬜  ⬜  ⬜  ⬜  ❌  ⚫  ⬜
6  ⬜  ⬜  ⬜  ⬜  ❌  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜
2  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜
3  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜
4  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫
5  ⬜  ⚫  ⬜  ⬜  ⚫  ⚫  ⬜
6  ⬜  ⬜  ⚫  ❌  ❌  ❌  ⚫
7  ⬜  ⬜  ⬜  ⬜  ⚫  ⚫  ⬜

   A  B  C  D  E  F  G
1  ⬜  ⚫  ⬜  ⚫  ⬜  ⬜  ⬜
2  ⚫  ❌  ⬜  ⬜  ⚫  ⬜  ⬜
3  ⬜  ❌  ⚫  ⬜  ⬜  ⚫  ⬜
4  ⬜  ❌  ⬜  ⚫  ⬜  ⬜  ⬜
5  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜
6  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
2  ⬜  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜
3  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜
4  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜
5  ⬜  ⚫  ❌  ⬜  ⚫  ⬜  ⬜
6  ⬜  ⬜  ❌  ⚫  ⬜  ⬜  ⬜
7  ⬜  ⬜  ❌  ⚫  ⬜  ⬜  ⬜

 56%|█████▌    | 557/1000 [00:14<00:11, 37.60it/s]

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⚫  ❌  ❌  ❌  ⬜
2  ⬜  ⬜  ⬜  ⚫  ⚫  ⬜  ⬜
3  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜
4  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜
5  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜
6  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
2  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
3  ⬜  ⬜  ⚫  ⬜  ⚫  ⬜  ⬜
4  ⬜  ⬜  ❌  ❌  ❌  ⚫  ⬜
5  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜
6  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⬜  ⚫  ⬜  ⚫  ⬜  ⬜  ⬜
2  ⚫  ❌  ⬜  ⬜  ⚫  ⬜  ⬜
3  ⬜  ❌  ⚫  ⬜  ⬜  ⚫  ⬜
4  ⬜  ❌  ⬜  ⚫  ⬜  ⬜  ⬜
5  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜
6  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
2  ⬜  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜
3  ⬜  ⬜  ⚫  ⬜  ⬜  ❌  ⚫
4  ⬜  ⬜  ⬜  ⚫  ⬜  ❌  ⬜
5  ⬜  ⬜  ⬜  ⬜  ⚫  ❌  ⬜
6  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜
2  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜
3  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜
4  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫
5  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜
6  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜
7  ⬜  ❌  ❌  ❌  ⚫  ⬜  ⬜

 56%|█████▌    | 562/1000 [00:14<00:11, 38.63it/s]

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
2  ⬜  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜
3  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜
4  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜
5  ⬜  ⚫  ⚫  ⬜  ⚫  ⬜  ⬜
6  ❌  ❌  ❌  ⚫  ⬜  ⬜  ⬜
7  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
2  ⬜  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜
3  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜
4  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜
5  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜
6  ⬜  ⬜  ❌  ❌  ❌  ⬜  ⬜
7  ⬜  ⬜  ⚫  ⚫  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜
2  ⬜  ⬜  ⬜  ⚫  ❌  ⬜  ⬜
3  ⬜  ⬜  ⚫  ⬜  ❌  ⚫  ⬜
4  ⬜  ⬜  ⬜  ⚫  ❌  ⬜  ⬜
5  ⬜  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜
6  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜
2  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜
3  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫  ❌
4  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜  ❌
5  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜  ❌
6  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
2  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
3  ⬜  ⬜  ⚫  ❌  ⬜  ⬜  ⬜
4  ⬜  ⬜  ⬜  ❌  ⚫  ⬜  ⬜
5  ⬜  ⬜  ⚫  ❌  ⬜  ⬜  ⬜
6  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

 57%|█████▋    | 567/1000 [00:14<00:10, 40.10it/s]

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜
2  ❌  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜
3  ❌  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜
4  ❌  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜
5  ⚫  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜
6  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜
2  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜
3  ❌  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜
4  ❌  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜
5  ❌  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜
6  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
2  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
3  ⬜  ⬜  ❌  ❌  ❌  ⬜  ⬜
4  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜  ⬜
5  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
6  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜
2  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜
3  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜
4  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫
5  ⬜  ⚫  ⬜  ⬜  ⚫  ❌  ⬜
6  ⬜  ⬜  ⚫  ⬜  ⬜  ❌  ⚫
7  ⬜  ⬜  ⬜  ⬜  ⚫  ❌  ⬜

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜
2  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜
3  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜
4  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫
5  ⬜  ⚫  ⬜  ⬜  ⚫  ❌  ⬜
6  ⬜  ⬜  ⚫  ⬜  ⬜  ❌  ⚫
7  ⬜  ⬜  ⬜  ⬜  ⚫  ❌  ⬜

 57%|█████▋    | 572/1000 [00:14<00:10, 40.23it/s]

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
2  ⬜  ⬜  ⬜  ⬜  ⚫  ❌  ⬜
3  ⬜  ⬜  ⚫  ⬜  ⬜  ❌  ⚫
4  ⬜  ⬜  ⬜  ⚫  ⬜  ❌  ⚫
5  ⬜  ⬜  ⬜  ⬜  ⚫  ⚫  ⬜
6  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜
2  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜
3  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜
4  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫
5  ⬜  ⚫  ⬜  ⬜  ⚫  ⚫  ⬜
6  ⬜  ⬜  ⚫  ⬜  ❌  ❌  ❌
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⚫  ⬜

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⚫  ❌  ❌  ❌  ⬜
2  ⬜  ⬜  ⬜  ⚫  ⚫  ⬜  ⬜
3  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜
4  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜
5  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜
6  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜
2  ⬜  ⬜  ⬜  ⚫  ❌  ❌  ❌
3  ⬜  ⬜  ⚫  ⬜  ⚫  ⬜  ⬜
4  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜
5  ⬜  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜
6  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
2  ⬜  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜
3  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜
4  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜
5  ⬜  ⚫  ⚫  ⬜  ⚫  ⬜  ⬜
6  ⬜  ❌  ❌  ❌  ⚫  ⬜  ⬜
7  ⬜  ⬜  ⚫  ⚫  ⬜  ⬜  ⬜

 58%|█████▊    | 577/1000 [00:14<00:10, 40.24it/s]

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
2  ⬜  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜
3  ⬜  ⬜  ⚫  ⬜  ⬜  ❌  ⚫
4  ⬜  ⬜  ⬜  ⚫  ⬜  ❌  ⬜
5  ⬜  ⬜  ⬜  ⬜  ⚫  ❌  ⬜
6  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⚫  ⬜  ⬜  ⚫  ⬜  ⚫  ❌
2  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜  ❌
3  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫  ❌
4  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫
5  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜
6  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜
7  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜
2  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜
3  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫  ⚫
4  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜  ❌
5  ⬜  ⚫  ⬜  ⬜  ⚫  ⚫  ❌
6  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜  ❌
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫
2  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜
3  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜
4  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫
5  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜
6  ⚫  ⚫  ⚫  ⬜  ⬜  ⚫  ⬜
7  ❌  ❌  ❌  ⚫  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫
2  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜
3  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜
4  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫
5  ❌  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜
6  ❌  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜
7  ❌  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜

 58%|█████▊    | 582/1000 [00:14<00:10, 38.16it/s]

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
2  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜  ⬜
3  ⬜  ❌  ❌  ❌  ⚫  ⬜  ⬜
4  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜  ⬜
5  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
6  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ❌  ⚫  ⬜  ⚫  ⬜  ⬜  ⬜
2  ❌  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜
3  ❌  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜
4  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫
5  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜
6  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜
7  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫
2  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜
3  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜
4  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫
5  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜
6  ⚫  ⚫  ⚫  ⬜  ⬜  ⚫  ⬜
7  ❌  ❌  ❌  ⚫  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⚫  ❌  ❌  ❌  ⬜
2  ⬜  ⬜  ⬜  ⚫  ⚫  ⬜  ⬜
3  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜
4  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜
5  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜
6  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

 59%|█████▊    | 586/1000 [00:14<00:11, 37.59it/s]

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⬜  ⬜  ❌  ⬜
2  ⬜  ⬜  ⬜  ⬜  ⚫  ❌  ⬜
3  ⬜  ⬜  ⚫  ⬜  ⬜  ❌  ⚫
4  ⬜  ⬜  ⬜  ⚫  ⬜  ⚫  ⬜
5  ⬜  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜
6  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
2  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
3  ⬜  ⬜  ⚫  ⬜  ⚫  ⬜  ⬜
4  ⬜  ⬜  ❌  ❌  ❌  ⚫  ⬜
5  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜
6  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜
2  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜
3  ⚫  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜
4  ❌  ⚫  ⬜  ⚫  ⬜  ⬜  ⬜
5  ❌  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜
6  ❌  ⬜  ⚫  ⬜  ⬜  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⬜  ⚫  ⬜  ⚫  ⬜  ⬜  ⬜
2  ⚫  ❌  ⬜  ⬜  ⚫  ⬜  ⬜
3  ⬜  ❌  ⚫  ⬜  ⬜  ⚫  ⬜
4  ⬜  ❌  ⬜  ⚫  ⬜  ⬜  ⬜
5  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜
6  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
2  ⬜  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜
3  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜
4  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜
5  ❌  ❌  ❌  ⬜  ⚫  ⬜  ⬜
6  ⬜  ⚫  ⬜  ⬜  ⬜  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

 59%|█████▉    | 591/1000 [00:15<00:10, 39.51it/s]

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜
2  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜
3  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜
4  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫
5  ⬜  ⚫  ⬜  ❌  ⚫  ⬜  ⬜
6  ⬜  ⬜  ⚫  ❌  ⬜  ⚫  ⬜
7  ⬜  ⬜  ⚫  ❌  ⚫  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
2  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
3  ⬜  ⬜  ⚫  ⚫  ⬜  ⬜  ⬜
4  ⬜  ❌  ❌  ❌  ⚫  ⬜  ⬜
5  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜
6  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
2  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
3  ⬜  ⬜  ⚫  ⬜  ⚫  ⬜  ⬜
4  ⬜  ⬜  ⬜  ❌  ❌  ❌  ⬜
5  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜
6  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⬜  ⬜  ❌  ⬜
2  ⬜  ⬜  ⬜  ⬜  ⚫  ❌  ⬜
3  ⬜  ⬜  ⚫  ⬜  ⬜  ❌  ⚫
4  ⬜  ⬜  ⬜  ⚫  ⬜  ⚫  ⬜
5  ⬜  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜
6  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⬜  ⚫  ⬜  ⚫  ⬜  ⬜  ⬜
2  ⚫  ❌  ⬜  ⬜  ⚫  ⬜  ⬜
3  ⬜  ❌  ⚫  ⬜  ⬜  ⚫  ⬜
4  ⬜  ❌  ⬜  ⚫  ⬜  ⬜  ⬜
5  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜
6  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

 60%|█████▉    | 596/1000 [00:15<00:09, 40.73it/s]

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜
2  ❌  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜
3  ❌  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜
4  ❌  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜
5  ⚫  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜
6  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
2  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜  ⬜
3  ❌  ❌  ❌  ⚫  ⬜  ⬜  ⬜
4  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜  ⬜
5  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
6  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
2  ⬜  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜
3  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜
4  ⬜  ❌  ⬜  ⚫  ⬜  ⬜  ⬜
5  ⚫  ❌  ⬜  ⬜  ⚫  ⬜  ⬜
6  ⬜  ❌  ⬜  ⬜  ⬜  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
2  ⬜  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜
3  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜
4  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜
5  ⬜  ⚫  ⚫  ⬜  ⚫  ⬜  ⬜
6  ❌  ❌  ❌  ⚫  ⬜  ⬜  ⬜
7  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
2  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
3  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜  ⬜
4  ⬜  ⬜  ⬜  ❌  ⚫  ⬜  ⬜
5  ⬜  ⬜  ⬜  ❌  ⬜  ⬜  ⬜
6  ⬜  ⬜  ⬜  ❌  ⬜  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

 60%|██████    | 601/1000 [00:15<00:09, 42.43it/s]

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
2  ⬜  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜
3  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜
4  ⬜  ⚫  ⬜  ⚫  ⬜  ⬜  ⬜
5  ⚫  ❌  ❌  ❌  ⚫  ⬜  ⬜
6  ⬜  ⚫  ⚫  ⬜  ⬜  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜
2  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜
3  ⚫  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜
4  ❌  ⚫  ⬜  ⚫  ⬜  ⬜  ⬜
5  ❌  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜
6  ❌  ⬜  ⚫  ⬜  ⬜  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
2  ⬜  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜
3  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜
4  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜
5  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜
6  ⬜  ⬜  ❌  ❌  ❌  ⬜  ⬜
7  ⬜  ⬜  ⚫  ⚫  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫
2  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜
3  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜
4  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫
5  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜
6  ⚫  ⚫  ⚫  ⬜  ⬜  ⚫  ⬜
7  ❌  ❌  ❌  ⚫  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
2  ⬜  ⬜  ⬜  ⬜  ⚫  ❌  ⬜
3  ⬜  ⬜  ⚫  ⬜  ⬜  ❌  ⚫
4  ⬜  ⬜  ⬜  ⚫  ⬜  ❌  ⚫
5  ⬜  ⬜  ⬜  ⬜  ⚫  ⚫  ⬜
6  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

 61%|██████    | 606/1000 [00:15<00:09, 40.55it/s]

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⚫  ❌  ❌  ❌  ⬜
2  ⬜  ⬜  ⬜  ⚫  ⚫  ⬜  ⬜
3  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜
4  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜
5  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜
6  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
2  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
3  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜  ⬜
4  ⬜  ⬜  ⬜  ❌  ⚫  ⬜  ⬜
5  ⬜  ⬜  ⬜  ❌  ⬜  ⬜  ⬜
6  ⬜  ⬜  ⬜  ❌  ⬜  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⚫  ❌  ⚫  ⚫  ⬜  ⬜  ⬜
2  ⚫  ❌  ⬜  ⬜  ⚫  ⬜  ⬜
3  ⬜  ❌  ⚫  ⬜  ⬜  ⚫  ⬜
4  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜
5  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜
6  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
2  ⬜  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜
3  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜
4  ⬜  ⚫  ⬜  ⚫  ⬜  ⬜  ⬜
5  ⚫  ❌  ❌  ❌  ⚫  ⬜  ⬜
6  ⬜  ⚫  ⚫  ⬜  ⬜  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
2  ⬜  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜
3  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜
4  ⬜  ❌  ⬜  ⚫  ⬜  ⬜  ⬜
5  ⚫  ❌  ⬜  ⬜  ⚫  ⬜  ⬜
6  ⬜  ❌  ⬜  ⬜  ⬜  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

 61%|██████    | 611/1000 [00:15<00:09, 41.63it/s]

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
2  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜  ⬜
3  ⬜  ❌  ❌  ❌  ⚫  ⬜  ⬜
4  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜  ⬜
5  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
6  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
2  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
3  ⬜  ⬜  ⚫  ❌  ⬜  ⬜  ⬜
4  ⬜  ⬜  ⬜  ❌  ⚫  ⬜  ⬜
5  ⬜  ⬜  ⚫  ❌  ⬜  ⬜  ⬜
6  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫
2  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜
3  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜
4  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫
5  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜
6  ⚫  ⚫  ⚫  ⬜  ⬜  ⚫  ⬜
7  ❌  ❌  ❌  ⚫  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫
2  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜
3  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜
4  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫
5  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜
6  ⚫  ⚫  ⚫  ⬜  ⬜  ⚫  ⬜
7  ❌  ❌  ❌  ⚫  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⚫  ⬜  ⬜  ⚫  ❌  ❌  ❌
2  ⬜  ⚫  ⬜  ⬜  ⚫  ⚫  ⚫
3  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜
4  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫
5  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜
6  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜
7  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜

 62%|██████▏   | 616/1000 [00:15<00:09, 39.45it/s]

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜
2  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜
3  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫  ⚫
4  ⚫  ⬜  ⬜  ⚫  ❌  ❌  ❌
5  ⬜  ⚫  ⬜  ⬜  ⚫  ⚫  ⚫
6  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜
2  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜  ❌
3  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫  ❌
4  ⚫  ⬜  ⬜  ⚫  ⬜  ⚫  ❌
5  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜  ⚫
6  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
2  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
3  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜  ⬜
4  ⬜  ⬜  ⬜  ⚫  ⚫  ⬜  ⬜
5  ⬜  ⬜  ⬜  ❌  ❌  ❌  ⚫
6  ⬜  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
2  ⬜  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜
3  ⬜  ❌  ⚫  ⬜  ⬜  ⚫  ⬜
4  ⬜  ❌  ⬜  ⚫  ⬜  ⬜  ⬜
5  ⚫  ❌  ⚫  ⬜  ⚫  ⬜  ⬜
6  ⬜  ⚫  ⬜  ⬜  ⬜  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

 62%|██████▏   | 620/1000 [00:15<00:09, 38.42it/s]

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
2  ⬜  ⬜  ❌  ⬜  ⬜  ⬜  ⬜
3  ⬜  ⬜  ❌  ⚫  ⬜  ⬜  ⬜
4  ⬜  ⬜  ❌  ⬜  ⬜  ⬜  ⬜
5  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜  ⬜
6  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
2  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
3  ⬜  ⬜  ⚫  ⬜  ❌  ⬜  ⬜
4  ⬜  ⬜  ⬜  ⚫  ❌  ⬜  ⬜
5  ⬜  ⬜  ⬜  ⬜  ❌  ⚫  ⬜
6  ⬜  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫
2  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜
3  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜
4  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫
5  ❌  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜
6  ❌  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜
7  ❌  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ❌  ❌  ❌  ⚫  ⬜  ⬜  ⬜
2  ⚫  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜
3  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜
4  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫
5  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜
6  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜
7  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜

 62%|██████▏   | 624/1000 [00:15<00:09, 38.34it/s]

   A  B  C  D  E  F  G
1  ⚫  ❌  ⚫  ⚫  ⬜  ⬜  ⬜
2  ⚫  ❌  ⬜  ⬜  ⚫  ⬜  ⬜
3  ⬜  ❌  ⚫  ⬜  ⬜  ⚫  ⬜
4  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜
5  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜
6  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜
2  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜
3  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜
4  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫
5  ⬜  ⚫  ⬜  ❌  ⚫  ⬜  ⬜
6  ⬜  ⬜  ⚫  ❌  ⬜  ⚫  ⬜
7  ⬜  ⬜  ⚫  ❌  ⚫  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
2  ⬜  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜
3  ⬜  ❌  ⚫  ⬜  ⬜  ⚫  ⬜
4  ⬜  ❌  ⬜  ⚫  ⬜  ⬜  ⬜
5  ⚫  ❌  ⚫  ⬜  ⚫  ⬜  ⬜
6  ⬜  ⚫  ⬜  ⬜  ⬜  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫
2  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜
3  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜
4  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫
5  ❌  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜
6  ❌  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜
7  ❌  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜

 63%|██████▎   | 628/1000 [00:15<00:09, 37.62it/s]

   A  B  C  D  E  F  G
1  ⬜  ❌  ❌  ❌  ⬜  ⬜  ⬜
2  ⬜  ⬜  ⚫  ⚫  ⚫  ⬜  ⬜
3  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜
4  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜
5  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜
6  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
2  ⬜  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜
3  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜
4  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜
5  ⬜  ⚫  ⚫  ⬜  ⚫  ⬜  ⬜
6  ⬜  ❌  ❌  ❌  ⚫  ⬜  ⬜
7  ⬜  ⬜  ⚫  ⚫  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜
2  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜
3  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜
4  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫
5  ⬜  ⚫  ⬜  ❌  ⚫  ⬜  ⬜
6  ⬜  ⬜  ⚫  ❌  ⬜  ⚫  ⬜
7  ⬜  ⬜  ⚫  ❌  ⚫  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
2  ⬜  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜
3  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜
4  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜
5  ⬜  ⚫  ⚫  ⬜  ⚫  ⬜  ⬜
6  ❌  ❌  ❌  ⚫  ⬜  ⬜  ⬜
7  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜  ⬜

 63%|██████▎   | 632/1000 [00:16<00:09, 37.96it/s]

   A  B  C  D  E  F  G
1  ⬜  ⬜  ❌  ⬜  ⬜  ⬜  ⬜
2  ⬜  ⬜  ❌  ⬜  ⬜  ⬜  ⬜
3  ⬜  ⬜  ❌  ⚫  ⬜  ⬜  ⬜
4  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜  ⬜
5  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
6  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫
2  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜
3  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜
4  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫
5  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜
6  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫  ⚫
7  ⚫  ⬜  ⬜  ⚫  ❌  ❌  ❌

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
2  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
3  ⬜  ⬜  ⚫  ⚫  ⬜  ⬜  ⬜
4  ⬜  ❌  ❌  ❌  ⚫  ⬜  ⬜
5  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜
6  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⚫  ⬜  ⬜  ⚫  ❌  ❌  ❌
2  ⬜  ⚫  ⬜  ⬜  ⚫  ⚫  ⚫
3  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜
4  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫
5  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜
6  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜
7  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜

 64%|██████▎   | 636/1000 [00:16<00:09, 37.86it/s]

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜
2  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜
3  ⚫  ⚫  ⚫  ⬜  ⬜  ⚫  ⬜
4  ❌  ❌  ❌  ⚫  ⬜  ⬜  ⬜
5  ⚫  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜
6  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜
2  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜
3  ❌  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜
4  ❌  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜
5  ❌  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜
6  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜
2  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜
3  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫  ❌
4  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜  ❌
5  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜  ❌
6  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
2  ⬜  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜
3  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜
4  ⬜  ⚫  ⬜  ⚫  ⬜  ⬜  ⬜
5  ⚫  ❌  ❌  ❌  ⚫  ⬜  ⬜
6  ⬜  ⚫  ⚫  ⬜  ⬜  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

 64%|██████▍   | 640/1000 [00:16<00:09, 37.33it/s]

   A  B  C  D  E  F  G
1  ⬜  ⚫  ❌  ❌  ❌  ⬜  ⬜
2  ⬜  ⬜  ⚫  ⚫  ⚫  ⬜  ⬜
3  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜
4  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜
5  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜
6  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜
2  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜
3  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜
4  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫
5  ⬜  ⚫  ⬜  ⬜  ⚫  ⚫  ⬜
6  ⬜  ⬜  ⚫  ❌  ❌  ❌  ⚫
7  ⬜  ⬜  ⬜  ⬜  ⚫  ⚫  ⬜

   A  B  C  D  E  F  G
1  ⬜  ❌  ❌  ❌  ⬜  ⬜  ⬜
2  ⬜  ⬜  ⚫  ⚫  ⚫  ⬜  ⬜
3  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜
4  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜
5  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜
6  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ❌  ❌  ❌  ⚫  ⬜  ⬜  ⬜
2  ⚫  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜
3  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜
4  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫
5  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜
6  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜
7  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜

 64%|██████▍   | 644/1000 [00:16<00:09, 36.49it/s]

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⚫  ❌  ⬜  ⬜
2  ⬜  ⬜  ⬜  ⬜  ❌  ⬜  ⬜
3  ⬜  ⬜  ⚫  ⬜  ❌  ⬜  ⬜
4  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜
5  ⬜  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜
6  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
2  ⬜  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜
3  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜
4  ⬜  ⚫  ⬜  ⚫  ⬜  ⬜  ⬜
5  ⚫  ❌  ⬜  ⬜  ⚫  ⬜  ⬜
6  ⬜  ❌  ⚫  ⬜  ⬜  ⬜  ⬜
7  ⬜  ❌  ⬜  ⬜  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
2  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
3  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜  ⬜
4  ⬜  ⬜  ⬜  ⚫  ⚫  ⬜  ⬜
5  ⬜  ⬜  ⬜  ❌  ❌  ❌  ⚫
6  ⬜  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⚫  ❌  ⬜  ⬜
2  ⬜  ⬜  ⬜  ⬜  ❌  ⬜  ⬜
3  ⬜  ⬜  ⚫  ⬜  ❌  ⬜  ⬜
4  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜
5  ⬜  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜
6  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
2  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
3  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜  ⬜
4  ⬜  ⬜  ⬜  ⚫  ❌  ⬜  ⬜
5  ⬜  ⬜  ⬜  ⬜  ❌  ⚫  ⬜
6  ⬜  ⬜  ⬜  ⬜  ❌  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
2  ⬜  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜
3  ⬜  ❌  ⚫  ⬜  ⬜  ⚫  ⬜
4  ⬜  ❌  ⬜  ⚫  ⬜  ⬜  ⬜
5  ⚫  ❌  ⚫  ⬜  ⚫  ⬜  ⬜
6  ⬜  ⚫  ⬜  ⬜  ⬜  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

 65%|██████▌   | 650/1000 [00:16<00:08, 40.15it/s]

   A  B  C  D  E  F  G
1  ⚫  ❌  ⚫  ⚫  ⬜  ⬜  ⬜
2  ⚫  ❌  ⬜  ⬜  ⚫  ⬜  ⬜
3  ⬜  ❌  ⚫  ⬜  ⬜  ⚫  ⬜
4  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜
5  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜
6  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
2  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜  ⬜
3  ❌  ❌  ❌  ⚫  ⬜  ⬜  ⬜
4  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜  ⬜
5  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
6  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
2  ⬜  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜
3  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜
4  ⬜  ❌  ⬜  ⚫  ⬜  ⬜  ⬜
5  ⚫  ❌  ⬜  ⬜  ⚫  ⬜  ⬜
6  ⬜  ❌  ⬜  ⬜  ⬜  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜
2  ⬜  ⬜  ⬜  ⚫  ❌  ⬜  ⬜
3  ⬜  ⬜  ⚫  ⬜  ❌  ⚫  ⬜
4  ⬜  ⬜  ⬜  ⚫  ❌  ⬜  ⬜
5  ⬜  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜
6  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

 65%|██████▌   | 654/1000 [00:16<00:09, 37.21it/s]

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⚫  ❌  ⬜  ⬜
2  ⬜  ⬜  ⬜  ⬜  ❌  ⬜  ⬜
3  ⬜  ⬜  ⚫  ⬜  ❌  ⬜  ⬜
4  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜
5  ⬜  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜
6  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜
2  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜
3  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜
4  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫
5  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜
6  ⬜  ⬜  ⚫  ⚫  ⚫  ⚫  ⬜
7  ⬜  ⬜  ⚫  ❌  ❌  ❌  ⬜

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
2  ⬜  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜
3  ⬜  ⬜  ⚫  ⬜  ⬜  ❌  ⚫
4  ⬜  ⬜  ⬜  ⚫  ⬜  ❌  ⬜
5  ⬜  ⬜  ⬜  ⬜  ⚫  ❌  ⬜
6  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫
2  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜
3  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜
4  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫
5  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜  ❌
6  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫  ❌
7  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜  ❌

 66%|██████▌   | 658/1000 [00:16<00:09, 37.18it/s]

   A  B  C  D  E  F  G
1  ⚫  ⚫  ⬜  ⚫  ⬜  ⬜  ⬜
2  ❌  ❌  ❌  ⬜  ⚫  ⬜  ⬜
3  ⚫  ⚫  ⚫  ⬜  ⬜  ⚫  ⬜
4  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜
5  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜
6  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
2  ⬜  ⬜  ⬜  ⬜  ⚫  ⚫  ⬜
3  ⬜  ⬜  ⚫  ❌  ❌  ❌  ⚫
4  ⬜  ⬜  ⬜  ⚫  ⬜  ⚫  ⬜
5  ⬜  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜
6  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
2  ⬜  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜
3  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜
4  ⬜  ⚫  ⬜  ⚫  ⬜  ⬜  ⬜
5  ⚫  ❌  ⬜  ⬜  ⚫  ⬜  ⬜
6  ⬜  ❌  ⚫  ⬜  ⬜  ⬜  ⬜
7  ⬜  ❌  ⬜  ⬜  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜
2  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜
3  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜
4  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫
5  ⬜  ⚫  ⬜  ⬜  ⚫  ❌  ⬜
6  ⬜  ⬜  ⚫  ⬜  ⬜  ❌  ⚫
7  ⬜  ⬜  ⬜  ⬜  ⚫  ❌  ⬜

 66%|██████▌   | 662/1000 [00:16<00:09, 37.33it/s]

   A  B  C  D  E  F  G
1  ⚫  ⚫  ⬜  ⚫  ⬜  ⬜  ⬜
2  ❌  ❌  ❌  ⬜  ⚫  ⬜  ⬜
3  ⚫  ⚫  ⚫  ⬜  ⬜  ⚫  ⬜
4  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜
5  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜
6  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
2  ⬜  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜
3  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜
4  ⬜  ⚫  ⬜  ⚫  ⬜  ⬜  ⬜
5  ⚫  ❌  ⬜  ⬜  ⚫  ⬜  ⬜
6  ⬜  ❌  ⚫  ⬜  ⬜  ⬜  ⬜
7  ⬜  ❌  ⬜  ⬜  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜
2  ⬜  ⬜  ⬜  ⚫  ❌  ⬜  ⬜
3  ⬜  ⬜  ⚫  ⬜  ❌  ⚫  ⬜
4  ⬜  ⬜  ⬜  ⚫  ❌  ⬜  ⬜
5  ⬜  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜
6  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜
2  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜
3  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫  ⚫
4  ⚫  ⬜  ⬜  ⚫  ❌  ❌  ❌
5  ⬜  ⚫  ⬜  ⬜  ⚫  ⚫  ⚫
6  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

 67%|██████▋   | 666/1000 [00:17<00:08, 37.79it/s]

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜
2  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜
3  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫  ⚫
4  ⚫  ⬜  ⬜  ⚫  ❌  ❌  ❌
5  ⬜  ⚫  ⬜  ⬜  ⚫  ⚫  ⚫
6  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜
2  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜
3  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫  ❌
4  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜  ❌
5  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜  ❌
6  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
2  ⬜  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜
3  ⬜  ❌  ⚫  ⬜  ⬜  ⚫  ⬜
4  ⬜  ❌  ⬜  ⚫  ⬜  ⬜  ⬜
5  ⚫  ❌  ⚫  ⬜  ⚫  ⬜  ⬜
6  ⬜  ⚫  ⬜  ⬜  ⬜  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫
2  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜
3  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜
4  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫
5  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜
6  ⚫  ⚫  ⚫  ⬜  ⬜  ⚫  ⬜
7  ❌  ❌  ❌  ⚫  ⬜  ⬜  ⬜

 67%|██████▋   | 670/1000 [00:17<00:08, 37.30it/s]

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜
2  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜
3  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜
4  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫
5  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜
6  ⬜  ⬜  ⚫  ⚫  ⚫  ⚫  ⬜
7  ⬜  ⬜  ⚫  ❌  ❌  ❌  ⬜

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
2  ⬜  ⬜  ⬜  ⬜  ⚫  ⚫  ⬜
3  ⬜  ⬜  ⚫  ❌  ❌  ❌  ⚫
4  ⬜  ⬜  ⬜  ⚫  ⬜  ⚫  ⬜
5  ⬜  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜
6  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫
2  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜
3  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜
4  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫
5  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜
6  ⚫  ⚫  ⚫  ⬜  ⬜  ⚫  ⬜
7  ❌  ❌  ❌  ⚫  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
2  ⬜  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜
3  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜
4  ⬜  ⚫  ⬜  ⚫  ⬜  ⬜  ⬜
5  ⚫  ❌  ❌  ❌  ⚫  ⬜  ⬜
6  ⬜  ⚫  ⚫  ⬜  ⬜  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

 67%|██████▋   | 674/1000 [00:17<00:08, 36.72it/s]

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜
2  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜
3  ⚫  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜
4  ❌  ⚫  ⬜  ⚫  ⬜  ⬜  ⬜
5  ❌  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜
6  ❌  ⬜  ⚫  ⬜  ⬜  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
2  ⬜  ⬜  ⬜  ⬜  ⚫  ⚫  ⬜
3  ⬜  ⬜  ⚫  ⬜  ❌  ❌  ❌
4  ⬜  ⬜  ⬜  ⚫  ⬜  ⚫  ⚫
5  ⬜  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜
6  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
2  ⬜  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜
3  ⬜  ❌  ⚫  ⬜  ⬜  ⚫  ⬜
4  ⬜  ❌  ⬜  ⚫  ⬜  ⬜  ⬜
5  ⚫  ❌  ⚫  ⬜  ⚫  ⬜  ⬜
6  ⬜  ⚫  ⬜  ⬜  ⬜  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
2  ⬜  ⬜  ⬜  ⬜  ⚫  ⚫  ⬜
3  ⬜  ⬜  ⚫  ❌  ❌  ❌  ⚫
4  ⬜  ⬜  ⬜  ⚫  ⬜  ⚫  ⬜
5  ⬜  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜
6  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
2  ⬜  ⬜  ⬜  ⬜  ⚫  ⚫  ⬜
3  ⬜  ⬜  ⚫  ⬜  ❌  ❌  ❌
4  ⬜  ⬜  ⬜  ⚫  ⬜  ⚫  ⚫
5  ⬜  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜
6  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

 68%|██████▊   | 679/1000 [00:17<00:08, 38.81it/s]

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
2  ⬜  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜
3  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜
4  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜
5  ⬜  ⚫  ⚫  ⬜  ⚫  ⬜  ⬜
6  ❌  ❌  ❌  ⚫  ⬜  ⬜  ⬜
7  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜
2  ⬜  ⬜  ⬜  ❌  ❌  ❌  ⬜
3  ⬜  ⬜  ⚫  ⬜  ⚫  ⬜  ⬜
4  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜
5  ⬜  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜
6  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⚫  ⬜  ⬜  ⚫  ❌  ❌  ❌
2  ⬜  ⚫  ⬜  ⬜  ⚫  ⚫  ⚫
3  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜
4  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫
5  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜
6  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜
7  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫
2  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜
3  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜
4  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫
5  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜
6  ⚫  ⚫  ⚫  ⬜  ⬜  ⚫  ⬜
7  ❌  ❌  ❌  ⚫  ⬜  ⬜  ⬜

 68%|██████▊   | 683/1000 [00:17<00:08, 37.51it/s]

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⚫  ❌  ❌  ❌  ⬜
2  ⬜  ⬜  ⬜  ⚫  ⚫  ⬜  ⬜
3  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜
4  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜
5  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜
6  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜
2  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜  ❌
3  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫  ❌
4  ⚫  ⬜  ⬜  ⚫  ⬜  ⚫  ❌
5  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜  ⚫
6  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫
2  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜
3  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜
4  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫
5  ❌  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜
6  ❌  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜
7  ❌  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
2  ⬜  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜
3  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜
4  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜
5  ⬜  ⚫  ⚫  ⬜  ⚫  ⬜  ⬜
6  ⬜  ❌  ❌  ❌  ⚫  ⬜  ⬜
7  ⬜  ⬜  ⚫  ⚫  ⬜  ⬜  ⬜

 69%|██████▊   | 687/1000 [00:17<00:08, 37.07it/s]

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⚫  ⚫  ⬜  ⬜
2  ⬜  ⬜  ❌  ❌  ❌  ⚫  ⬜
3  ⬜  ⬜  ⚫  ⬜  ⚫  ⬜  ⬜
4  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜
5  ⬜  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜
6  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
2  ⬜  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜
3  ⬜  ⬜  ⚫  ⬜  ⬜  ❌  ⚫
4  ⬜  ⬜  ⬜  ⚫  ⬜  ❌  ⬜
5  ⬜  ⬜  ⬜  ⬜  ⚫  ❌  ⬜
6  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜
2  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜
3  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜
4  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫
5  ⬜  ⚫  ⬜  ❌  ⚫  ⬜  ⬜
6  ⬜  ⬜  ⚫  ❌  ⬜  ⚫  ⬜
7  ⬜  ⬜  ⚫  ❌  ⚫  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
2  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
3  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜  ⬜
4  ⬜  ⬜  ⬜  ⚫  ⚫  ⬜  ⬜
5  ⬜  ⬜  ⬜  ❌  ❌  ❌  ⚫
6  ⬜  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
2  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
3  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜  ⬜
4  ⬜  ⬜  ⬜  ❌  ⚫  ⬜  ⬜
5  ⬜  ⬜  ⬜  ❌  ⬜  ⬜  ⬜
6  ⬜  ⬜  ⬜  ❌  ⬜  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

 69%|██████▉   | 692/1000 [00:17<00:07, 39.21it/s]

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
2  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
3  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜  ⬜
4  ⬜  ⬜  ⬜  ❌  ⚫  ⬜  ⬜
5  ⬜  ⬜  ⬜  ❌  ⬜  ⬜  ⬜
6  ⬜  ⬜  ⬜  ❌  ⬜  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
2  ⬜  ⬜  ⬜  ⬜  ⚫  ❌  ⬜
3  ⬜  ⬜  ⚫  ⬜  ⬜  ❌  ⚫
4  ⬜  ⬜  ⬜  ⚫  ⬜  ❌  ⚫
5  ⬜  ⬜  ⬜  ⬜  ⚫  ⚫  ⬜
6  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜
2  ⬜  ⬜  ⬜  ⚫  ❌  ⬜  ⬜
3  ⬜  ⬜  ⚫  ⬜  ❌  ⚫  ⬜
4  ⬜  ⬜  ⬜  ⚫  ❌  ⬜  ⬜
5  ⬜  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜
6  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⚫  ⬜  ⬜  ⚫  ⬜  ⚫  ❌
2  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜  ❌
3  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫  ❌
4  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫
5  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜
6  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜
7  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⚫  ❌  ⚫  ⬜  ⬜
2  ⬜  ⬜  ⚫  ❌  ⚫  ⬜  ⬜
3  ⬜  ⬜  ⚫  ❌  ⬜  ⚫  ⬜
4  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜
5  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜
6  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

 70%|██████▉   | 697/1000 [00:17<00:07, 39.52it/s]

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
2  ⬜  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜
3  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜
4  ⬜  ❌  ⬜  ⚫  ⬜  ⬜  ⬜
5  ⚫  ❌  ⬜  ⬜  ⚫  ⬜  ⬜
6  ⬜  ❌  ⬜  ⬜  ⬜  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜
2  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜
3  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜
4  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫
5  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜
6  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜
7  ⬜  ⬜  ❌  ❌  ❌  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜
2  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜
3  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜
4  ⚫  ⬜  ⬜  ⚫  ⬜  ❌  ⚫
5  ⬜  ⚫  ⬜  ⬜  ⚫  ❌  ⬜
6  ⬜  ⬜  ⚫  ⬜  ⬜  ❌  ⚫
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⚫  ⬜

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
2  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
3  ⬜  ⬜  ⚫  ❌  ⬜  ⬜  ⬜
4  ⬜  ⬜  ⬜  ❌  ⚫  ⬜  ⬜
5  ⬜  ⬜  ⚫  ❌  ⬜  ⬜  ⬜
6  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

 70%|███████   | 701/1000 [00:17<00:07, 39.33it/s]

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜
2  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜
3  ⚫  ⚫  ⚫  ⬜  ⬜  ⚫  ⬜
4  ❌  ❌  ❌  ⚫  ⬜  ⬜  ⬜
5  ⚫  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜
6  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⬜  ⬜  ❌  ⬜  ⬜  ⬜  ⬜
2  ⬜  ⬜  ❌  ⬜  ⬜  ⬜  ⬜
3  ⬜  ⬜  ❌  ⚫  ⬜  ⬜  ⬜
4  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜  ⬜
5  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
6  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⬜  ⚫  ❌  ❌  ❌  ⬜  ⬜
2  ⬜  ⬜  ⚫  ⚫  ⚫  ⬜  ⬜
3  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜
4  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜
5  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜
6  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫
2  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜
3  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜
4  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫
5  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜
6  ⚫  ⚫  ⚫  ⬜  ⬜  ⚫  ⬜
7  ❌  ❌  ❌  ⚫  ⬜  ⬜  ⬜

 70%|███████   | 705/1000 [00:18<00:07, 38.80it/s]

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜
2  ⬜  ⬜  ⬜  ❌  ❌  ❌  ⬜
3  ⬜  ⬜  ⚫  ⬜  ⚫  ⬜  ⬜
4  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜
5  ⬜  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜
6  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜
2  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜
3  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜
4  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫
5  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜
6  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜
7  ⬜  ❌  ❌  ❌  ⚫  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
2  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
3  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜  ⬜
4  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜
5  ⬜  ⬜  ⬜  ⬜  ❌  ⚫  ⬜
6  ⬜  ⬜  ⬜  ⬜  ❌  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ❌  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫
2  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜
3  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜
4  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫
5  ❌  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜
6  ❌  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜
7  ❌  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜

 71%|███████   | 709/1000 [00:18<00:07, 38.77it/s]

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
2  ⬜  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜
3  ⬜  ⬜  ⚫  ⬜  ⬜  ❌  ⚫
4  ⬜  ⬜  ⬜  ⚫  ⬜  ❌  ⬜
5  ⬜  ⬜  ⬜  ⬜  ⚫  ❌  ⬜
6  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫
2  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜
3  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜
4  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫
5  ❌  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜
6  ❌  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜
7  ❌  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
2  ⬜  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜
3  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜
4  ⬜  ⚫  ⬜  ⚫  ⬜  ⬜  ⬜
5  ⚫  ❌  ❌  ❌  ⚫  ⬜  ⬜
6  ⬜  ⚫  ⚫  ⬜  ⬜  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
2  ⬜  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜
3  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜
4  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜
5  ⬜  ⚫  ⚫  ⬜  ⚫  ⬜  ⬜
6  ❌  ❌  ❌  ⚫  ⬜  ⬜  ⬜
7  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜  ⬜

 71%|███████▏  | 713/1000 [00:18<00:07, 38.68it/s]

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
2  ⬜  ⬜  ⬜  ⬜  ⚫  ⚫  ⬜
3  ⬜  ⬜  ⚫  ❌  ❌  ❌  ⚫
4  ⬜  ⬜  ⬜  ⚫  ⬜  ⚫  ⬜
5  ⬜  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜
6  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
2  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
3  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜  ⬜
4  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜
5  ⬜  ⬜  ⬜  ⬜  ❌  ⚫  ⬜
6  ⬜  ⬜  ⬜  ⬜  ❌  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ❌  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
2  ⬜  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜
3  ⬜  ⬜  ⚫  ⬜  ⬜  ❌  ⚫
4  ⬜  ⬜  ⬜  ⚫  ⬜  ❌  ⬜
5  ⬜  ⬜  ⬜  ⬜  ⚫  ❌  ⬜
6  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
2  ⬜  ⬜  ⬜  ❌  ⬜  ⬜  ⬜
3  ⬜  ⬜  ⚫  ❌  ⬜  ⬜  ⬜
4  ⬜  ⬜  ⬜  ❌  ⚫  ⬜  ⬜
5  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜
6  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⬜  ⚫  ❌  ❌  ❌  ⬜  ⬜
2  ⬜  ⬜  ⚫  ⚫  ⚫  ⬜  ⬜
3  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜
4  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜
5  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜
6  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

 72%|███████▏  | 718/1000 [00:18<00:06, 40.79it/s]

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
2  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
3  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜  ⬜
4  ⬜  ⬜  ⬜  ❌  ⚫  ⬜  ⬜
5  ⬜  ⬜  ⬜  ❌  ⬜  ⬜  ⬜
6  ⬜  ⬜  ⬜  ❌  ⬜  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜
2  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜
3  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜
4  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫
5  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜
6  ⬜  ⬜  ⚫  ⚫  ⚫  ⚫  ⬜
7  ⬜  ⬜  ⚫  ❌  ❌  ❌  ⬜

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⚫  ❌  ⚫  ⬜  ⬜
2  ⬜  ⬜  ⚫  ❌  ⚫  ⬜  ⬜
3  ⬜  ⬜  ⚫  ❌  ⬜  ⚫  ⬜
4  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜
5  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜
6  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⬜  ❌  ❌  ❌  ⬜  ⬜  ⬜
2  ⬜  ⬜  ⚫  ⚫  ⚫  ⬜  ⬜
3  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜
4  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜
5  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜
6  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜
2  ⬜  ⬜  ⬜  ⚫  ❌  ⬜  ⬜
3  ⬜  ⬜  ⚫  ⬜  ❌  ⚫  ⬜
4  ⬜  ⬜  ⬜  ⚫  ❌  ⬜  ⬜
5  ⬜  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜
6  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

 72%|███████▏  | 723/1000 [00:18<00:06, 39.62it/s]

   A  B  C  D  E  F  G
1  ⚫  ⬜  ⬜  ⚫  ❌  ❌  ❌
2  ⬜  ⚫  ⬜  ⬜  ⚫  ⚫  ⚫
3  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜
4  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫
5  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜
6  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜
7  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
2  ⬜  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜
3  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜
4  ⬜  ⬜  ❌  ⚫  ⬜  ⬜  ⬜
5  ⬜  ⚫  ❌  ⬜  ⚫  ⬜  ⬜
6  ⬜  ⬜  ❌  ⚫  ⬜  ⬜  ⬜
7  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
2  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
3  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜  ⬜
4  ⬜  ⬜  ⬜  ⚫  ⚫  ⬜  ⬜
5  ⬜  ⬜  ❌  ❌  ❌  ⚫  ⬜
6  ⬜  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
2  ⬜  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜
3  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜
4  ⬜  ⬜  ❌  ⚫  ⬜  ⬜  ⬜
5  ⬜  ⚫  ❌  ⬜  ⚫  ⬜  ⬜
6  ⬜  ⬜  ❌  ⚫  ⬜  ⬜  ⬜
7  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜  ⬜

 73%|███████▎  | 727/1000 [00:18<00:06, 39.02it/s]

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
2  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
3  ⬜  ⬜  ⚫  ⬜  ❌  ⬜  ⬜
4  ⬜  ⬜  ⬜  ⚫  ❌  ⬜  ⬜
5  ⬜  ⬜  ⬜  ⬜  ❌  ⚫  ⬜
6  ⬜  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
2  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
3  ⬜  ⬜  ⚫  ⚫  ⬜  ⬜  ⬜
4  ⬜  ❌  ❌  ❌  ⚫  ⬜  ⬜
5  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜
6  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
2  ⬜  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜
3  ⬜  ⬜  ⚫  ⬜  ⬜  ❌  ⚫
4  ⬜  ⬜  ⬜  ⚫  ⬜  ❌  ⬜
5  ⬜  ⬜  ⬜  ⬜  ⚫  ❌  ⬜
6  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫
2  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜
3  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜
4  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫
5  ❌  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜
6  ❌  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜
7  ❌  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜
2  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜
3  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫  ⚫
4  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜  ❌
5  ⬜  ⚫  ⬜  ⬜  ⚫  ⚫  ❌
6  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜  ❌
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

 73%|███████▎  | 732/1000 [00:18<00:06, 39.79it/s]

   A  B  C  D  E  F  G
1  ⚫  ⬜  ⬜  ⚫  ⬜  ⚫  ❌
2  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜  ❌
3  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫  ❌
4  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫
5  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜
6  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜
7  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫
2  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜
3  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜
4  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫
5  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜
6  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫  ⚫
7  ⚫  ⬜  ⬜  ⚫  ❌  ❌  ❌

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜
2  ⬜  ⬜  ⬜  ❌  ❌  ❌  ⬜
3  ⬜  ⬜  ⚫  ⬜  ⚫  ⬜  ⬜
4  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜
5  ⬜  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜
6  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⚫  ❌  ❌  ❌  ⬜
2  ⬜  ⬜  ⬜  ⚫  ⚫  ⬜  ⬜
3  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜
4  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜
5  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜
6  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

 74%|███████▎  | 736/1000 [00:18<00:06, 38.78it/s]

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜
2  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜
3  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫  ❌
4  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜  ❌
5  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜  ❌
6  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜
2  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜
3  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜
4  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫
5  ⬜  ⚫  ⬜  ⬜  ⚫  ❌  ⬜
6  ⬜  ⬜  ⚫  ⬜  ⬜  ❌  ⚫
7  ⬜  ⬜  ⬜  ⬜  ⚫  ❌  ⬜

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
2  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
3  ⬜  ⬜  ⚫  ⬜  ⚫  ⬜  ⬜
4  ⬜  ⬜  ⬜  ❌  ❌  ❌  ⬜
5  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜
6  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜
2  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜
3  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫  ⚫
4  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜  ❌
5  ⬜  ⚫  ⬜  ⬜  ⚫  ⚫  ❌
6  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜  ❌
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

 74%|███████▍  | 740/1000 [00:18<00:06, 38.35it/s]

   A  B  C  D  E  F  G
1  ⬜  ⬜  ❌  ⬜  ⬜  ⬜  ⬜
2  ⬜  ⬜  ❌  ⬜  ⬜  ⬜  ⬜
3  ⬜  ⬜  ❌  ⚫  ⬜  ⬜  ⬜
4  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜  ⬜
5  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
6  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
2  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
3  ⬜  ⬜  ⚫  ❌  ⬜  ⬜  ⬜
4  ⬜  ⬜  ⬜  ❌  ⚫  ⬜  ⬜
5  ⬜  ⬜  ⚫  ❌  ⬜  ⬜  ⬜
6  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ❌  ❌  ❌  ⚫  ⬜  ⬜  ⬜
2  ⚫  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜
3  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜
4  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫
5  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜
6  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜
7  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⬜  ⚫  ❌  ❌  ❌  ⬜  ⬜
2  ⬜  ⬜  ⚫  ⚫  ⚫  ⬜  ⬜
3  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜
4  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜
5  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜
6  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
2  ⬜  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜
3  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜
4  ⬜  ❌  ⬜  ⚫  ⬜  ⬜  ⬜
5  ⚫  ❌  ⬜  ⬜  ⚫  ⬜  ⬜
6  ⬜  ❌  ⬜  ⬜  ⬜  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

 74%|███████▍  | 745/1000 [00:19<00:06, 40.20it/s]

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
2  ⬜  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜
3  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜
4  ⬜  ❌  ⬜  ⚫  ⬜  ⬜  ⬜
5  ⚫  ❌  ⬜  ⬜  ⚫  ⬜  ⬜
6  ⬜  ❌  ⬜  ⬜  ⬜  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜
2  ❌  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜
3  ❌  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜
4  ❌  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜
5  ⚫  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜
6  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⬜  ⬜  ❌  ⬜
2  ⬜  ⬜  ⬜  ⬜  ⚫  ❌  ⬜
3  ⬜  ⬜  ⚫  ⬜  ⬜  ❌  ⚫
4  ⬜  ⬜  ⬜  ⚫  ⬜  ⚫  ⬜
5  ⬜  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜
6  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫
2  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜
3  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜
4  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫
5  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜
6  ⚫  ⚫  ⚫  ⬜  ⬜  ⚫  ⬜
7  ❌  ❌  ❌  ⚫  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
2  ⬜  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜
3  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜
4  ⬜  ⚫  ⬜  ⚫  ⬜  ⬜  ⬜
5  ⚫  ❌  ❌  ❌  ⚫  ⬜  ⬜
6  ⬜  ⚫  ⚫  ⬜  ⬜  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

 75%|███████▌  | 750/1000 [00:19<00:06, 39.47it/s]

   A  B  C  D  E  F  G
1  ⬜  ⚫  ⬜  ⚫  ⬜  ⬜  ⬜
2  ⚫  ❌  ⬜  ⬜  ⚫  ⬜  ⬜
3  ⬜  ❌  ⚫  ⬜  ⬜  ⚫  ⬜
4  ⬜  ❌  ⬜  ⚫  ⬜  ⬜  ⬜
5  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜
6  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⬜  ⬜  ❌  ⬜  ⬜  ⬜  ⬜
2  ⬜  ⬜  ❌  ⬜  ⬜  ⬜  ⬜
3  ⬜  ⬜  ❌  ⚫  ⬜  ⬜  ⬜
4  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜  ⬜
5  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
6  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜
2  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜
3  ⚫  ⚫  ⚫  ⬜  ⬜  ⚫  ⬜
4  ❌  ❌  ❌  ⚫  ⬜  ⬜  ⬜
5  ⚫  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜
6  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
2  ⬜  ⬜  ⬜  ❌  ⬜  ⬜  ⬜
3  ⬜  ⬜  ⚫  ❌  ⬜  ⬜  ⬜
4  ⬜  ⬜  ⬜  ❌  ⚫  ⬜  ⬜
5  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜
6  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
2  ⬜  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜
3  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜
4  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜
5  ❌  ❌  ❌  ⬜  ⚫  ⬜  ⬜
6  ⬜  ⚫  ⬜  ⬜  ⬜  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

 76%|███████▌  | 755/1000 [00:19<00:05, 41.23it/s]

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
2  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
3  ⬜  ⬜  ⚫  ⬜  ⚫  ⬜  ⬜
4  ⬜  ⬜  ⬜  ❌  ❌  ❌  ⬜
5  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜
6  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ❌  ❌  ❌  ⚫  ⬜  ⬜  ⬜
2  ⚫  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜
3  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜
4  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫
5  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜
6  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜
7  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
2  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
3  ⬜  ⬜  ⚫  ⬜  ⚫  ⬜  ⬜
4  ⬜  ⬜  ⬜  ❌  ❌  ❌  ⬜
5  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜
6  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⚫  ⚫  ⬜  ⬜
2  ⬜  ⬜  ❌  ❌  ❌  ⚫  ⬜
3  ⬜  ⬜  ⚫  ⬜  ⚫  ⬜  ⬜
4  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜
5  ⬜  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜
6  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⬜  ⬜  ❌  ⬜  ⬜  ⬜  ⬜
2  ⬜  ⬜  ❌  ⬜  ⬜  ⬜  ⬜
3  ⬜  ⬜  ❌  ⚫  ⬜  ⬜  ⬜
4  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜  ⬜
5  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
6  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

 76%|███████▌  | 760/1000 [00:19<00:05, 43.28it/s]

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
2  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
3  ⬜  ⬜  ⚫  ⬜  ❌  ⬜  ⬜
4  ⬜  ⬜  ⬜  ⚫  ❌  ⬜  ⬜
5  ⬜  ⬜  ⬜  ⬜  ❌  ⚫  ⬜
6  ⬜  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
2  ⬜  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜
3  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜
4  ⬜  ⬜  ❌  ⚫  ⬜  ⬜  ⬜
5  ⬜  ⚫  ❌  ⬜  ⚫  ⬜  ⬜
6  ⬜  ⬜  ❌  ⚫  ⬜  ⬜  ⬜
7  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⚫  ⚫  ⬜  ⬜
2  ⬜  ⬜  ❌  ❌  ❌  ⚫  ⬜
3  ⬜  ⬜  ⚫  ⬜  ⚫  ⬜  ⬜
4  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜
5  ⬜  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜
6  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
2  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
3  ⬜  ⬜  ⚫  ⬜  ⚫  ⬜  ⬜
4  ⬜  ⬜  ❌  ❌  ❌  ⚫  ⬜
5  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜
6  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
2  ⬜  ⬜  ⬜  ⬜  ⚫  ⚫  ⬜
3  ⬜  ⬜  ⚫  ⬜  ❌  ❌  ❌
4  ⬜  ⬜  ⬜  ⚫  ⬜  ⚫  ⚫
5  ⬜  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜
6  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

 76%|███████▋  | 765/1000 [00:19<00:05, 44.41it/s]

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜
2  ❌  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜
3  ❌  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜
4  ❌  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜
5  ⚫  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜
6  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜
2  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜
3  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜
4  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫
5  ⬜  ⚫  ⬜  ❌  ⚫  ⬜  ⬜
6  ⬜  ⬜  ⚫  ❌  ⬜  ⚫  ⬜
7  ⬜  ⬜  ⚫  ❌  ⚫  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
2  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
3  ⬜  ⬜  ⚫  ❌  ⬜  ⬜  ⬜
4  ⬜  ⬜  ⬜  ❌  ⚫  ⬜  ⬜
5  ⬜  ⬜  ⚫  ❌  ⬜  ⬜  ⬜
6  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⚫  ⚫  ⬜  ⚫  ⬜  ⬜  ⬜
2  ❌  ❌  ❌  ⬜  ⚫  ⬜  ⬜
3  ⚫  ⚫  ⚫  ⬜  ⬜  ⚫  ⬜
4  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜
5  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜
6  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⚫  ❌  ⚫  ⬜  ⬜
2  ⬜  ⬜  ⚫  ❌  ⚫  ⬜  ⬜
3  ⬜  ⬜  ⚫  ❌  ⬜  ⚫  ⬜
4  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜
5  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜
6  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

 77%|███████▋  | 770/1000 [00:19<00:05, 40.54it/s]

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
2  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜  ⬜
3  ❌  ❌  ❌  ⚫  ⬜  ⬜  ⬜
4  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜  ⬜
5  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
6  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
2  ⬜  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜
3  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜
4  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜
5  ❌  ❌  ❌  ⬜  ⚫  ⬜  ⬜
6  ⬜  ⚫  ⬜  ⬜  ⬜  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
2  ⬜  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜
3  ⬜  ⬜  ⚫  ⬜  ⬜  ❌  ⚫
4  ⬜  ⬜  ⬜  ⚫  ⬜  ❌  ⬜
5  ⬜  ⬜  ⬜  ⬜  ⚫  ❌  ⬜
6  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
2  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
3  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜  ⬜
4  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜
5  ⬜  ⬜  ⬜  ⬜  ❌  ⚫  ⬜
6  ⬜  ⬜  ⬜  ⬜  ❌  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ❌  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜
2  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜
3  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫  ❌
4  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜  ❌
5  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜  ❌
6  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

 78%|███████▊  | 775/1000 [00:19<00:05, 42.02it/s]

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
2  ⬜  ⬜  ❌  ⬜  ⬜  ⬜  ⬜
3  ⬜  ⬜  ❌  ⚫  ⬜  ⬜  ⬜
4  ⬜  ⬜  ❌  ⬜  ⬜  ⬜  ⬜
5  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜  ⬜
6  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
2  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
3  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜  ⬜
4  ⬜  ⬜  ⬜  ⚫  ❌  ⬜  ⬜
5  ⬜  ⬜  ⬜  ⬜  ❌  ⚫  ⬜
6  ⬜  ⬜  ⬜  ⬜  ❌  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
2  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜  ⬜
3  ❌  ❌  ❌  ⚫  ⬜  ⬜  ⬜
4  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜  ⬜
5  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
6  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⬜  ⚫  ⚫  ⚫  ⬜  ⬜  ⬜
2  ⚫  ❌  ❌  ❌  ⚫  ⬜  ⬜
3  ⬜  ⚫  ⚫  ⬜  ⬜  ⚫  ⬜
4  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜
5  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜
6  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
2  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
3  ⬜  ⬜  ⚫  ⬜  ❌  ⬜  ⬜
4  ⬜  ⬜  ⬜  ⚫  ❌  ⬜  ⬜
5  ⬜  ⬜  ⬜  ⬜  ❌  ⚫  ⬜
6  ⬜  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

 78%|███████▊  | 780/1000 [00:19<00:05, 43.27it/s]

   A  B  C  D  E  F  G
1  ❌  ⚫  ⬜  ⚫  ⬜  ⬜  ⬜
2  ❌  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜
3  ❌  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜
4  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫
5  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜
6  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜
7  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
2  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜  ⬜
3  ❌  ❌  ❌  ⚫  ⬜  ⬜  ⬜
4  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜  ⬜
5  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
6  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
2  ⬜  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜
3  ⬜  ❌  ⚫  ⬜  ⬜  ⚫  ⬜
4  ⬜  ❌  ⬜  ⚫  ⬜  ⬜  ⬜
5  ⚫  ❌  ⚫  ⬜  ⚫  ⬜  ⬜
6  ⬜  ⚫  ⬜  ⬜  ⬜  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜
2  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜
3  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜
4  ⚫  ⬜  ⬜  ⚫  ⬜  ❌  ⚫
5  ⬜  ⚫  ⬜  ⬜  ⚫  ❌  ⬜
6  ⬜  ⬜  ⚫  ⬜  ⬜  ❌  ⚫
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⚫  ⬜

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
2  ⬜  ⬜  ⬜  ❌  ⬜  ⬜  ⬜
3  ⬜  ⬜  ⚫  ❌  ⬜  ⬜  ⬜
4  ⬜  ⬜  ⬜  ❌  ⚫  ⬜  ⬜
5  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜
6  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

 78%|███████▊  | 785/1000 [00:19<00:05, 42.84it/s]

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
2  ⬜  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜
3  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜
4  ⬜  ⬜  ❌  ⚫  ⬜  ⬜  ⬜
5  ⬜  ⚫  ❌  ⬜  ⚫  ⬜  ⬜
6  ⬜  ⬜  ❌  ⚫  ⬜  ⬜  ⬜
7  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
2  ⬜  ⬜  ⬜  ⬜  ⚫  ⚫  ⬜
3  ⬜  ⬜  ⚫  ❌  ❌  ❌  ⚫
4  ⬜  ⬜  ⬜  ⚫  ⬜  ⚫  ⬜
5  ⬜  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜
6  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
2  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
3  ⬜  ⬜  ⚫  ❌  ⬜  ⬜  ⬜
4  ⬜  ⬜  ⬜  ❌  ⚫  ⬜  ⬜
5  ⬜  ⬜  ⚫  ❌  ⬜  ⬜  ⬜
6  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
2  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
3  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜  ⬜
4  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜
5  ⬜  ⬜  ⬜  ⬜  ❌  ⚫  ⬜
6  ⬜  ⬜  ⬜  ⬜  ❌  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ❌  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
2  ⬜  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜
3  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜
4  ⬜  ⬜  ❌  ⚫  ⬜  ⬜  ⬜
5  ⬜  ⚫  ❌  ⬜  ⚫  ⬜  ⬜
6  ⬜  ⬜  ❌  ⚫  ⬜  ⬜  ⬜
7  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜  ⬜

 79%|███████▉  | 790/1000 [00:20<00:04, 43.91it/s]

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜
2  ❌  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜
3  ❌  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜
4  ❌  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜
5  ⚫  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜
6  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⬜  ⚫  ❌  ❌  ❌  ⬜  ⬜
2  ⬜  ⬜  ⚫  ⚫  ⚫  ⬜  ⬜
3  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜
4  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜
5  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜
6  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜
2  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜
3  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜
4  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫
5  ⬜  ⚫  ⬜  ⬜  ⚫  ⚫  ⬜
6  ⬜  ⬜  ⚫  ⬜  ❌  ❌  ❌
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⚫  ⬜

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜
2  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜
3  ⚫  ⚫  ⚫  ⬜  ⬜  ⚫  ⬜
4  ❌  ❌  ❌  ⚫  ⬜  ⬜  ⬜
5  ⚫  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜
6  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
2  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
3  ⬜  ⬜  ❌  ⚫  ⬜  ⬜  ⬜
4  ⬜  ⬜  ❌  ⬜  ⬜  ⬜  ⬜
5  ⬜  ⬜  ❌  ⬜  ⬜  ⬜  ⬜
6  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

 80%|███████▉  | 795/1000 [00:20<00:04, 41.97it/s]

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜
2  ⬜  ⬜  ⬜  ⚫  ❌  ⬜  ⬜
3  ⬜  ⬜  ⚫  ⬜  ❌  ⚫  ⬜
4  ⬜  ⬜  ⬜  ⚫  ❌  ⬜  ⬜
5  ⬜  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜
6  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜
2  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜
3  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫  ⚫
4  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜  ❌
5  ⬜  ⚫  ⬜  ⬜  ⚫  ⚫  ❌
6  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜  ❌
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
2  ⬜  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜
3  ⬜  ❌  ⚫  ⬜  ⬜  ⚫  ⬜
4  ⬜  ❌  ⬜  ⚫  ⬜  ⬜  ⬜
5  ⚫  ❌  ⚫  ⬜  ⚫  ⬜  ⬜
6  ⬜  ⚫  ⬜  ⬜  ⬜  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜
2  ⬜  ⬜  ⬜  ⚫  ❌  ⬜  ⬜
3  ⬜  ⬜  ⚫  ⬜  ❌  ⚫  ⬜
4  ⬜  ⬜  ⬜  ⚫  ❌  ⬜  ⬜
5  ⬜  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜
6  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫
2  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜
3  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜
4  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫
5  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜
6  ⚫  ⚫  ⚫  ⬜  ⬜  ⚫  ⬜
7  ❌  ❌  ❌  ⚫  ⬜  ⬜  ⬜

 80%|████████  | 800/1000 [00:20<00:04, 41.08it/s]

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
2  ⬜  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜
3  ⬜  ❌  ⚫  ⬜  ⬜  ⚫  ⬜
4  ⬜  ❌  ⬜  ⚫  ⬜  ⬜  ⬜
5  ⚫  ❌  ⚫  ⬜  ⚫  ⬜  ⬜
6  ⬜  ⚫  ⬜  ⬜  ⬜  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜
2  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜
3  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜
4  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫
5  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜
6  ⬜  ⬜  ⚫  ⚫  ⚫  ⚫  ⬜
7  ⬜  ⬜  ⚫  ❌  ❌  ❌  ⬜

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
2  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
3  ⬜  ⬜  ⚫  ⬜  ⚫  ⬜  ⬜
4  ⬜  ⬜  ❌  ❌  ❌  ⚫  ⬜
5  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜
6  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
2  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
3  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜  ⬜
4  ⬜  ⬜  ⬜  ⚫  ⚫  ⬜  ⬜
5  ⬜  ⬜  ⬜  ❌  ❌  ❌  ⚫
6  ⬜  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
2  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜  ⬜
3  ❌  ❌  ❌  ⚫  ⬜  ⬜  ⬜
4  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜  ⬜
5  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
6  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

 80%|████████  | 805/1000 [00:20<00:04, 41.26it/s]

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
2  ⬜  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜
3  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜
4  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜
5  ⬜  ⚫  ⚫  ⬜  ⚫  ⬜  ⬜
6  ❌  ❌  ❌  ⚫  ⬜  ⬜  ⬜
7  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
2  ⬜  ⬜  ⬜  ⬜  ⚫  ❌  ⬜
3  ⬜  ⬜  ⚫  ⬜  ⬜  ❌  ⚫
4  ⬜  ⬜  ⬜  ⚫  ⬜  ❌  ⚫
5  ⬜  ⬜  ⬜  ⬜  ⚫  ⚫  ⬜
6  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
2  ⬜  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜
3  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜
4  ⬜  ⚫  ⬜  ⚫  ⬜  ⬜  ⬜
5  ⚫  ❌  ⬜  ⬜  ⚫  ⬜  ⬜
6  ⬜  ❌  ⚫  ⬜  ⬜  ⬜  ⬜
7  ⬜  ❌  ⬜  ⬜  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜
2  ⬜  ⬜  ⬜  ⚫  ❌  ⬜  ⬜
3  ⬜  ⬜  ⚫  ⬜  ❌  ⚫  ⬜
4  ⬜  ⬜  ⬜  ⚫  ❌  ⬜  ⬜
5  ⬜  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜
6  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜
2  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜
3  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜
4  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫
5  ⬜  ⚫  ⬜  ⬜  ⚫  ⚫  ⬜
6  ⬜  ⬜  ⚫  ⬜  ❌  ❌  ❌
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⚫  ⬜

 81%|████████  | 810/1000 [00:20<00:04, 41.36it/s]

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
2  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
3  ⬜  ⬜  ⚫  ⬜  ❌  ⬜  ⬜
4  ⬜  ⬜  ⬜  ⚫  ❌  ⬜  ⬜
5  ⬜  ⬜  ⬜  ⬜  ❌  ⚫  ⬜
6  ⬜  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜
2  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜
3  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜
4  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫
5  ⬜  ⚫  ⬜  ⬜  ⚫  ⚫  ⬜
6  ⬜  ⬜  ⚫  ❌  ❌  ❌  ⚫
7  ⬜  ⬜  ⬜  ⬜  ⚫  ⚫  ⬜

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⚫  ❌  ❌  ❌  ⬜
2  ⬜  ⬜  ⬜  ⚫  ⚫  ⬜  ⬜
3  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜
4  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜
5  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜
6  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
2  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜  ⬜
3  ❌  ❌  ❌  ⚫  ⬜  ⬜  ⬜
4  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜  ⬜
5  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
6  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⬜  ⬜  ❌  ⬜
2  ⬜  ⬜  ⬜  ⬜  ⚫  ❌  ⬜
3  ⬜  ⬜  ⚫  ⬜  ⬜  ❌  ⚫
4  ⬜  ⬜  ⬜  ⚫  ⬜  ⚫  ⬜
5  ⬜  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜
6  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

 82%|████████▏ | 815/1000 [00:20<00:04, 42.12it/s]

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜
2  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜
3  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜
4  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫
5  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜
6  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜
7  ⬜  ⬜  ❌  ❌  ❌  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
2  ⬜  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜
3  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜
4  ⬜  ❌  ⬜  ⚫  ⬜  ⬜  ⬜
5  ⚫  ❌  ⬜  ⬜  ⚫  ⬜  ⬜
6  ⬜  ❌  ⬜  ⬜  ⬜  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜
2  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜
3  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜
4  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫
5  ⬜  ⚫  ⬜  ❌  ⚫  ⬜  ⬜
6  ⬜  ⬜  ⚫  ❌  ⬜  ⚫  ⬜
7  ⬜  ⬜  ⚫  ❌  ⚫  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
2  ⬜  ⬜  ⬜  ⬜  ⚫  ⚫  ⬜
3  ⬜  ⬜  ⚫  ⬜  ❌  ❌  ❌
4  ⬜  ⬜  ⬜  ⚫  ⬜  ⚫  ⚫
5  ⬜  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜
6  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜
2  ⬜  ⬜  ⬜  ❌  ❌  ❌  ⬜
3  ⬜  ⬜  ⚫  ⬜  ⚫  ⬜  ⬜
4  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜
5  ⬜  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜
6  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

 82%|████████▏ | 820/1000 [00:20<00:04, 41.78it/s]

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
2  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
3  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜  ⬜
4  ⬜  ⬜  ⬜  ⚫  ⚫  ⬜  ⬜
5  ⬜  ⬜  ❌  ❌  ❌  ⚫  ⬜
6  ⬜  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
2  ⬜  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜
3  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜
4  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜
5  ❌  ❌  ❌  ⬜  ⚫  ⬜  ⬜
6  ⬜  ⚫  ⬜  ⬜  ⬜  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
2  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
3  ⬜  ⬜  ⚫  ⬜  ❌  ⬜  ⬜
4  ⬜  ⬜  ⬜  ⚫  ❌  ⬜  ⬜
5  ⬜  ⬜  ⬜  ⬜  ❌  ⚫  ⬜
6  ⬜  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⬜  ⬜  ❌  ⬜
2  ⬜  ⬜  ⬜  ⬜  ⚫  ❌  ⬜
3  ⬜  ⬜  ⚫  ⬜  ⬜  ❌  ⚫
4  ⬜  ⬜  ⬜  ⚫  ⬜  ⚫  ⬜
5  ⬜  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜
6  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
2  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
3  ⬜  ⬜  ⚫  ⚫  ⬜  ⬜  ⬜
4  ⬜  ❌  ❌  ❌  ⚫  ⬜  ⬜
5  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜
6  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜
2  ❌  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜
3  ❌  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜
4  ❌  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜
5  ⚫  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜
6  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

 83%|████████▎ | 826/1000 [00:20<00:03, 44.27it/s]

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜
2  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜
3  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜
4  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫
5  ⬜  ⚫  ⬜  ⬜  ⚫  ⚫  ⬜
6  ⬜  ⬜  ⚫  ⬜  ❌  ❌  ❌
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⚫  ⬜

   A  B  C  D  E  F  G
1  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫
2  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜
3  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜
4  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫
5  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜
6  ⚫  ⚫  ⚫  ⬜  ⬜  ⚫  ⬜
7  ❌  ❌  ❌  ⚫  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
2  ⬜  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜
3  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜
4  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜
5  ❌  ❌  ❌  ⬜  ⚫  ⬜  ⬜
6  ⬜  ⚫  ⬜  ⬜  ⬜  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ❌  ❌  ❌  ⚫  ⬜  ⬜  ⬜
2  ⚫  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜
3  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜
4  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫
5  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜
6  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜
7  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
2  ⬜  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜
3  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜
4  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜
5  ❌  ❌  ❌  ⬜  ⚫  ⬜  ⬜
6  ⬜  ⚫  ⬜  ⬜  ⬜  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

 83%|████████▎ | 831/1000 [00:21<00:04, 41.94it/s]

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
2  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
3  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜  ⬜
4  ⬜  ⬜  ⬜  ⚫  ⚫  ⬜  ⬜
5  ⬜  ⬜  ⬜  ❌  ❌  ❌  ⚫
6  ⬜  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
2  ⬜  ⬜  ⬜  ⬜  ⚫  ⚫  ⬜
3  ⬜  ⬜  ⚫  ⬜  ❌  ❌  ❌
4  ⬜  ⬜  ⬜  ⚫  ⬜  ⚫  ⚫
5  ⬜  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜
6  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜
2  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜
3  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜
4  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫
5  ⬜  ⚫  ⬜  ❌  ⚫  ⬜  ⬜
6  ⬜  ⬜  ⚫  ❌  ⬜  ⚫  ⬜
7  ⬜  ⬜  ⚫  ❌  ⚫  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
2  ⬜  ⬜  ⬜  ⬜  ⚫  ❌  ⬜
3  ⬜  ⬜  ⚫  ⬜  ⬜  ❌  ⚫
4  ⬜  ⬜  ⬜  ⚫  ⬜  ❌  ⚫
5  ⬜  ⬜  ⬜  ⬜  ⚫  ⚫  ⬜
6  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜
2  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜
3  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜
4  ⚫  ⬜  ⬜  ⚫  ⬜  ❌  ⚫
5  ⬜  ⚫  ⬜  ⬜  ⚫  ❌  ⬜
6  ⬜  ⬜  ⚫  ⬜  ⬜  ❌  ⚫
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⚫  ⬜

 84%|████████▎ | 836/1000 [00:21<00:04, 40.67it/s]

   A  B  C  D  E  F  G
1  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫
2  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜
3  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜
4  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫
5  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜  ❌
6  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫  ❌
7  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜  ❌

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⬜  ⬜  ❌  ⬜
2  ⬜  ⬜  ⬜  ⬜  ⚫  ❌  ⬜
3  ⬜  ⬜  ⚫  ⬜  ⬜  ❌  ⚫
4  ⬜  ⬜  ⬜  ⚫  ⬜  ⚫  ⬜
5  ⬜  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜
6  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜
2  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜
3  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫  ⚫
4  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜  ❌
5  ⬜  ⚫  ⬜  ⬜  ⚫  ⚫  ❌
6  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜  ❌
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜
2  ⬜  ⬜  ⬜  ❌  ❌  ❌  ⬜
3  ⬜  ⬜  ⚫  ⬜  ⚫  ⬜  ⬜
4  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜
5  ⬜  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜
6  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⚫  ⚫  ⬜  ⬜
2  ⬜  ⬜  ❌  ❌  ❌  ⚫  ⬜
3  ⬜  ⬜  ⚫  ⬜  ⚫  ⬜  ⬜
4  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜
5  ⬜  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜
6  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

 84%|████████▍ | 841/1000 [00:21<00:04, 39.38it/s]

   A  B  C  D  E  F  G
1  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫
2  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜
3  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜
4  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫
5  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜  ❌
6  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫  ❌
7  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜  ❌

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⚫  ❌  ⚫  ⬜  ⬜
2  ⬜  ⬜  ⚫  ❌  ⚫  ⬜  ⬜
3  ⬜  ⬜  ⚫  ❌  ⬜  ⚫  ⬜
4  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜
5  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜
6  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
2  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
3  ⬜  ⬜  ⚫  ⬜  ❌  ⬜  ⬜
4  ⬜  ⬜  ⬜  ⚫  ❌  ⬜  ⬜
5  ⬜  ⬜  ⬜  ⬜  ❌  ⚫  ⬜
6  ⬜  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜
2  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜
3  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜
4  ⚫  ⬜  ⬜  ⚫  ⬜  ❌  ⚫
5  ⬜  ⚫  ⬜  ⬜  ⚫  ❌  ⬜
6  ⬜  ⬜  ⚫  ⬜  ⬜  ❌  ⚫
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⚫  ⬜

 84%|████████▍ | 845/1000 [00:21<00:04, 38.16it/s]

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
2  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜  ⬜
3  ❌  ❌  ❌  ⚫  ⬜  ⬜  ⬜
4  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜  ⬜
5  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
6  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜
2  ❌  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜
3  ❌  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜
4  ❌  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜
5  ⚫  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜
6  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
2  ⬜  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜
3  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜
4  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜
5  ⬜  ⚫  ⚫  ⬜  ⚫  ⬜  ⬜
6  ❌  ❌  ❌  ⚫  ⬜  ⬜  ⬜
7  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜
2  ⬜  ⬜  ⬜  ⚫  ❌  ❌  ❌
3  ⬜  ⬜  ⚫  ⬜  ⚫  ⬜  ⬜
4  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜
5  ⬜  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜
6  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⬜  ❌  ❌  ❌  ⬜  ⬜  ⬜
2  ⬜  ⬜  ⚫  ⚫  ⚫  ⬜  ⬜
3  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜
4  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜
5  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜
6  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

 85%|████████▌ | 850/1000 [00:21<00:03, 38.91it/s]

   A  B  C  D  E  F  G
1  ⚫  ⚫  ⬜  ⚫  ⬜  ⬜  ⬜
2  ❌  ❌  ❌  ⬜  ⚫  ⬜  ⬜
3  ⚫  ⚫  ⚫  ⬜  ⬜  ⚫  ⬜
4  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜
5  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜
6  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
2  ⬜  ⬜  ⬜  ⬜  ⚫  ❌  ⬜
3  ⬜  ⬜  ⚫  ⬜  ⬜  ❌  ⚫
4  ⬜  ⬜  ⬜  ⚫  ⬜  ❌  ⚫
5  ⬜  ⬜  ⬜  ⬜  ⚫  ⚫  ⬜
6  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜
2  ⬜  ⬜  ⬜  ⚫  ❌  ⬜  ⬜
3  ⬜  ⬜  ⚫  ⬜  ❌  ⚫  ⬜
4  ⬜  ⬜  ⬜  ⚫  ❌  ⬜  ⬜
5  ⬜  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜
6  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
2  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
3  ⬜  ⬜  ⚫  ⬜  ❌  ⬜  ⬜
4  ⬜  ⬜  ⬜  ⚫  ❌  ⬜  ⬜
5  ⬜  ⬜  ⬜  ⬜  ❌  ⚫  ⬜
6  ⬜  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⚫  ❌  ⬜  ⬜
2  ⬜  ⬜  ⬜  ⬜  ❌  ⬜  ⬜
3  ⬜  ⬜  ⚫  ⬜  ❌  ⬜  ⬜
4  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜
5  ⬜  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜
6  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

 86%|████████▌ | 855/1000 [00:21<00:03, 40.93it/s]

   A  B  C  D  E  F  G
1  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫
2  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜
3  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜
4  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫
5  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜  ❌
6  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫  ❌
7  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜  ❌

   A  B  C  D  E  F  G
1  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫
2  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜
3  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜
4  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫
5  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜
6  ⚫  ⚫  ⚫  ⬜  ⬜  ⚫  ⬜
7  ❌  ❌  ❌  ⚫  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⬜  ⚫  ⬜  ⚫  ⬜  ⬜  ⬜
2  ⚫  ❌  ⬜  ⬜  ⚫  ⬜  ⬜
3  ⬜  ❌  ⚫  ⬜  ⬜  ⚫  ⬜
4  ⬜  ❌  ⬜  ⚫  ⬜  ⬜  ⬜
5  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜
6  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
2  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜  ⬜
3  ❌  ❌  ❌  ⚫  ⬜  ⬜  ⬜
4  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜  ⬜
5  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
6  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
2  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
3  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜  ⬜
4  ⬜  ⬜  ⬜  ❌  ⚫  ⬜  ⬜
5  ⬜  ⬜  ⬜  ❌  ⬜  ⬜  ⬜
6  ⬜  ⬜  ⬜  ❌  ⬜  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

 86%|████████▌ | 860/1000 [00:21<00:03, 40.46it/s]

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
2  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
3  ⬜  ⬜  ⚫  ⬜  ⚫  ⬜  ⬜
4  ⬜  ⬜  ❌  ❌  ❌  ⚫  ⬜
5  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜
6  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜
2  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜
3  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜
4  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫
5  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜
6  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜
7  ⬜  ❌  ❌  ❌  ⚫  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫
2  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜
3  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜
4  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫
5  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜
6  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫  ⚫
7  ⚫  ⬜  ⬜  ⚫  ❌  ❌  ❌

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜
2  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜
3  ⚫  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜
4  ❌  ⚫  ⬜  ⚫  ⬜  ⬜  ⬜
5  ❌  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜
6  ❌  ⬜  ⚫  ⬜  ⬜  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
2  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜  ⬜
3  ❌  ❌  ❌  ⚫  ⬜  ⬜  ⬜
4  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜  ⬜
5  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
6  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

 86%|████████▋ | 865/1000 [00:21<00:03, 39.86it/s]

   A  B  C  D  E  F  G
1  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫
2  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜
3  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜
4  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫
5  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜  ❌
6  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫  ❌
7  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜  ❌

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜
2  ⬜  ⬜  ⬜  ⚫  ❌  ❌  ❌
3  ⬜  ⬜  ⚫  ⬜  ⚫  ⬜  ⬜
4  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜
5  ⬜  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜
6  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
2  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
3  ⬜  ⬜  ⚫  ⚫  ⬜  ⬜  ⬜
4  ⬜  ❌  ❌  ❌  ⚫  ⬜  ⬜
5  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜
6  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
2  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
3  ⬜  ⬜  ⚫  ⚫  ⬜  ⬜  ⬜
4  ⬜  ❌  ❌  ❌  ⚫  ⬜  ⬜
5  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜
6  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
2  ⬜  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜
3  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜
4  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜
5  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜
6  ⬜  ⬜  ❌  ❌  ❌  ⬜  ⬜
7  ⬜  ⬜  ⚫  ⚫  ⬜  ⬜  ⬜

 87%|████████▋ | 870/1000 [00:22<00:03, 40.63it/s]

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
2  ⬜  ⬜  ⬜  ❌  ⬜  ⬜  ⬜
3  ⬜  ⬜  ⚫  ❌  ⬜  ⬜  ⬜
4  ⬜  ⬜  ⬜  ❌  ⚫  ⬜  ⬜
5  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜
6  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
2  ⬜  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜
3  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜
4  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜
5  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜
6  ⬜  ⬜  ❌  ❌  ❌  ⬜  ⬜
7  ⬜  ⬜  ⚫  ⚫  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⚫  ⬜  ⬜  ⚫  ❌  ❌  ❌
2  ⬜  ⚫  ⬜  ⬜  ⚫  ⚫  ⚫
3  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜
4  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫
5  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜
6  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜
7  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫
2  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜
3  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜
4  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫
5  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜
6  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫  ⚫
7  ⚫  ⬜  ⬜  ⚫  ❌  ❌  ❌

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
2  ⬜  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜
3  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜
4  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜
5  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜
6  ⬜  ⬜  ❌  ❌  ❌  ⬜  ⬜
7  ⬜  ⬜  ⚫  ⚫  ⬜  ⬜  ⬜

 88%|████████▊ | 875/1000 [00:22<00:03, 40.01it/s]

   A  B  C  D  E  F  G
1  ⬜  ⚫  ⬜  ⚫  ⬜  ⬜  ⬜
2  ⚫  ❌  ⬜  ⬜  ⚫  ⬜  ⬜
3  ⬜  ❌  ⚫  ⬜  ⬜  ⚫  ⬜
4  ⬜  ❌  ⬜  ⚫  ⬜  ⬜  ⬜
5  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜
6  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
2  ⬜  ⬜  ⬜  ⬜  ⚫  ⚫  ⬜
3  ⬜  ⬜  ⚫  ⬜  ❌  ❌  ❌
4  ⬜  ⬜  ⬜  ⚫  ⬜  ⚫  ⚫
5  ⬜  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜
6  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜
2  ⬜  ⬜  ⬜  ⚫  ❌  ⬜  ⬜
3  ⬜  ⬜  ⚫  ⬜  ❌  ⚫  ⬜
4  ⬜  ⬜  ⬜  ⚫  ❌  ⬜  ⬜
5  ⬜  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜
6  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫
2  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜
3  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜
4  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫
5  ❌  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜
6  ❌  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜
7  ❌  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
2  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
3  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜  ⬜
4  ⬜  ⬜  ⬜  ⚫  ⚫  ⬜  ⬜
5  ⬜  ⬜  ⬜  ❌  ❌  ❌  ⚫
6  ⬜  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

 88%|████████▊ | 880/1000 [00:22<00:03, 39.73it/s]

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
2  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
3  ⬜  ⬜  ⚫  ❌  ⬜  ⬜  ⬜
4  ⬜  ⬜  ⬜  ❌  ⚫  ⬜  ⬜
5  ⬜  ⬜  ⚫  ❌  ⬜  ⬜  ⬜
6  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
2  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜  ⬜
3  ❌  ❌  ❌  ⚫  ⬜  ⬜  ⬜
4  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜  ⬜
5  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
6  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫
2  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜
3  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜
4  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫
5  ❌  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜
6  ❌  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜
7  ❌  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜
2  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜
3  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜
4  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫
5  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜
6  ⬜  ⬜  ⚫  ⚫  ⚫  ⚫  ⬜
7  ⬜  ⬜  ⚫  ❌  ❌  ❌  ⬜

 88%|████████▊ | 884/1000 [00:22<00:02, 39.49it/s]

   A  B  C  D  E  F  G
1  ⬜  ❌  ❌  ❌  ⬜  ⬜  ⬜
2  ⬜  ⬜  ⚫  ⚫  ⚫  ⬜  ⬜
3  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜
4  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜
5  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜
6  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
2  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
3  ⬜  ⬜  ❌  ❌  ❌  ⬜  ⬜
4  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜  ⬜
5  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
6  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
2  ⬜  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜
3  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜
4  ⬜  ⬜  ❌  ⚫  ⬜  ⬜  ⬜
5  ⬜  ⚫  ❌  ⬜  ⚫  ⬜  ⬜
6  ⬜  ⬜  ❌  ⚫  ⬜  ⬜  ⬜
7  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜
2  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜
3  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫  ⚫
4  ⚫  ⬜  ⬜  ⚫  ❌  ❌  ❌
5  ⬜  ⚫  ⬜  ⬜  ⚫  ⚫  ⚫
6  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⬜  ❌  ❌  ❌  ⬜  ⬜  ⬜
2  ⬜  ⬜  ⚫  ⚫  ⚫  ⬜  ⬜
3  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜
4  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜
5  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜
6  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

 89%|████████▉ | 889/1000 [00:22<00:02, 39.84it/s]

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
2  ⬜  ⬜  ⬜  ❌  ⬜  ⬜  ⬜
3  ⬜  ⬜  ⚫  ❌  ⬜  ⬜  ⬜
4  ⬜  ⬜  ⬜  ❌  ⚫  ⬜  ⬜
5  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜
6  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜
2  ⬜  ⬜  ⬜  ⚫  ❌  ❌  ❌
3  ⬜  ⬜  ⚫  ⬜  ⚫  ⬜  ⬜
4  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜
5  ⬜  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜
6  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜
2  ⬜  ⬜  ⬜  ❌  ❌  ❌  ⬜
3  ⬜  ⬜  ⚫  ⬜  ⚫  ⬜  ⬜
4  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜
5  ⬜  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜
6  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
2  ⬜  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜
3  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜
4  ⬜  ⚫  ⬜  ⚫  ⬜  ⬜  ⬜
5  ⚫  ❌  ❌  ❌  ⚫  ⬜  ⬜
6  ⬜  ⚫  ⚫  ⬜  ⬜  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜
2  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜
3  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫  ⚫
4  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜  ❌
5  ⬜  ⚫  ⬜  ⬜  ⚫  ⚫  ❌
6  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜  ❌
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

 89%|████████▉ | 894/1000 [00:22<00:02, 40.10it/s]

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
2  ⬜  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜
3  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜
4  ⬜  ❌  ⬜  ⚫  ⬜  ⬜  ⬜
5  ⚫  ❌  ⬜  ⬜  ⚫  ⬜  ⬜
6  ⬜  ❌  ⬜  ⬜  ⬜  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
2  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜  ⬜
3  ❌  ❌  ❌  ⚫  ⬜  ⬜  ⬜
4  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜  ⬜
5  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
6  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⬜  ⚫  ❌  ❌  ❌  ⬜  ⬜
2  ⬜  ⬜  ⚫  ⚫  ⚫  ⬜  ⬜
3  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜
4  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜
5  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜
6  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
2  ⬜  ⬜  ⬜  ⬜  ⚫  ⚫  ⬜
3  ⬜  ⬜  ⚫  ❌  ❌  ❌  ⚫
4  ⬜  ⬜  ⬜  ⚫  ⬜  ⚫  ⬜
5  ⬜  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜
6  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
2  ⬜  ⬜  ❌  ⬜  ⬜  ⬜  ⬜
3  ⬜  ⬜  ❌  ⚫  ⬜  ⬜  ⬜
4  ⬜  ⬜  ❌  ⬜  ⬜  ⬜  ⬜
5  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜  ⬜
6  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

 90%|████████▉ | 899/1000 [00:22<00:02, 41.59it/s]

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
2  ⬜  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜
3  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜
4  ⬜  ⬜  ❌  ⚫  ⬜  ⬜  ⬜
5  ⬜  ⚫  ❌  ⬜  ⚫  ⬜  ⬜
6  ⬜  ⬜  ❌  ⚫  ⬜  ⬜  ⬜
7  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫
2  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜
3  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜
4  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫
5  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜  ❌
6  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫  ❌
7  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜  ❌

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
2  ⬜  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜
3  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜
4  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜
5  ⬜  ⚫  ⚫  ⬜  ⚫  ⬜  ⬜
6  ❌  ❌  ❌  ⚫  ⬜  ⬜  ⬜
7  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⬜  ❌  ❌  ❌  ⬜  ⬜  ⬜
2  ⬜  ⬜  ⚫  ⚫  ⚫  ⬜  ⬜
3  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜
4  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜
5  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜
6  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
2  ⬜  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜
3  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜
4  ⬜  ⬜  ❌  ⚫  ⬜  ⬜  ⬜
5  ⬜  ⚫  ❌  ⬜  ⚫  ⬜  ⬜
6  ⬜  ⬜  ❌  ⚫  ⬜  ⬜  ⬜
7  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜  ⬜

 90%|█████████ | 904/1000 [00:22<00:02, 40.90it/s]

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⚫  ❌  ❌  ❌  ⬜
2  ⬜  ⬜  ⬜  ⚫  ⚫  ⬜  ⬜
3  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜
4  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜
5  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜
6  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⚫  ❌  ⚫  ⚫  ⬜  ⬜  ⬜
2  ⚫  ❌  ⬜  ⬜  ⚫  ⬜  ⬜
3  ⬜  ❌  ⚫  ⬜  ⬜  ⚫  ⬜
4  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜
5  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜
6  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
2  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
3  ⬜  ⬜  ⚫  ⬜  ❌  ⬜  ⬜
4  ⬜  ⬜  ⬜  ⚫  ❌  ⬜  ⬜
5  ⬜  ⬜  ⬜  ⬜  ❌  ⚫  ⬜
6  ⬜  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜
2  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜
3  ⚫  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜
4  ❌  ⚫  ⬜  ⚫  ⬜  ⬜  ⬜
5  ❌  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜
6  ❌  ⬜  ⚫  ⬜  ⬜  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
2  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜  ⬜
3  ❌  ❌  ❌  ⚫  ⬜  ⬜  ⬜
4  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜  ⬜
5  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
6  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

 91%|█████████ | 909/1000 [00:23<00:02, 41.32it/s]

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜
2  ⬜  ⬜  ⬜  ⚫  ❌  ❌  ❌
3  ⬜  ⬜  ⚫  ⬜  ⚫  ⬜  ⬜
4  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜
5  ⬜  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜
6  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
2  ⬜  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜
3  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜
4  ⬜  ⬜  ❌  ⚫  ⬜  ⬜  ⬜
5  ⬜  ⚫  ❌  ⬜  ⚫  ⬜  ⬜
6  ⬜  ⬜  ❌  ⚫  ⬜  ⬜  ⬜
7  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
2  ⬜  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜
3  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜
4  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜
5  ⬜  ⚫  ⚫  ⬜  ⚫  ⬜  ⬜
6  ⬜  ❌  ❌  ❌  ⚫  ⬜  ⬜
7  ⬜  ⬜  ⚫  ⚫  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜
2  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜
3  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜
4  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫
5  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜
6  ⬜  ⬜  ⚫  ⚫  ⚫  ⚫  ⬜
7  ⬜  ⬜  ⚫  ❌  ❌  ❌  ⬜

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜
2  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜
3  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜
4  ⚫  ⬜  ⬜  ⚫  ⬜  ❌  ⚫
5  ⬜  ⚫  ⬜  ⬜  ⚫  ❌  ⬜
6  ⬜  ⬜  ⚫  ⬜  ⬜  ❌  ⚫
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⚫  ⬜

 91%|█████████▏| 914/1000 [00:23<00:02, 39.97it/s]

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
2  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
3  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜  ⬜
4  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜
5  ⬜  ⬜  ⬜  ⬜  ❌  ❌  ❌
6  ⬜  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
2  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
3  ⬜  ⬜  ⚫  ⬜  ❌  ⬜  ⬜
4  ⬜  ⬜  ⬜  ⚫  ❌  ⬜  ⬜
5  ⬜  ⬜  ⬜  ⬜  ❌  ⚫  ⬜
6  ⬜  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫
2  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜
3  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜
4  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫
5  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜  ❌
6  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫  ❌
7  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜  ❌

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜
2  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜
3  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜
4  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫
5  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜
6  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜
7  ⬜  ❌  ❌  ❌  ⚫  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
2  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜  ⬜
3  ⬜  ❌  ❌  ❌  ⚫  ⬜  ⬜
4  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜  ⬜
5  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
6  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

 92%|█████████▏| 919/1000 [00:23<00:01, 41.31it/s]

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
2  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
3  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜  ⬜
4  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜
5  ⬜  ⬜  ⬜  ⬜  ❌  ⚫  ⬜
6  ⬜  ⬜  ⬜  ⬜  ❌  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ❌  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜
2  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜
3  ⚫  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜
4  ❌  ⚫  ⬜  ⚫  ⬜  ⬜  ⬜
5  ❌  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜
6  ❌  ⬜  ⚫  ⬜  ⬜  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
2  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
3  ⬜  ⬜  ⚫  ❌  ⬜  ⬜  ⬜
4  ⬜  ⬜  ⬜  ❌  ⚫  ⬜  ⬜
5  ⬜  ⬜  ⚫  ❌  ⬜  ⬜  ⬜
6  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
2  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
3  ⬜  ⬜  ⚫  ❌  ⬜  ⬜  ⬜
4  ⬜  ⬜  ⬜  ❌  ⚫  ⬜  ⬜
5  ⬜  ⬜  ⚫  ❌  ⬜  ⬜  ⬜
6  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
2  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
3  ⬜  ⬜  ❌  ⚫  ⬜  ⬜  ⬜
4  ⬜  ⬜  ❌  ⬜  ⬜  ⬜  ⬜
5  ⬜  ⬜  ❌  ⬜  ⬜  ⬜  ⬜
6  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

 92%|█████████▏| 924/1000 [00:23<00:01, 43.53it/s]

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜
2  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜
3  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫  ⚫
4  ⚫  ⬜  ⬜  ⚫  ❌  ❌  ❌
5  ⬜  ⚫  ⬜  ⬜  ⚫  ⚫  ⚫
6  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⬜  ⬜  ❌  ⬜  ⬜  ⬜  ⬜
2  ⬜  ⬜  ❌  ⬜  ⬜  ⬜  ⬜
3  ⬜  ⬜  ❌  ⚫  ⬜  ⬜  ⬜
4  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜  ⬜
5  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
6  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⬜  ❌  ❌  ❌  ⬜  ⬜  ⬜
2  ⬜  ⬜  ⚫  ⚫  ⚫  ⬜  ⬜
3  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜
4  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜
5  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜
6  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ❌  ❌  ❌  ⚫  ⬜  ⬜  ⬜
2  ⚫  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜
3  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜
4  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫
5  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜
6  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜
7  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⚫  ⬜  ⬜  ⚫  ⬜  ⚫  ❌
2  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜  ❌
3  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫  ❌
4  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫
5  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜
6  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜
7  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜

 93%|█████████▎| 929/1000 [00:23<00:01, 41.23it/s]

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜
2  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜
3  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜
4  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫
5  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜
6  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜
7  ⬜  ❌  ❌  ❌  ⚫  ⬜  ⬜

   A  B  C  D  E  F  G
1  ❌  ❌  ❌  ⚫  ⬜  ⬜  ⬜
2  ⚫  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜
3  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜
4  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫
5  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜
6  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜
7  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜
2  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜
3  ⚫  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜
4  ❌  ⚫  ⬜  ⚫  ⬜  ⬜  ⬜
5  ❌  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜
6  ❌  ⬜  ⚫  ⬜  ⬜  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜
2  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜
3  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜
4  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫
5  ⬜  ⚫  ⬜  ⬜  ⚫  ❌  ⬜
6  ⬜  ⬜  ⚫  ⬜  ⬜  ❌  ⚫
7  ⬜  ⬜  ⬜  ⬜  ⚫  ❌  ⬜

   A  B  C  D  E  F  G
1  ⬜  ⚫  ⚫  ⚫  ⬜  ⬜  ⬜
2  ⚫  ❌  ❌  ❌  ⚫  ⬜  ⬜
3  ⬜  ⚫  ⚫  ⬜  ⬜  ⚫  ⬜
4  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜
5  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜
6  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

 93%|█████████▎| 934/1000 [00:23<00:01, 38.83it/s]

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
2  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
3  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜  ⬜
4  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜
5  ⬜  ⬜  ⬜  ⬜  ❌  ❌  ❌
6  ⬜  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜
2  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜
3  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜
4  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫
5  ⬜  ⚫  ⬜  ⬜  ⚫  ⚫  ⬜
6  ⬜  ⬜  ⚫  ❌  ❌  ❌  ⚫
7  ⬜  ⬜  ⬜  ⬜  ⚫  ⚫  ⬜

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
2  ⬜  ⬜  ❌  ⬜  ⬜  ⬜  ⬜
3  ⬜  ⬜  ❌  ⚫  ⬜  ⬜  ⬜
4  ⬜  ⬜  ❌  ⬜  ⬜  ⬜  ⬜
5  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜  ⬜
6  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜
2  ⬜  ⬜  ⬜  ⚫  ❌  ⬜  ⬜
3  ⬜  ⬜  ⚫  ⬜  ❌  ⚫  ⬜
4  ⬜  ⬜  ⬜  ⚫  ❌  ⬜  ⬜
5  ⬜  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜
6  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
2  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
3  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜  ⬜
4  ⬜  ⬜  ⬜  ❌  ⚫  ⬜  ⬜
5  ⬜  ⬜  ⬜  ❌  ⬜  ⬜  ⬜
6  ⬜  ⬜  ⬜  ❌  ⬜  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

 94%|█████████▍| 939/1000 [00:23<00:01, 40.98it/s]

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
2  ⬜  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜
3  ⬜  ❌  ⚫  ⬜  ⬜  ⚫  ⬜
4  ⬜  ❌  ⬜  ⚫  ⬜  ⬜  ⬜
5  ⚫  ❌  ⚫  ⬜  ⚫  ⬜  ⬜
6  ⬜  ⚫  ⬜  ⬜  ⬜  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜
2  ❌  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜
3  ❌  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜
4  ❌  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜
5  ⚫  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜
6  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜
2  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜
3  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫  ⚫
4  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜  ❌
5  ⬜  ⚫  ⬜  ⬜  ⚫  ⚫  ❌
6  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜  ❌
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜
2  ⬜  ⬜  ⬜  ⚫  ❌  ❌  ❌
3  ⬜  ⬜  ⚫  ⬜  ⚫  ⬜  ⬜
4  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜
5  ⬜  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜
6  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
2  ⬜  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜
3  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜
4  ⬜  ⚫  ⬜  ⚫  ⬜  ⬜  ⬜
5  ⚫  ❌  ⬜  ⬜  ⚫  ⬜  ⬜
6  ⬜  ❌  ⚫  ⬜  ⬜  ⬜  ⬜
7  ⬜  ❌  ⬜  ⬜  ⬜  ⬜  ⬜

 94%|█████████▍| 944/1000 [00:23<00:01, 40.20it/s]

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
2  ⬜  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜
3  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜
4  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜
5  ❌  ❌  ❌  ⬜  ⚫  ⬜  ⬜
6  ⬜  ⚫  ⬜  ⬜  ⬜  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⚫  ❌  ⚫  ⚫  ⬜  ⬜  ⬜
2  ⚫  ❌  ⬜  ⬜  ⚫  ⬜  ⬜
3  ⬜  ❌  ⚫  ⬜  ⬜  ⚫  ⬜
4  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜
5  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜
6  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
2  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
3  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜  ⬜
4  ⬜  ⬜  ⬜  ⚫  ⚫  ⬜  ⬜
5  ⬜  ⬜  ⬜  ❌  ❌  ❌  ⚫
6  ⬜  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
2  ⬜  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜
3  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜
4  ⬜  ⬜  ❌  ⚫  ⬜  ⬜  ⬜
5  ⬜  ⚫  ❌  ⬜  ⚫  ⬜  ⬜
6  ⬜  ⬜  ❌  ⚫  ⬜  ⬜  ⬜
7  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
2  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
3  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜  ⬜
4  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜
5  ⬜  ⬜  ⬜  ⬜  ❌  ❌  ❌
6  ⬜  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

 95%|█████████▍| 949/1000 [00:23<00:01, 40.98it/s]

   A  B  C  D  E  F  G
1  ⬜  ❌  ❌  ❌  ⬜  ⬜  ⬜
2  ⬜  ⬜  ⚫  ⚫  ⚫  ⬜  ⬜
3  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜
4  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜
5  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜
6  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜
2  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜
3  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜
4  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫
5  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜
6  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜
7  ⬜  ❌  ❌  ❌  ⚫  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜
2  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜
3  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜
4  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫
5  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜
6  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜
7  ⬜  ❌  ❌  ❌  ⚫  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫
2  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜
3  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜
4  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫
5  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜  ❌
6  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫  ❌
7  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜  ❌

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
2  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜  ⬜
3  ⬜  ❌  ❌  ❌  ⚫  ⬜  ⬜
4  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜  ⬜
5  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
6  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

 95%|█████████▌| 954/1000 [00:24<00:01, 39.29it/s]

   A  B  C  D  E  F  G
1  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫
2  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜
3  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜
4  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫
5  ❌  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜
6  ❌  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜
7  ❌  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⚫  ❌  ⚫  ⬜  ⬜
2  ⬜  ⬜  ⚫  ❌  ⚫  ⬜  ⬜
3  ⬜  ⬜  ⚫  ❌  ⬜  ⚫  ⬜
4  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜
5  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜
6  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜
2  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜
3  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜
4  ⚫  ⬜  ⬜  ⚫  ⬜  ❌  ⚫
5  ⬜  ⚫  ⬜  ⬜  ⚫  ❌  ⬜
6  ⬜  ⬜  ⚫  ⬜  ⬜  ❌  ⚫
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⚫  ⬜

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
2  ⬜  ⬜  ⬜  ⬜  ⚫  ❌  ⬜
3  ⬜  ⬜  ⚫  ⬜  ⬜  ❌  ⚫
4  ⬜  ⬜  ⬜  ⚫  ⬜  ❌  ⚫
5  ⬜  ⬜  ⬜  ⬜  ⚫  ⚫  ⬜
6  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

 96%|█████████▌| 958/1000 [00:24<00:01, 38.50it/s]

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜
2  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜
3  ⚫  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜
4  ❌  ⚫  ⬜  ⚫  ⬜  ⬜  ⬜
5  ❌  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜
6  ❌  ⬜  ⚫  ⬜  ⬜  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⬜  ❌  ❌  ❌  ⬜  ⬜  ⬜
2  ⬜  ⬜  ⚫  ⚫  ⚫  ⬜  ⬜
3  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜
4  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜
5  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜
6  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
2  ⬜  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜
3  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜
4  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜
5  ❌  ❌  ❌  ⬜  ⚫  ⬜  ⬜
6  ⬜  ⚫  ⬜  ⬜  ⬜  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⬜  ⬜  ❌  ⬜  ⬜  ⬜  ⬜
2  ⬜  ⬜  ❌  ⬜  ⬜  ⬜  ⬜
3  ⬜  ⬜  ❌  ⚫  ⬜  ⬜  ⬜
4  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜  ⬜
5  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
6  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
2  ⬜  ⬜  ⬜  ⬜  ⚫  ⚫  ⬜
3  ⬜  ⬜  ⚫  ❌  ❌  ❌  ⚫
4  ⬜  ⬜  ⬜  ⚫  ⬜  ⚫  ⬜
5  ⬜  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜
6  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

 96%|█████████▋| 963/1000 [00:24<00:00, 40.07it/s]

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
2  ⬜  ⬜  ⬜  ⬜  ⚫  ⚫  ⬜
3  ⬜  ⬜  ⚫  ❌  ❌  ❌  ⚫
4  ⬜  ⬜  ⬜  ⚫  ⬜  ⚫  ⬜
5  ⬜  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜
6  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
2  ⬜  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜
3  ⬜  ⬜  ⚫  ⬜  ⬜  ❌  ⚫
4  ⬜  ⬜  ⬜  ⚫  ⬜  ❌  ⬜
5  ⬜  ⬜  ⬜  ⬜  ⚫  ❌  ⬜
6  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⬜  ⚫  ⚫  ⚫  ⬜  ⬜  ⬜
2  ⚫  ❌  ❌  ❌  ⚫  ⬜  ⬜
3  ⬜  ⚫  ⚫  ⬜  ⬜  ⚫  ⬜
4  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜
5  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜
6  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
2  ⬜  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜
3  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜
4  ⬜  ⚫  ⬜  ⚫  ⬜  ⬜  ⬜
5  ⚫  ❌  ❌  ❌  ⚫  ⬜  ⬜
6  ⬜  ⚫  ⚫  ⬜  ⬜  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
2  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
3  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜  ⬜
4  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜
5  ⬜  ⬜  ⬜  ⬜  ❌  ⚫  ⬜
6  ⬜  ⬜  ⬜  ⬜  ❌  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ❌  ⬜  ⬜

 97%|█████████▋| 968/1000 [00:24<00:00, 41.39it/s]

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜
2  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜
3  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫  ⚫
4  ⚫  ⬜  ⬜  ⚫  ❌  ❌  ❌
5  ⬜  ⚫  ⬜  ⬜  ⚫  ⚫  ⚫
6  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
2  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
3  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜  ⬜
4  ⬜  ⬜  ⬜  ⚫  ❌  ⬜  ⬜
5  ⬜  ⬜  ⬜  ⬜  ❌  ⚫  ⬜
6  ⬜  ⬜  ⬜  ⬜  ❌  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜
2  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜
3  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜
4  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫
5  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜
6  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜
7  ⬜  ⬜  ❌  ❌  ❌  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
2  ⬜  ⬜  ⬜  ⬜  ⚫  ❌  ⬜
3  ⬜  ⬜  ⚫  ⬜  ⬜  ❌  ⚫
4  ⬜  ⬜  ⬜  ⚫  ⬜  ❌  ⚫
5  ⬜  ⬜  ⬜  ⬜  ⚫  ⚫  ⬜
6  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⚫  ❌  ⬜  ⬜
2  ⬜  ⬜  ⬜  ⬜  ❌  ⬜  ⬜
3  ⬜  ⬜  ⚫  ⬜  ❌  ⬜  ⬜
4  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜
5  ⬜  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜
6  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

 97%|█████████▋| 973/1000 [00:24<00:00, 41.25it/s]

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
2  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
3  ⬜  ⬜  ⚫  ⬜  ⚫  ⬜  ⬜
4  ⬜  ⬜  ⬜  ❌  ❌  ❌  ⬜
5  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜
6  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
2  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
3  ⬜  ⬜  ⚫  ⬜  ⚫  ⬜  ⬜
4  ⬜  ⬜  ❌  ❌  ❌  ⚫  ⬜
5  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜
6  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
2  ⬜  ⬜  ⬜  ❌  ⬜  ⬜  ⬜
3  ⬜  ⬜  ⚫  ❌  ⬜  ⬜  ⬜
4  ⬜  ⬜  ⬜  ❌  ⚫  ⬜  ⬜
5  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜
6  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
2  ⬜  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜
3  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜
4  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜
5  ⬜  ⚫  ⚫  ⬜  ⚫  ⬜  ⬜
6  ⬜  ❌  ❌  ❌  ⚫  ⬜  ⬜
7  ⬜  ⬜  ⚫  ⚫  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⬜  ⬜  ❌  ⬜
2  ⬜  ⬜  ⬜  ⬜  ⚫  ❌  ⬜
3  ⬜  ⬜  ⚫  ⬜  ⬜  ❌  ⚫
4  ⬜  ⬜  ⬜  ⚫  ⬜  ⚫  ⬜
5  ⬜  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜
6  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

 98%|█████████▊| 978/1000 [00:24<00:00, 43.34it/s]

   A  B  C  D  E  F  G
1  ⚫  ⬜  ⬜  ⚫  ⬜  ⚫  ❌
2  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜  ❌
3  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫  ❌
4  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫
5  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜
6  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜
7  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
2  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
3  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜  ⬜
4  ⬜  ⬜  ⬜  ⚫  ❌  ⬜  ⬜
5  ⬜  ⬜  ⬜  ⬜  ❌  ⚫  ⬜
6  ⬜  ⬜  ⬜  ⬜  ❌  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⚫  ❌  ⚫  ⚫  ⬜  ⬜  ⬜
2  ⚫  ❌  ⬜  ⬜  ⚫  ⬜  ⬜
3  ⬜  ❌  ⚫  ⬜  ⬜  ⚫  ⬜
4  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜
5  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜
6  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜
2  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜
3  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜
4  ⚫  ⬜  ⬜  ⚫  ⬜  ❌  ⚫
5  ⬜  ⚫  ⬜  ⬜  ⚫  ❌  ⬜
6  ⬜  ⬜  ⚫  ⬜  ⬜  ❌  ⚫
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⚫  ⬜

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜
2  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜
3  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜
4  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫
5  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜
6  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜
7  ⬜  ❌  ❌  ❌  ⚫  ⬜  ⬜

 98%|█████████▊| 983/1000 [00:24<00:00, 41.47it/s]

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
2  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
3  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜  ⬜
4  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜
5  ⬜  ⬜  ⬜  ⬜  ❌  ⚫  ⬜
6  ⬜  ⬜  ⬜  ⬜  ❌  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ❌  ⬜  ⬜

   A  B  C  D  E  F  G
1  ❌  ⚫  ⬜  ⚫  ⬜  ⬜  ⬜
2  ❌  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜
3  ❌  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜
4  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫
5  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜
6  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜
7  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
2  ⬜  ⬜  ❌  ⬜  ⬜  ⬜  ⬜
3  ⬜  ⬜  ❌  ⚫  ⬜  ⬜  ⬜
4  ⬜  ⬜  ❌  ⬜  ⬜  ⬜  ⬜
5  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜  ⬜
6  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
2  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
3  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜  ⬜
4  ⬜  ⬜  ⬜  ❌  ⚫  ⬜  ⬜
5  ⬜  ⬜  ⬜  ❌  ⬜  ⬜  ⬜
6  ⬜  ⬜  ⬜  ❌  ⬜  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜
2  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜
3  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫  ⚫
4  ⚫  ⬜  ⬜  ⚫  ❌  ❌  ❌
5  ⬜  ⚫  ⬜  ⬜  ⚫  ⚫  ⚫
6  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

 99%|█████████▉| 988/1000 [00:24<00:00, 42.74it/s]

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⚫  ❌  ⚫  ⬜  ⬜
2  ⬜  ⬜  ⚫  ❌  ⚫  ⬜  ⬜
3  ⬜  ⬜  ⚫  ❌  ⬜  ⚫  ⬜
4  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜
5  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜
6  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
2  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
3  ⬜  ⬜  ❌  ❌  ❌  ⬜  ⬜
4  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜  ⬜
5  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
6  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
2  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
3  ⬜  ⬜  ❌  ⚫  ⬜  ⬜  ⬜
4  ⬜  ⬜  ❌  ⬜  ⬜  ⬜  ⬜
5  ⬜  ⬜  ❌  ⬜  ⬜  ⬜  ⬜
6  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜
2  ⬜  ⬜  ⬜  ❌  ❌  ❌  ⬜
3  ⬜  ⬜  ⚫  ⬜  ⚫  ⬜  ⬜
4  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜
5  ⬜  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜
6  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
2  ⬜  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜
3  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜
4  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜
5  ⬜  ⚫  ⚫  ⬜  ⚫  ⬜  ⬜
6  ❌  ❌  ❌  ⚫  ⬜  ⬜  ⬜
7  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⚫  ⚫  ⬜  ⬜
2  ⬜  ⬜  ❌  ❌  ❌  ⚫  ⬜
3  ⬜  ⬜  ⚫  ⬜  ⚫  ⬜  ⬜
4  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜
5  ⬜  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜
6  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

 99%|█████████▉| 994/1000 [00:25<00:00, 44.79it/s]

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⚫  ❌  ⬜  ⬜
2  ⬜  ⬜  ⬜  ⬜  ❌  ⬜  ⬜
3  ⬜  ⬜  ⚫  ⬜  ❌  ⬜  ⬜
4  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜
5  ⬜  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜
6  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜
2  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜
3  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜
4  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫
5  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜
6  ⬜  ⬜  ⚫  ⚫  ⚫  ⚫  ⬜
7  ⬜  ⬜  ⚫  ❌  ❌  ❌  ⬜

   A  B  C  D  E  F  G
1  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫
2  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜
3  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜
4  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫
5  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜  ❌
6  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫  ❌
7  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜  ❌

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜
2  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜
3  ⚫  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜
4  ❌  ⚫  ⬜  ⚫  ⬜  ⬜  ⬜
5  ❌  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜
6  ❌  ⬜  ⚫  ⬜  ⬜  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

   A  B  C  D  E  F  G
1  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜
2  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜  ❌
3  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫  ❌
4  ⚫  ⬜  ⬜  ⚫  ⬜  ⚫  ❌
5  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜  ⚫
6  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜  ⬜
7  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜  ⬜

100%|█████████▉| 999/1000 [00:25<00:00, 41.94it/s]

   A  B  C  D  E  F  G
1  ⚫  ⬜  ⬜  ⚫  ❌  ❌  ❌
2  ⬜  ⚫  ⬜  ⬜  ⚫  ⚫  ⚫
3  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜
4  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫
5  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜  ⬜
6  ⬜  ⬜  ⚫  ⬜  ⬜  ⚫  ⬜
7  ⬜  ⬜  ⬜  ⚫  ⬜  ⬜  ⬜

100%|██████████| 1000/1000 [00:25<00:00, 39.66it/s]

Episodes: 1000
Reward: min 97.75, max 101.75, mean 99.862, median: 100.0
Steps: min 4, max 20, mean 11.552, median: 11.0